registerGames([
// === ADVENTURE ===
{id:"tlou2",name:"The Last of Us Part II",genre:"Action / Survival",category:"adventure",icon:"🍄",color:"#3a5a2e",
desc:"Survive in a brutal post-apocalyptic world. Stealth, crafting, and intense combat.",tags:["Action","Survival","Stealth","Story"],
tips:[
{level:"beginner",section:"Stealth",title:"Listen Mode",controls:["R1 (hold)"],desc:"See enemies through walls.",why:"Plan your approach. Know every enemy position."},
{level:"beginner",section:"Stealth",title:"Crouch",controls:["○"],desc:"Move silently while crouched.",why:"Stealth kills save ammo. Resources are scarce."},
{level:"beginner",section:"Combat",title:"Melee",controls:["□"],desc:"Melee strikes.",why:"Saves ammo but risky. Combine with stealth for silent kills."},
{level:"beginner",section:"Combat",title:"Aim & Shoot",controls:["L2 + R2"],desc:"Aim and fire. Hold R1 while aiming to steady.",why:"Aim sways without upgrades. Hold breath to steady."},
{level:"beginner",section:"Crafting",title:"Craft Items",controls:["Hold D-Pad"],desc:"Craft health kits, molotovs, and melee upgrades.",why:"Time doesn't stop while crafting. Find a safe spot."},
{level:"intermediate",section:"Stealth",title:"Prone",controls:["○ while crouched"],desc:"Go prone. Crawl through grass and under objects.",why:"Invisible in tall grass. Crawl under cars to hide."},
{level:"intermediate",section:"Combat",title:"Throw Distraction",controls:["L2 + R1"],desc:"Throw bricks/bottles to distract or stun enemies.",why:"Lure enemies into ambush positions."},
{level:"intermediate",section:"Combat",title:"Dodge in Melee",controls:["L1"],desc:"Dodge melee attacks from enemies.",why:"Dodge then counter. Essential against Shamblers and Bloaters."},
{level:"advanced",section:"Combat",title:"Trip Mine + Bait",controls:["Place mine → throw bottle nearby"],desc:"Lure enemies into your trap mine with a distraction.",why:"Kills 3-4 at once. Most efficient explosive use."},
{level:"advanced",section:"Stealth",title:"Stealth Chain",controls:["Kill → prone → next kill"],desc:"Stealth kill, immediately go prone, crawl to next target.",why:"Nearby enemies briefly look at kill location. You're invisible prone."},
{level:"expert",section:"Combat",title:"Smoke + Shiv Rush",controls:["Smoke bomb → shiv kills"],desc:"Smoke bomb then rush with shiv for multiple instant kills.",why:"Clears rooms using only smoke + shiv. Maximum efficiency."}
]},
{id:"uncharted4",name:"Uncharted 4: A Thief's End",genre:"Action / Adventure",category:"adventure",icon:"🏴‍☠️",color:"#c49a1a",
desc:"Nathan Drake's final adventure. Climbing, gunplay, stealth, and cinematic action.",tags:["Action","Adventure","Story","PS Exclusive"],
tips:[
{level:"beginner",section:"Movement",title:"Climb",controls:["Left Stick + X"],desc:"Move toward handholds and jump to grab them.",why:"Climbing is natural. Look for yellow/white markers for climbable surfaces."},
{level:"beginner",section:"Movement",title:"Rope Swing",controls:["L1 to throw → swing → X to jump"],desc:"Throw your grappling hook and swing across gaps.",why:"Rope swinging opens up new routes and looks incredible."},
{level:"beginner",section:"Combat",title:"Shoot",controls:["L2 + R2"],desc:"Standard aim and fire.",why:"Cover is essential in Uncharted. Don't stand in the open."},
{level:"beginner",section:"Combat",title:"Take Cover",controls:["○ near cover"],desc:"Press Circle near walls and objects for cover.",why:"Pop out, shoot, duck back. The core gunplay loop."},
{level:"beginner",section:"Combat",title:"Melee",controls:["□"],desc:"Punch enemies. Chain for combos.",why:"Melee is very powerful in Uncharted, especially from above."},
{level:"beginner",section:"Combat",title:"Grenade",controls:["L1"],desc:"Throw grenades to flush enemies from cover.",why:"Grenades force enemies to move from safe positions."},
{level:"intermediate",section:"Stealth",title:"Stealth Takedown",controls:["□ from behind/above"],desc:"Silent takedown from stealth.",why:"Clear enemies without alerting others. Saves ammo."},
{level:"intermediate",section:"Stealth",title:"Mark Enemies",controls:["L3 on enemies while in stealth"],desc:"Tag enemies to track them through walls.",why:"Know every enemy position before engaging."},
{level:"intermediate",section:"Combat",title:"Rope Attack",controls:["L1 → swing into enemies + □"],desc:"Swing on rope and melee enemies as you fly past.",why:"Spectacular and effective. Knocks groups off ledges."},
{level:"intermediate",section:"Movement",title:"Slide Down Slopes",controls:["Approach slope → auto-slide"],desc:"Use slopes for fast movement and dramatic escapes.",why:"Slides maintain speed and look cinematic."},
{level:"advanced",section:"Combat",title:"Aerial Takedown",controls:["Jump from above → □"],desc:"Jump from a height onto an enemy for an instant takedown.",why:"Silent, instant, and incredibly satisfying from height."},
{level:"advanced",section:"Combat",title:"Pull Down",controls:["□ near ledge with enemy above/below"],desc:"Pull enemies off ledges to their doom.",why:"Instant, silent ledge kills. Very efficient."},
{level:"expert",section:"Combat",title:"Chain Stealth Clears",controls:["Stealth kill → rope to new position → repeat"],desc:"Clear entire arenas without being detected.",why:"On Crushing difficulty, stealth is almost mandatory."},
{level:"expert",section:"Combat",title:"Explosive Chain Reaction",controls:["Shoot explosive barrels near groups"],desc:"Use environmental explosives to wipe groups.",why:"One shot, multiple kills. Read the environment before fighting."}
]},
// === RACING ===
{id:"gt7",name:"Gran Turismo 7",genre:"Racing / Simulation",category:"racing",icon:"🏎️",color:"#0a3a8b",
desc:"The real driving simulator. Braking, racing lines, tuning, and Sport mode mastery.",tags:["Racing","Simulation","Cars","Multiplayer"],
tips:[
{level:"beginner",section:"Driving",title:"Accelerate / Brake",controls:["R2 / L2"],desc:"R2 for gas, L2 for brake. Pressure-sensitive — feather them.",why:"Full throttle through corners = spinning out. Learn to modulate."},
{level:"beginner",section:"Driving",title:"Steer",controls:["Left Stick"],desc:"Smooth steering inputs. Jerky turns cause spins.",why:"Be smooth. Gradual inputs = faster corner speeds."},
{level:"beginner",section:"Driving",title:"Shift Up / Down",controls:["Right paddle / Left paddle (or auto)"],desc:"Manual transmission is faster but harder.",why:"Auto is fine for learning. Manual gives more control at advanced levels."},
{level:"beginner",section:"Assists",title:"Racing Line",controls:["Enable in settings"],desc:"The racing line shows the optimal path and braking zones.",why:"Follow the line while learning. Green = go, red = brake."},
{level:"beginner",section:"Assists",title:"ABS / Traction Control",controls:["Enable in settings"],desc:"Anti-lock brakes and traction control prevent spins.",why:"Keep these on while learning. Turn them off for faster lap times later."},
{level:"intermediate",section:"Technique",title:"Braking Points",controls:["Brake before the corner, not in it"],desc:"Brake in a straight line before the turn, then coast through.",why:"Braking in a turn overloads the tires and causes understeer or spin."},
{level:"intermediate",section:"Technique",title:"Racing Line",controls:["Outside → Inside → Outside (apex)"],desc:"Approach from the outside, clip the inside (apex), exit to the outside.",why:"This line maximizes speed through corners. It's geometry, not just feel."},
{level:"intermediate",section:"Technique",title:"Trail Braking",controls:["Gradually release L2 as you turn in"],desc:"Start braking straight, then gradually release as you steer into the corner.",why:"Keeps weight on the front tires for better grip while turning."},
{level:"intermediate",section:"Tuning",title:"Tire Choice",controls:["Soft / Medium / Hard in race setup"],desc:"Soft = fastest but wears quickly. Hard = slow but lasts.",why:"Match tire choice to race length. Pit strategy depends on this."},
{level:"advanced",section:"Technique",title:"Throttle Control",controls:["Feather R2 on corner exit"],desc:"Gradually apply throttle as you straighten the wheel on corner exit.",why:"Full throttle too early = wheelspin. Progressive throttle = faster exit speed."},
{level:"advanced",section:"Tuning",title:"Suspension Setup",controls:["Adjust in garage"],desc:"Lower ride height, stiffer springs for faster cars. Softer for bumpy tracks.",why:"Tuning can gain 1-2 seconds per lap. Huge at competitive levels."},
{level:"advanced",section:"Sport Mode",title:"Sportsmanship Rating",controls:["Drive clean, avoid contact"],desc:"Clean driving increases your SR, matching you with better drivers.",why:"High SR = clean races. Low SR = crashers and rammers. Drive clean."},
{level:"expert",section:"Technique",title:"Tire Management",controls:["Smooth inputs + manage tire temp"],desc:"Aggressive driving overheats tires. Manage wear over a race.",why:"Saving tires for the last laps while others pit gives a massive advantage."},
{level:"expert",section:"Strategy",title:"Slipstream + Overtake",controls:["Draft behind then slingshot past"],desc:"Tuck behind the car ahead for reduced drag, then slingshot past on a straight.",why:"Slipstream gives 5-10 mph extra. Time your overtake for the braking zone."}
]},
// === INDIE ===
{id:"hades",name:"Hades / Hades II",genre:"Roguelike / Action",category:"indie",icon:"🔥",color:"#d4380d",
desc:"Die, improve, repeat. Boons, Daedalus hammers, and incredible combat flow.",tags:["Roguelike","Action","Indie","Story"],
tips:[
{level:"beginner",section:"Combat",title:"Attack",controls:["□"],desc:"Basic weapon attack.",why:"Each weapon has a unique attack pattern. Learn yours."},
{level:"beginner",section:"Combat",title:"Special",controls:["△"],desc:"Weapon's special attack.",why:"Specials have different uses — ranged, AoE, or powerful single hits."},
{level:"beginner",section:"Combat",title:"Dash",controls:["R1"],desc:"Dash with I-frames.",why:"Dash is your survival. I-frames go through projectiles and attacks."},
{level:"beginner",section:"Combat",title:"Cast",controls:["R2"],desc:"Ranged cast ability.",why:"Casts can be enhanced by boons into powerful tools. Don't forget about them."},
{level:"beginner",section:"Combat",title:"Call (God ability)",controls:["L1 + R1"],desc:"Activate your God gauge ability.",why:"Calls are ultimates. Athena's call makes you invincible. Artemis' does massive damage."},
{level:"beginner",section:"Build",title:"Boons",controls:["Choose from Olympian gods"],desc:"Gods offer boons that enhance your abilities.",why:"Boon synergies make or break a run. Ares' doom + Artemis' crit = devastating."},
{level:"intermediate",section:"Combat",title:"Dash-Strike",controls:["R1 → □ immediately"],desc:"Dash then immediately attack for a dash-strike.",why:"Faster than normal attacks and repositions you. Use constantly."},
{level:"intermediate",section:"Build",title:"Daedalus Hammers",controls:["Choose weapon upgrade"],desc:"Hammers fundamentally change your weapon's moveset.",why:"Hammers are the most impactful upgrades. Some are run-defining."},
{level:"intermediate",section:"Build",title:"Boon Synergies",controls:["Match duo/legendary requirements"],desc:"Collecting specific boon combos unlocks Duo and Legendary boons.",why:"Duo boons are incredibly powerful. Plan your god choices around them."},
{level:"intermediate",section:"Survival",title:"Death Defiance",controls:["Passive — revives you"],desc:"You have multiple Death Defiances (revives) per run.",why:"Don't panic when you die. You'll come back. Spend DD wisely on tough fights."},
{level:"advanced",section:"Combat",title:"Deflect Timing",controls:["Athena dash/attack reflects projectiles"],desc:"Athena boons deflect attacks back at enemies.",why:"Deflect trivializes projectile-heavy rooms. Reflect their own attacks back."},
{level:"advanced",section:"Build",title:"Mirror Upgrades",controls:["Spend Darkness at the Mirror"],desc:"Permanent upgrades between runs.",why:"Prioritize Death Defiance, then damage upgrades. These carry between runs."},
{level:"advanced",section:"Build",title:"Keepsakes",controls:["Equip before each biome"],desc:"Keepsakes give passive bonuses. Switch between biomes.",why:"Use god keepsakes to guarantee the boon you want at the start of each area."},
{level:"expert",section:"Build",title:"Heat System",controls:["Add modifiers for bonus rewards"],desc:"Increase Heat (difficulty modifiers) for better rewards.",why:"High heat gives Titan Blood and Diamonds. Essential for upgrading weapons."},
{level:"expert",section:"Combat",title:"Speed Clear Optimization",controls:["Kill order + room pathing"],desc:"Kill enemies in optimal order and path through rooms efficiently.",why:"Speed clears earn bonus rewards and test your mastery of every mechanic."}
]},
{id:"hollowknight",name:"Hollow Knight",genre:"Metroidvania",category:"indie",icon:"🦋",color:"#1a2a3a",
desc:"Explore the vast kingdom of Hallownest. Nail combat, charms, and precise platforming.",tags:["Metroidvania","Indie","Platformer","Exploration"],
tips:[
{level:"beginner",section:"Combat",title:"Nail Attack",controls:["□"],desc:"Swing your nail (sword) to attack.",why:"Your primary weapon. Short range — get close but dodge away after."},
{level:"beginner",section:"Combat",title:"Focus / Heal",controls:["Hold ○"],desc:"Hold Circle to spend Soul (from hitting enemies) to heal.",why:"Healing takes time and you're vulnerable. Only heal in safe windows."},
{level:"beginner",section:"Movement",title:"Jump",controls:["X"],desc:"Press X to jump.",why:"Jump and attack enemies below you for a pogo effect (bouncing off them)."},
{level:"beginner",section:"Combat",title:"Dash",controls:["R1 (after Mothwing Cloak)"],desc:"Dash through attacks with I-frames.",why:"Essential for dodging boss attacks once unlocked."},
{level:"beginner",section:"Combat",title:"Spells",controls:["△ (down) + ○ for different spells"],desc:"Vengeful Spirit (fireball), Desolate Dive (ground slam), etc.",why:"Spells use Soul but deal massive damage. Don't hoard Soul — spend it."},
{level:"beginner",section:"Exploration",title:"Map",controls:["Touchpad → map"],desc:"Open your map. Buy maps from Cornifer in each area.",why:"Without a map, you're lost. Always find Cornifer first in new areas."},
{level:"intermediate",section:"Build",title:"Charm Loadout",controls:["Equip charms at benches"],desc:"Charms modify your abilities. Limited notch slots.",why:"Charm combos define your playstyle. Quick Slash + Mark of Pride = extended fast attacks."},
{level:"intermediate",section:"Combat",title:"Pogo",controls:["Down + □ on enemy below"],desc:"Attack downward while airborne to bounce off enemies/spikes.",why:"Pogo lets you cross spike pits and stay in the air indefinitely."},
{level:"intermediate",section:"Combat",title:"Shade Cloak",controls:["Dash through enemies/projectiles"],desc:"Upgraded dash phases through attacks and enemies.",why:"Complete invincibility during dash. Game-changing upgrade."},
{level:"intermediate",section:"Exploration",title:"Dream Nail",controls:["Hold △ on NPCs/enemies"],desc:"Read thoughts and access dream boss fights.",why:"Dream bosses give Essence for upgrades. Dream Nail is essential for progression."},
{level:"advanced",section:"Combat",title:"Nail Arts",controls:["Hold □ → release"],desc:"Charge your nail for powerful arts: Great Slash, Dash Slash, Cyclone Slash.",why:"Nail Arts deal 2-3x normal damage. Great Slash is safe burst damage."},
{level:"advanced",section:"Build",title:"Spell Build",controls:["Spell Twister + Shaman Stone + Soul Eater"],desc:"Reduce spell cost + increase spell damage + gain more soul.",why:"Spell builds delete bosses. Shade Soul does massive damage with Shaman Stone."},
{level:"advanced",section:"Build",title:"Nail Build",controls:["Quick Slash + Mark of Pride + Unbreakable Strength"],desc:"Attack faster, from farther, with more damage.",why:"The aggressive build. Constant attacks that generate Soul for healing."},
{level:"expert",section:"Challenge",title:"Pantheon of Hallownest",controls:["Beat all bosses in a row"],desc:"Fight every boss in sequence without dying.",why:"The ultimate Hollow Knight challenge. Requires mastery of every boss pattern."},
{level:"expert",section:"Combat",title:"Abyss Shriek Spam",controls:["Jump → Abyss Shriek → heal → repeat"],desc:"Abyss Shriek deals massive upward damage. Use against large bosses.",why:"With Shaman Stone, Abyss Shriek melts bosses faster than any other strategy."}
]},
// === MISC ===
{id:"minecraft",name:"Minecraft",genre:"Sandbox / Survival",category:"misc",icon:"⛏️",color:"#5c8a2a",
desc:"Mine, craft, build, survive. The ultimate creative and survival sandbox.",tags:["Sandbox","Survival","Creative","Multiplayer"],
tips:[
{level:"beginner",section:"Basics",title:"Mine / Attack",controls:["R2 (hold to mine / tap to attack)"],desc:"Hold R2 on blocks to mine them. Tap to attack mobs.",why:"Mining is the foundation of everything. Punch a tree to start."},
{level:"beginner",section:"Basics",title:"Place Block",controls:["L2"],desc:"Place the block in your hand.",why:"Building shelters, bridges, and structures is core gameplay."},
{level:"beginner",section:"Basics",title:"Jump",controls:["X"],desc:"Jump to climb blocks and navigate terrain.",why:"Sprint + jump is the fastest movement on land."},
{level:"beginner",section:"Basics",title:"Open Inventory",controls:["△"],desc:"Open crafting inventory.",why:"Craft tools, weapons, armor, and more. Everything starts here."},
{level:"beginner",section:"Basics",title:"Sprint",controls:["L3 (click)"],desc:"Click left stick to sprint.",why:"Sprint + jump for fast travel. Uses hunger faster."},
{level:"beginner",section:"Survival",title:"Craft Basics",controls:["Wood → Planks → Crafting Table → Tools"],desc:"First craft: wooden pickaxe, then stone, then iron.",why:"Better tools mine faster and last longer. Upgrade ASAP."},
{level:"intermediate",section:"Survival",title:"First Night",controls:["Build shelter before dark"],desc:"Mine and build a basic shelter before nightfall (10 min).",why:"Monsters spawn at night. Without shelter, you die."},
{level:"intermediate",section:"Mining",title:"Branch Mining",controls:["Dig at Y=11 in 2-block tunnels"],desc:"Create parallel tunnels at Y=-59 to Y=16 for diamonds.",why:"Diamonds spawn at these depths. Branch mining is the most efficient method."},
{level:"intermediate",section:"Survival",title:"Farming",controls:["Hoe → till dirt → plant seeds near water"],desc:"Create a farm for renewable food.",why:"Food = healing and sprint. A farm ensures you never starve."},
{level:"intermediate",section:"Combat",title:"Shield",controls:["L2 (with shield equipped)"],desc:"Block attacks with your shield.",why:"Blocks 100% of melee and arrow damage. Essential for survival."},
{level:"advanced",section:"Redstone",title:"Redstone Basics",controls:["Place redstone dust + lever/button"],desc:"Create circuits for doors, traps, and automated farms.",why:"Redstone automates everything. Auto-farms produce infinite resources."},
{level:"advanced",section:"Nether",title:"Nether Portal",controls:["Obsidian frame + flint & steel"],desc:"Build a 4x5 obsidian frame and light it to enter the Nether.",why:"The Nether has essential resources: Blaze Rods, Nether Wart for potions."},
{level:"advanced",section:"Enchanting",title:"Enchant Items",controls:["Enchanting table + lapis + bookshelves"],desc:"Surround an enchanting table with 15 bookshelves for max enchants.",why:"Enchanted diamond/netherite gear is dramatically more powerful."},
{level:"expert",section:"Endgame",title:"Ender Dragon",controls:["Ender Eyes → Stronghold → End Portal → Fight"],desc:"Find the stronghold, activate the End Portal, and defeat the Ender Dragon.",why:"The main objective of survival mode. Prepare with enchanted gear and potions."},
{level:"expert",section:"Building",title:"Efficient Base Design",controls:["Central storage + farms + enchant room"],desc:"Design your base with easy access to storage, farms, and utilities.",why:"Efficiency saves hours. A well-designed base makes every activity faster."}
]},
{id:"rocketleague",name:"Rocket League",genre:"Sports / Vehicular",category:"misc",icon:"🚀",color:"#0060a8",
desc:"Rocket-powered car soccer. Aerials, dribbles, rotations, and mechanical skill ceiling.",tags:["Sports","Competitive","Multiplayer","Cars"],
tips:[
{level:"beginner",section:"Basics",title:"Accelerate / Brake",controls:["R2 / L2"],desc:"R2 to drive forward, L2 to brake/reverse.",why:"Speed control is everything. Don't boost constantly."},
{level:"beginner",section:"Basics",title:"Jump",controls:["X"],desc:"Press X to jump. Tap twice for a double jump.",why:"Jumping lets you hit aerial balls and dodge."},
{level:"beginner",section:"Basics",title:"Boost",controls:["○"],desc:"Hold Circle for rocket boost.",why:"Boost pads refill your meter. Pick them up constantly. Full pads give 100."},
{level:"beginner",section:"Basics",title:"Dodge / Flip",controls:["X + X + direction"],desc:"Double jump with a direction to flip/dodge in that direction.",why:"Front flip = speed boost. Side flip = dodging. Back flip = saves."},
{level:"beginner",section:"Basics",title:"Ball Cam",controls:["△"],desc:"Toggle ball cam to always track the ball.",why:"Keep ball cam on 90% of the time. Toggle off when grabbing boost."},
{level:"beginner",section:"Basics",title:"Powerslide",controls:["□"],desc:"Hold Square to powerslide for sharp turns.",why:"Powerslide lets you turn without losing all your speed."},
{level:"intermediate",section:"Technique",title:"Aerial",controls:["Jump → boost → fly toward ball"],desc:"Jump, then hold boost while tilting up to fly toward the ball.",why:"Aerials are when the game opens up. Practice in training until comfortable."},
{level:"intermediate",section:"Technique",title:"Fast Aerial",controls:["Jump → tilt back + boost → jump again"],desc:"Jump, immediately tilt back and boost, then double jump for faster altitude.",why:"Reaches the ball much faster than a normal aerial. The standard at higher ranks."},
{level:"intermediate",section:"Rotation",title:"Rotation (3v3)",controls:["Take turns: attack → rotate back → defense"],desc:"After attacking, rotate to the back and let your teammate go next.",why:"Ball chasing with 3 people on offense = easy goals for the other team. ROTATE."},
{level:"intermediate",section:"Technique",title:"Half Flip",controls:["Backflip → cancel with stick forward → air roll"],desc:"Backflip, cancel mid-flip by pushing stick forward, air roll to land.",why:"Turns you around instantly when facing the wrong way. Essential recovery."},
{level:"advanced",section:"Technique",title:"Air Dribble",controls:["Pop ball off wall → follow with boost"],desc:"Hit the ball off the wall and follow it in the air, touching it gently to maintain control.",why:"Incredibly hard to defend against. The ball is unpredictable."},
{level:"advanced",section:"Technique",title:"Wave Dash",controls:["Jump → dodge into ground diagonally"],desc:"Jump, then dodge into the ground at an angle for a speed boost without using boost.",why:"Free speed without spending boost. Essential for boost management."},
{level:"advanced",section:"Technique",title:"Dribble + Flick",controls:["Ball on car roof → jump + flip"],desc:"Balance ball on car, then jump and flip to flick it over defenders.",why:"Flicks are nearly unsaveable. The opponent must challenge before you flick."},
{level:"expert",section:"Technique",title:"Ceiling Shot",controls:["Drive onto ceiling → fall off → unlimited dodge"],desc:"Drive onto ceiling, fall off (don't jump) to keep your dodge indefinitely.",why:"You can dodge into the ball at any time during the fall. Extremely hard to read."},
{level:"expert",section:"Technique",title:"Flip Reset",controls:["Touch ball with all 4 wheels in air"],desc:"Touch the ball with all 4 wheels to reset your dodge.",why:"Infinite flip resets mean infinite aerial options. The highest mechanical skill."},
{level:"expert",section:"Strategy",title:"Boost Starving",controls:["Grab opponent's corner boost pads"],desc:"Drive through the enemy's boost pad corners to deny them boost.",why:"An opponent without boost can't challenge aerials or recover quickly."}
]},
{id:"genshin",name:"Genshin Impact",genre:"Action RPG / Gacha",category:"misc",icon:"🌟",color:"#4a8bc2",
desc:"Explore Teyvat with elemental reactions, team combos, and gacha characters.",tags:["Action","RPG","Gacha","Open World"],
tips:[
{level:"beginner",section:"Combat",title:"Normal Attack",controls:["□"],desc:"Basic attack combo.",why:"Each character has a unique combo string. Some are fast, some are heavy."},
{level:"beginner",section:"Combat",title:"Elemental Skill",controls:["R1"],desc:"Character's elemental ability (tap or hold).",why:"Skills define each character. Short cooldowns for regular use."},
{level:"beginner",section:"Combat",title:"Elemental Burst",controls:["R2"],desc:"Powerful ultimate when energy is full.",why:"Bursts deal massive damage and trigger reactions. Build energy with skills."},
{level:"beginner",section:"Combat",title:"Dodge",controls:["R1 (while sprinting) or ○"],desc:"Dodge with I-frames.",why:"Dodge through attacks. Essential against bosses."},
{level:"beginner",section:"Team",title:"Switch Character",controls:["D-Pad"],desc:"Switch between 4 party members instantly.",why:"Switching characters is CORE. Apply elements with one, react with another."},
{level:"beginner",section:"Exploration",title:"Glide",controls:["X in air"],desc:"Deploy wind glider for aerial traversal.",why:"Stamina-dependent. Upgrade stamina with Statues of the Seven."},
{level:"intermediate",section:"Combat",title:"Elemental Reactions",controls:["Apply element A → switch → apply element B"],desc:"Vaporize (Hydro+Pyro), Melt (Cryo+Pyro), Freeze (Hydro+Cryo), etc.",why:"Reactions are the core damage system. Vaporize doubles damage. Melt doubles damage."},
{level:"intermediate",section:"Team",title:"Team Composition",controls:["1 DPS + 1 Sub-DPS + 1 Support + 1 Healer"],desc:"Build teams around one main damage dealer with supports.",why:"Supports buff the DPS. Bennett + Xiangling + Xingqiu = one of the strongest F2P teams."},
{level:"intermediate",section:"Build",title:"Artifact Sets",controls:["Equip matching set pieces"],desc:"4-piece sets give powerful bonuses. 2+2 splits also work.",why:"Artifacts are endgame progression. Farm domains at AR45+ for guaranteed 5-stars."},
{level:"intermediate",section:"Build",title:"Weapon Leveling",controls:["Level up weapons to max"],desc:"Always max your weapon level. It's the biggest single stat increase.",why:"Weapons are often more impactful than character level. Prioritize weapon."},
{level:"advanced",section:"Combat",title:"Animation Cancel",controls:["Dash/jump after attack to cancel recovery"],desc:"Cancel attack recovery animations with a dash or jump.",why:"Increases DPS by removing dead time between attacks."},
{level:"advanced",section:"Build",title:"Crit Ratio",controls:["Aim for 1:2 Crit Rate to Crit DMG"],desc:"60% CR / 120% CD or 70/140 etc.",why:"The universal DPS formula. Crit stats multiply your total damage."},
{level:"advanced",section:"Combat",title:"Energy Funneling",controls:["Use skill → switch to burst character"],desc:"Generate energy particles with one character, switch to another to catch them.",why:"Characters catch more energy from their own element. Funnel energy to your burst DPS."},
{level:"expert",section:"Combat",title:"Snapshot Buffs",controls:["Apply buffs → deploy abilities that snapshot"],desc:"Some abilities snapshot their stats at cast time. Apply all buffs first.",why:"Xiangling's Pyronado snapshots. Bennett buff → Xiangling burst = boosted for entire duration."},
{level:"expert",section:"Abyss",title:"Spiral Abyss Clears",controls:["Build 2 teams for 2 halves"],desc:"Floor 12 requires two fully built teams with good elemental coverage.",why:"Spiral Abyss is the endgame challenge. Primogem rewards reset monthly."}
]},
{id:"fallguys",name:"Fall Guys",genre:"Party / Battle Royale",category:"misc",icon:"🫘",color:"#ffcc00",
desc:"Stumble and tumble to victory. Party game with obstacle courses and team rounds.",tags:["Party","Battle Royale","Multiplayer","Fun"],
tips:[
{level:"beginner",section:"Movement",title:"Run",controls:["Left Stick"],desc:"Run with left stick.",why:"You're always moving. Don't slow down unless you need precision."},
{level:"beginner",section:"Movement",title:"Jump",controls:["X"],desc:"Jump over obstacles and gaps.",why:"Timing is everything. Early jumps clear more obstacles."},
{level:"beginner",section:"Movement",title:"Dive",controls:["□"],desc:"Dive forward for extra distance.",why:"Jump + Dive covers the most ground. Use at the end of jumps."},
{level:"beginner",section:"Interaction",title:"Grab",controls:["R2"],desc:"Grab onto objects and other players.",why:"Grab ledges to survive falls. Grab enemies to sabotage them."},
{level:"intermediate",section:"Strategy",title:"Jump + Dive",controls:["X then □ mid-air"],desc:"Jump then immediately dive for maximum forward distance.",why:"The key combo for clearing gaps. Master it — you'll use it every round."},
{level:"intermediate",section:"Strategy",title:"Dive Recovery",controls:["Dive → stand up faster by not moving"],desc:"After a dive, don't move the stick to get up slightly faster.",why:"Recovery speed wins close eliminations."},
{level:"intermediate",section:"Race",title:"Inside Track",controls:["Take the shortest path"],desc:"On circular courses, always take the inner path.",why:"Inside = shorter distance = faster time. Simple geometry."},
{level:"intermediate",section:"Team",title:"Team Round Strategy",controls:["Defend your team's objective"],desc:"In team rounds, defense is as important as offense.",why:"Guard your team's eggs/tail/zone. One good defender saves the team."},
{level:"advanced",section:"Race",title:"Shortcut Knowledge",controls:["Learn map shortcuts"],desc:"Many maps have hidden shortcuts and optimal paths.",why:"Knowing a 2-second shortcut means guaranteed qualification."},
{level:"advanced",section:"Final",title:"Final Round Tips",controls:["Stay center → react to others"],desc:"In finals like Hex-A-Gone, play slowly and cut off opponents' paths.",why:"Slow play preserves tiles. Fast play wastes them. Patience wins finals."},
{level:"expert",section:"Final",title:"Hex-A-Gone Slow Walk",controls:["Walk, don't run on tiles"],desc:"Walking only removes one tile. Running removes more.",why:"Maximum tile preservation. Jump only when necessary to move between sections."}
]}
]);
