registerGames([
{
  id:"hogwarts",name:"Hogwarts Legacy",genre:"Action RPG",category:"rpg",icon:"🧙",color:"#5c2d91",
  desc:"Explore the wizarding world. Spell combos, broom flight, Room of Requirement, and magical combat.",
  tags:["RPG","Open World","Magic","Single Player"],
  tips:[
    {level:"beginner",section:"Combat",title:"Basic Cast",controls:["R2"],desc:"Press R2 to fire your basic cast at targeted enemies.",why:"Free damage between cooldowns. Always be casting."},
    {level:"beginner",section:"Combat",title:"Protego (Shield)",controls:["△"],desc:"Press Triangle when indicator appears to block attacks.",why:"Perfect timing stuns the attacker for a counter."},
    {level:"beginner",section:"Combat",title:"Dodge Roll",controls:["○"],desc:"Press Circle to dodge. Red attacks can't be blocked.",why:"Some attacks bypass Protego. Dodge is your only option for red indicators."},
    {level:"beginner",section:"Combat",title:"Lock On",controls:["R3"],desc:"Click right stick to lock on.",why:"Keeps spells focused. Essential against multiple enemies."},
    {level:"beginner",section:"Exploration",title:"Revelio",controls:["Left D-Pad"],desc:"Reveal hidden items, collectibles, and interactables.",why:"Use constantly. You'll miss tons of loot without it."},
    {level:"beginner",section:"Combat",title:"Spell Sets",controls:["R1 + face buttons / R1 tap to cycle"],desc:"4 spell sets × 4 spells = 16 equipped spells.",why:"Organize by role: damage set, control set, utility set."},
    {level:"intermediate",section:"Combat",title:"Perfect Protego Counter",controls:["△ (frame-perfect)"],desc:"Block at the exact moment for a perfect Protego — stuns and reflects projectiles.",why:"Reflected projectiles deal massive damage."},
    {level:"intermediate",section:"Combat",title:"Levioso → Accio → Descendo Combo",controls:["Levioso → Accio → Descendo"],desc:"Float enemy, pull them close, slam them down.",why:"Core combo. Enormous damage on most enemies."},
    {level:"intermediate",section:"Combat",title:"Ancient Magic Finisher",controls:["L1 + R1 when full"],desc:"Devastating finisher when Ancient Magic meter is full.",why:"One-shots most regulars. Build meter with varied spells."},
    {level:"intermediate",section:"Stealth",title:"Disillusionment → Petrificus",controls:["Cast Disillusionment → sneak → Petrificus Totalus"],desc:"Go invisible, sneak behind enemy, instant kill.",why:"Clears camps without combat. The most efficient approach."},
    {level:"intermediate",section:"Traversal",title:"Broom",controls:["X mount / R2 boost / L2 brake"],desc:"Mount, boost, and brake on your broom.",why:"Fastest travel method. Boost through challenges for rewards."},
    {level:"intermediate",section:"Combat",title:"Wingardium Leviosa Objects",controls:["Cast → throw at enemies"],desc:"Lift environmental objects and throw them at enemies.",why:"Barrels and crates deal huge damage and break shields. Free damage."},
    {level:"advanced",section:"Combat",title:"Shield Breaking",controls:["Match spell color to shield"],desc:"Yellow shields = Control spells (Levioso, Glacius). Purple = Force (Accio, Depulso). Red = Damage (Incendio, Confringo).",why:"You MUST match colors. Keep one of each type equipped always."},
    {level:"advanced",section:"Build",title:"Key Talents",controls:["Talent menu"],desc:"Protego Absorption (heal on block), Spell Knowledge III (more sets), Enduring Curse (Crucio spreads).",why:"Talent tree makes or breaks your build. Prioritize Spell Knowledge early."},
    {level:"advanced",section:"Combat",title:"Transformation + Cliff",controls:["Transformation near edges"],desc:"Cast Transformation near cliff edges — enemies fall off for instant kills.",why:"Works on anything transformable. Trivializes encounters near ledges."},
    {level:"advanced",section:"Resources",title:"Room of Requirement",controls:["Conjure stations + beast pens"],desc:"Fill Room with potion stations and beast breeding pens.",why:"Passive resource generation. Maxed potions = massive combat advantage."},
    {level:"expert",section:"Combat",title:"Crucio Curse Chain",controls:["Crucio → basic casts spread curse"],desc:"Cast Crucio on one, then basic cast others to spread the curse.",why:"Every cursed enemy takes 30% more damage. Room-wide debuff."},
    {level:"expert",section:"Combat",title:"Animation Canceling",controls:["Dodge → spell immediately"],desc:"Dodge roll and immediately cast to skip recovery animation.",why:"Cast, dodge, cast — never stop dealing damage. Massive DPS increase."},
    {level:"expert",section:"Combat",title:"Invisibility + Petrificus Chain",controls:["Invisibility Potion → spam Petrificus"],desc:"Drink potion, chain instant kills before detection.",why:"Clears entire camps. Potion lasts for 8-10 kills if fast."}
  ]
},
{
  id:"eldenring",name:"Elden Ring",genre:"Action RPG / Souls-like",category:"rpg",icon:"⚔️",color:"#8b7500",
  desc:"Conquer the Lands Between. Melee, magic, and mounted combat across a vast open world.",
  tags:["RPG","Open World","Souls-like","FromSoftware"],
  tips:[
    {level:"beginner",section:"Combat",title:"Light Attack",controls:["R1"],desc:"Quick, stamina-efficient attack.",why:"Safest damage option against new enemies."},
    {level:"beginner",section:"Combat",title:"Heavy Attack",controls:["R2 (hold to charge)"],desc:"Slower but more damage and poise break.",why:"Charged heavies break poise fast. Use during enemy recovery."},
    {level:"beginner",section:"Combat",title:"Dodge Roll",controls:["○"],desc:"Roll with I-frames at the START.",why:"Roll INTO attacks. Counterintuitive but critical. I-frames are at roll start."},
    {level:"beginner",section:"Combat",title:"Lock On",controls:["R3"],desc:"Lock onto enemies.",why:"Unlock for large enemies where camera struggles."},
    {level:"beginner",section:"Combat",title:"Heal (Flask)",controls:["□"],desc:"Use Flask of Crimson Tears.",why:"Long animation. Only heal during safe windows."},
    {level:"beginner",section:"Combat",title:"Guard",controls:["L1"],desc:"Block with shield.",why:"Costs stamina. Stamina break = stagger."},
    {level:"beginner",section:"Combat",title:"Use Item",controls:["□"],desc:"Use whatever item is in your quick slot.",why:"Swap items with D-Pad down. Keep flasks and summons accessible."},
    {level:"intermediate",section:"Combat",title:"Guard Counter",controls:["Block → R2"],desc:"Block an attack then immediately R2.",why:"Massive poise damage. Two guard counters often break enemy stance."},
    {level:"intermediate",section:"Combat",title:"Jump Attack",controls:["X → R1 or R2"],desc:"Jump then attack for bonus poise damage.",why:"Best way to break poise. Pair with heavy weapons."},
    {level:"intermediate",section:"Combat",title:"Two-Hand Weapon",controls:["△ + R1 (right) or △ + L1 (left)"],desc:"Two-hand for 1.5x strength and new moveset.",why:"More damage, different attacks, no shield."},
    {level:"intermediate",section:"Summons",title:"Spirit Ashes",controls:["Use near summoning pool"],desc:"Summon AI allies — Mimic Tear, Black Knife Tiche are best.",why:"They draw aggro and deal real damage. Makes tough fights manageable."},
    {level:"intermediate",section:"Mount",title:"Torrent",controls:["Spectral Steed Whistle"],desc:"Summon your horse. R1/R2 for mounted attacks.",why:"Hit and run on horseback makes open-world bosses much easier."},
    {level:"intermediate",section:"Combat",title:"Ash of War",controls:["L2 (with weapon skill)"],desc:"Use your weapon's equipped Ash of War ability.",why:"Some Ashes of War are incredibly powerful. Experiment with different ones."},
    {level:"advanced",section:"Build",title:"Ash of War Swapping",controls:["Grace → Ashes of War menu"],desc:"Change weapon skill and affinity at any Site of Grace.",why:"Match affinity to build: Keen (Dex), Heavy (Str), Quality (both), Sacred (Faith)."},
    {level:"advanced",section:"Combat",title:"Stance Breaking",controls:["Charged R2 + Jump R2 combos"],desc:"Mix charged heavies and jump attacks to break boss stance.",why:"Criticals deal 3-5x normal damage. Most efficient boss-killing method."},
    {level:"advanced",section:"Build",title:"Bleed Buildup",controls:["Blood loss weapons"],desc:"Bleed weapons proc hemorrhage for % max HP damage.",why:"Bleed destroys bosses. Dual curved swords are the meta."},
    {level:"advanced",section:"Build",title:"Buff Stacking",controls:["Flask of Wondrous Physick + greases + spells"],desc:"Stack multiple damage buffs before boss fights.",why:"Buffs multiply. Physick + Golden Vow + weapon grease = 2-3x damage."},
    {level:"expert",section:"Combat",title:"Animation Cancel",controls:["Use item → roll to cancel"],desc:"Use consumable then roll to cancel end animation.",why:"Stack buffs faster. Multiple buffs without wasting time."},
    {level:"expert",section:"Combat",title:"Status Stacking",controls:["Frostbite → fire reset → Bleed → repeat"],desc:"Apply Frostbite, reset with fire, apply Bleed, repeat cycle.",why:"Frostbite + Bleed = highest DPS combo. Both proc for % HP."},
    {level:"expert",section:"PvP",title:"Crouch Poke",controls:["Crouch → R1 with thrusting sword"],desc:"Fastest attack in the game. Nearly unpunishable.",why:"The meta PvP move for duels. Almost impossible to react to."}
  ]
},
{
  id:"ff7r",name:"Final Fantasy VII Rebirth",genre:"Action RPG",category:"rpg",icon:"🌟",color:"#1a1a8a",
  desc:"Cloud and friends across the open world. ATB combat, Synergy abilities, and Materia mastery.",
  tags:["RPG","Action","Story","Open World"],
  tips:[
    {level:"beginner",section:"Combat",title:"Basic Attack",controls:["□"],desc:"Press Square for melee combo attacks.",why:"Basic attacks build your ATB gauge. The faster you attack, the faster you get abilities."},
    {level:"beginner",section:"Combat",title:"Block",controls:["R1"],desc:"Hold R1 to block and reduce damage.",why:"Blocking is essential. Some enemies hit hard enough to one-shot without blocking."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["○"],desc:"Press Circle to dodge roll.",why:"Dodge unblockable attacks. Some boss attacks have huge AoE — dodge far."},
    {level:"beginner",section:"Combat",title:"ATB Abilities",controls:["X → select ability"],desc:"When ATB charges fill, press X to open the command menu.",why:"Abilities are your real damage. Basic attacks just build the gauge."},
    {level:"beginner",section:"Combat",title:"Switch Character",controls:["D-Pad left/right"],desc:"Switch between party members.",why:"AI doesn't use ATB well. Switch to characters to spend their ATB manually."},
    {level:"beginner",section:"Combat",title:"Magic",controls:["Command menu → Magic"],desc:"Cast equipped Materia spells using ATB.",why:"Exploit elemental weaknesses for massive damage and stagger."},
    {level:"intermediate",section:"Combat",title:"Stagger System",controls:["Fill stagger bar → 160-300% damage"],desc:"Attacking enemies fills a stagger bar. Once full, they're stunned and take bonus damage.",why:"Damage is MULTIPLIED during stagger. Save your biggest abilities for this window."},
    {level:"intermediate",section:"Combat",title:"Stagger Bonus",controls:["Use specific abilities during stagger"],desc:"Tifa's Rise and Fall and Unbridled Strength increase the stagger damage multiplier.",why:"Going from 160% to 300% multiplier doubles your stagger damage output."},
    {level:"intermediate",section:"Combat",title:"Synergy Abilities",controls:["R1 + face button"],desc:"Two characters team up for a powerful Synergy ability.",why:"Synergy abilities cost no ATB and can be devastatingly powerful."},
    {level:"intermediate",section:"Combat",title:"Assess Materia",controls:["Command → Assess"],desc:"Scan enemies to learn weaknesses and stagger conditions.",why:"Always Assess new enemies. Knowing weakness = killing 3x faster."},
    {level:"intermediate",section:"Build",title:"Materia Combos",controls:["Link Materia slots"],desc:"Pair Materia in linked slots for combos — Elemental + Fire on weapon = fire damage on attacks.",why:"Linked Materia creates powerful combinations. Elemental + element is essential."},
    {level:"intermediate",section:"Build",title:"Weapon Upgrades",controls:["Menu → Weapons"],desc:"Spend SP on weapon upgrades for stat boosts and abilities.",why:"Each weapon has unique abilities. Upgrade to unlock them, then swap weapons freely."},
    {level:"advanced",section:"Combat",title:"ATB Ward",controls:["Aerith ability"],desc:"Aerith places a ward that doubles ATB ability casts.",why:"Step into the ward, cast a spell, and it casts TWICE. Double damage for one ATB bar."},
    {level:"advanced",section:"Combat",title:"Limit Break Timing",controls:["Save Limit for stagger"],desc:"Don't use Limit Breaks randomly. Save for stagger windows.",why:"Limit Break during 300% stagger = the highest damage possible."},
    {level:"advanced",section:"Combat",title:"Precision Block",controls:["R1 at exact moment of impact"],desc:"Perfect timing block fills ATB faster and reduces more damage.",why:"Speeds up your ATB economy significantly against aggressive enemies."},
    {level:"expert",section:"Combat",title:"Stagger Chain Optimization",controls:["Pressure → Stagger → Tifa boost → Limit → Abilities"],desc:"The optimal chain: Pressure enemy, stagger, boost multiplier with Tifa, then unload everything.",why:"This is how speedrunners and hard-mode players kill bosses in one stagger cycle."},
    {level:"expert",section:"Build",title:"Gotterdammerung Accessory",controls:["Equip for Limit Break on battle start"],desc:"Starts every battle with a full Limit Break gauge.",why:"Opening with a Limit Break trivializes most encounters."},
    {level:"expert",section:"Combat",title:"Switch Canceling",controls:["Switch character mid-combo to cancel recovery"],desc:"Switch characters to cancel the recovery animation of abilities.",why:"Increases DPS by eliminating downtime between ability casts across your party."}
  ]
},
{
  id:"ff16",name:"Final Fantasy XVI",genre:"Action RPG",category:"rpg",icon:"🔥",color:"#4a1a8a",
  desc:"Eikon powers and stylish combat as Clive Rosfield in Valisthea.",
  tags:["Action","RPG","Story","Fantasy"],
  tips:[
    {level:"beginner",section:"Combat",title:"Melee Combo",controls:["□ chain"],desc:"Press Square repeatedly for sword combos.",why:"Your basic damage. Learn the rhythm for max hits."},
    {level:"beginner",section:"Combat",title:"Magic Burst",controls:["△"],desc:"Triangle for ranged magic.",why:"Use between melee combos. No cooldown, no cost."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["R1"],desc:"R1 to dodge. Precision Dodge (last moment) slows time.",why:"Precision Dodge gives a HUGE free damage window."},
    {level:"beginner",section:"Combat",title:"Eikon Abilities",controls:["L2 + face buttons"],desc:"Hold L2 and press face buttons for Eikon powers.",why:"Your most powerful attacks. Rotate between cooldowns."},
    {level:"intermediate",section:"Combat",title:"Stagger System",controls:["Deplete stagger bar"],desc:"All damage multiplied during stagger. Save your biggest abilities.",why:"70% of boss damage comes during stagger windows."},
    {level:"intermediate",section:"Combat",title:"Lunge",controls:["Hold □ → release"],desc:"Hold Square to charge, release to lunge to distant enemies.",why:"Closes distance instantly. Keeps your combo going."},
    {level:"intermediate",section:"Combat",title:"Eikon Swap",controls:["L2 + L1/R1"],desc:"Swap between three Eikon sets while holding L2.",why:"Always have abilities ready. Swap when one set is on cooldown."},
    {level:"intermediate",section:"Eikons",title:"Phoenix Shift",controls:["L2 + ○ (Phoenix)"],desc:"Teleport to the target enemy instantly.",why:"Closes any distance and starts a combo. Incredible gap closer."},
    {level:"advanced",section:"Eikons",title:"Zantetsuken (Odin)",controls:["Build gauge → L2 + □+△"],desc:"Build the Zantetsuken gauge, then unleash.",why:"Highest single-hit damage. Full gauge can one-shot mid-bosses."},
    {level:"advanced",section:"Combat",title:"Aerial Combo",controls:["Launch → □ chain in air"],desc:"Use Phoenix Shift or Gouge to launch, then air combo.",why:"Airborne enemies can't attack. Free damage with zero risk."},
    {level:"advanced",section:"Eikons",title:"Satellite (Shiva)",controls:["L2 + △ (Shiva)"],desc:"Place ice crystals that shoot at enemies automatically.",why:"Passive damage while you combo. Stacks with everything."},
    {level:"expert",section:"Combat",title:"Stagger Burst Window",controls:["All abilities during stagger"],desc:"Stagger → unload every ability → swap Eikon sets → unload again.",why:"Top players dump 70% of boss HP in one stagger window."},
    {level:"expert",section:"Combat",title:"Precision Counter → Full Combo",controls:["Precision Dodge → □ → △ → all abilities"],desc:"Dodge, counter, combo, swap, ability, swap, ability.",why:"The perfect flow state. Non-stop DPS with zero downtime."}
  ]
},
{
  id:"persona5",name:"Persona 5 Royal",genre:"JRPG / Social Sim",category:"rpg",icon:"🎭",color:"#e60012",
  desc:"Steal hearts, manage time. Turn-based combat, confidants, and the Metaverse.",
  tags:["JRPG","Story","Turn-Based","Social Sim"],
  tips:[
    {level:"beginner",section:"Combat",title:"Exploit Weaknesses",controls:["Analyze → hit weakness"],desc:"Use Analyze, then hit elemental weakness for One More actions.",why:"Hitting weaknesses = extra turns. The core of combat."},
    {level:"beginner",section:"Combat",title:"All-Out Attack",controls:["Knock all down → prompt"],desc:"When all enemies are downed, trigger All-Out Attack.",why:"Usually one-shots regular encounters."},
    {level:"beginner",section:"Combat",title:"Guard",controls:["Select Guard"],desc:"Halve incoming damage for one turn.",why:"Guard when you know a powerful attack is coming."},
    {level:"beginner",section:"Combat",title:"Persona Switch",controls:["Select in battle menu"],desc:"Joker can switch Personas mid-battle.",why:"Different Personas have different elements. Switch to exploit weaknesses."},
    {level:"intermediate",section:"Combat",title:"Baton Pass",controls:["After One More → pass to ally"],desc:"Pass turn to an ally to boost their attack power.",why:"Each Baton Pass increases damage. Chain through 3 allies for huge final attack."},
    {level:"intermediate",section:"Life Sim",title:"Time Management",controls:["Plan daily activities"],desc:"Every day has limited time slots. Prioritize wisely.",why:"Can't max everything first playthrough without a guide. Focus on what you want most."},
    {level:"intermediate",section:"Build",title:"Persona Fusion",controls:["Velvet Room → Fuse"],desc:"Fuse Personas to create stronger ones that inherit skills.",why:"Fused Personas are ALWAYS stronger than found ones. Fuse often."},
    {level:"intermediate",section:"Combat",title:"Gun Attacks",controls:["Select Gun in battle"],desc:"Ranged attacks that use ammo. Some enemies are weak to gun.",why:"Ammo refreshes per battle in Royal. Use guns freely."},
    {level:"intermediate",section:"Life Sim",title:"Social Stats",controls:["Various activities"],desc:"Build Knowledge, Guts, Proficiency, Kindness, Charm through activities.",why:"Many confidants require specific social stat levels to advance."},
    {level:"advanced",section:"Life Sim",title:"Priority: Temperance & Fortune",controls:["Kawakami & Chihaya"],desc:"Kawakami gives you extra night activities. Chihaya boosts confidant points.",why:"These give you MORE TIME — the most valuable resource. Max them early."},
    {level:"advanced",section:"Combat",title:"Technical Damage",controls:["Status ailment → specific element"],desc:"Apply ailment then hit with corresponding element.",why:"Technicals knock down enemies. Combined with Baton Pass, this is the advanced loop."},
    {level:"advanced",section:"Build",title:"Skill Inheritance",controls:["Select skills during fusion"],desc:"Choose which skills carry over during Persona fusion.",why:"Pass the best abilities forward to create Personas with perfect skill sets."},
    {level:"expert",section:"Build",title:"Fusion Alarm Abuse",controls:["Trigger alarm → fuse"],desc:"Fusion Alarms boost results. Create overpowered Personas.",why:"Alarm fusions create Personas 2-3x stronger than normal."},
    {level:"expert",section:"Build",title:"Itemize Personas",controls:["Velvet Room → Electric Chair"],desc:"Turn Personas into powerful equipment and skill cards.",why:"Best weapons and accessories come from itemization, not shops."},
    {level:"expert",section:"Combat",title:"Baton Pass Chain 4x",controls:["Pass through all 4 party members"],desc:"Chain Baton Pass through all 4 members. The 4th gets massive damage boost.",why:"4th pass nearly triples damage. Set up all-weakness party comps for maximum chains."}
  ]
},
{
  id:"mhworld",name:"Monster Hunter World / Rise",genre:"Action RPG",category:"rpg",icon:"🐲",color:"#3a6b1a",
  desc:"Hunt massive monsters with 14 weapon types. Deep combat, crafting, and co-op.",
  tags:["Action","RPG","Co-op","Hunting"],
  tips:[
    {level:"beginner",section:"Basics",title:"Attack",controls:["△ and ○ (varies by weapon)"],desc:"Each weapon has unique attack inputs. Triangle and Circle are primary attacks.",why:"14 weapons with completely different movesets. Pick one and learn it deeply."},
    {level:"beginner",section:"Basics",title:"Dodge / Roll",controls:["X"],desc:"Press X to roll. Has I-frames.",why:"Rolling through attacks avoids damage. Time it with monster tells."},
    {level:"beginner",section:"Basics",title:"Sprint",controls:["R1"],desc:"Hold R1 to sprint. Sheaths weapon automatically.",why:"Sheathing to sprint is essential for repositioning during hunts."},
    {level:"beginner",section:"Basics",title:"Use Item",controls:["□"],desc:"Use the selected item from your quick bar.",why:"Potions heal, traps capture, buffs increase damage. Use items freely."},
    {level:"beginner",section:"Basics",title:"Sheathe/Draw Weapon",controls:["R1 / R2 (draw attack)"],desc:"R1 to sheathe, R2 while sheathed for a draw attack.",why:"Draw attacks with Great Sword are some of the strongest hits in the game."},
    {level:"intermediate",section:"Combat",title:"Weak Points",controls:["Aim for head/tail"],desc:"Monster heads and tails take the most damage. Tails can be severed.",why:"Hitting weak points deals 2-3x damage. Hunter's Notes shows exact values."},
    {level:"intermediate",section:"Combat",title:"Elemental Matching",controls:["Check monster weakness"],desc:"Use weapons with the element the monster is weak to.",why:"Matching element adds significant extra damage per hit."},
    {level:"intermediate",section:"Combat",title:"Mounting",controls:["Jump attack from ledge → mini-game"],desc:"Jump off ledges and attack to mount the monster.",why:"Mounting gives free damage and topples the monster for a big damage window."},
    {level:"intermediate",section:"Weapons",title:"Great Sword: Charged Slash",controls:["△ (hold for 3 charge levels)"],desc:"Hold Triangle to charge through 3 levels. Release at max for devastating damage.",why:"Great Sword charged hits are the highest single-hit damage in the game."},
    {level:"intermediate",section:"Weapons",title:"Long Sword: Spirit Blade",controls:["R2 combo → R2 finisher"],desc:"Use R2 to Spirit Blade combo. Landing the finisher levels up your gauge.",why:"Higher Spirit gauge = more damage. Red gauge is your goal."},
    {level:"intermediate",section:"Weapons",title:"Dual Blades: Demon Mode",controls:["R2 to activate"],desc:"Enter Demon Mode for faster attacks and new combos.",why:"Demon Mode transforms your moveset. Essential for Dual Blade DPS."},
    {level:"advanced",section:"Weapons",title:"Charge Blade: SAED",controls:["Shield charge → phial load → Ultra"],desc:"Charge phials, charge shield, then unleash Super Amped Element Discharge.",why:"SAED is the most damaging single ability. Worth learning the complex inputs."},
    {level:"advanced",section:"Combat",title:"Monster Tells",controls:["Watch monster animations"],desc:"Every attack has a telegraph. Learn the tells for each monster.",why:"Knowing what's coming lets you pre-position for counters instead of just dodging."},
    {level:"advanced",section:"Build",title:"Skill Priority",controls:["Weakness Exploit + Critical Eye + Attack Boost"],desc:"These three skills are core DPS for almost every build.",why:"Weakness Exploit gives 50% affinity on weak points. Combine with Crit Eye for 100% crit rate."},
    {level:"expert",section:"Combat",title:"Tenderize + Wallbang",controls:["Clutch claw → flinch shot"],desc:"Clutch onto the monster, tenderize the body part, then flinch shot into a wall.",why:"Tenderizing increases damage. Wall bangs deal massive damage and topple. Do both constantly."},
    {level:"expert",section:"Build",title:"Meta Sets",controls:["Mix armor for optimal skills"],desc:"Mix armor pieces from different sets to get the perfect skill combination.",why:"Full sets are never optimal. Mixed sets with the right skills deal 30-50% more damage."}
  ]
},
{
  id:"darksoul3",name:"Dark Souls III",genre:"Action RPG / Souls-like",category:"rpg",icon:"🔥",color:"#333",
  desc:"The definitive Souls experience. Rolling, parrying, and Weapon Arts through Lothric.",
  tags:["RPG","Souls-like","Dark Fantasy","FromSoftware"],
  tips:[
    {level:"beginner",section:"Combat",title:"Light / Heavy Attack",controls:["R1 / R2"],desc:"R1 for quick, R2 for heavy. Heavy can be charged.",why:"Learn your weapon's combo timing. Each weapon has unique strings."},
    {level:"beginner",section:"Combat",title:"Roll",controls:["○"],desc:"Roll with I-frames. Equip load determines roll speed.",why:"Under 30% = fast roll. Under 70% = medium. Over 70% = fat roll (death sentence)."},
    {level:"beginner",section:"Combat",title:"Block",controls:["L1"],desc:"Block with shield. Stability determines stamina cost.",why:"Good stability shields make early game much easier. Grass Crest Shield boosts stamina recovery."},
    {level:"beginner",section:"Combat",title:"Estus Heal",controls:["□"],desc:"Use Estus Flask to heal.",why:"Allot flasks between HP (Estus) and FP (Ashen) at bonfires. Start with mostly Estus."},
    {level:"beginner",section:"Combat",title:"Lock On",controls:["R3"],desc:"Lock on for tracking and strafing.",why:"Unlock for big bosses. Use unlocked rolling for more directional control."},
    {level:"intermediate",section:"Combat",title:"Weapon Art",controls:["L2"],desc:"Each weapon has a unique Weapon Art ability.",why:"Some Arts are incredibly powerful. Stomp on Great weapons gives hyper armor."},
    {level:"intermediate",section:"Combat",title:"Backstab",controls:["R1 behind enemy"],desc:"Get behind an enemy and press R1 for a devastating backstab.",why:"Circle-strafe slower enemies to get behind them. Massive damage."},
    {level:"intermediate",section:"Combat",title:"Parry",controls:["L2 with parry shield/weapon"],desc:"Press L2 with a parrying tool at the right moment to parry.",why:"Parry → riposte deals enormous damage. Essential for PvP."},
    {level:"intermediate",section:"Combat",title:"Two-Handing",controls:["△ + R1 or △ + L1"],desc:"Two-hand for 1.5x STR and different moveset.",why:"Two-handing lets you use weapons you barely meet the STR requirement for."},
    {level:"intermediate",section:"Exploration",title:"Illusory Walls",controls:["Attack walls"],desc:"Hit suspicious walls to reveal hidden passages.",why:"Many secrets are behind illusory walls. Hit every dead-end wall."},
    {level:"advanced",section:"Build",title:"Infusions",controls:["Blacksmith → infuse"],desc:"Infuse weapons to match your stat build.",why:"Heavy = STR, Sharp = DEX, Refined = Quality, Raw = no scaling (early game)."},
    {level:"advanced",section:"Build",title:"Ring Slots",controls:["Equip 4 rings"],desc:"4 ring slots for powerful buffs. Prisoner's Chain, Ring of Favor, Chloranthy, Hornet.",why:"Ring choice defines your build. The right rings add 30%+ effectiveness."},
    {level:"advanced",section:"PvP",title:"Spacing",controls:["Stay just outside attack range"],desc:"Position yourself at the tip of your weapon's max range.",why:"Hit them, they can't hit you. Spacing wins duels."},
    {level:"expert",section:"Combat",title:"Roll Catching",controls:["Delay your attack after their roll"],desc:"Wait a half-beat after the enemy rolls, then attack as their I-frames end.",why:"The #1 PvP skill. Most players panic-roll. Catch them every time."},
    {level:"expert",section:"Build",title:"SL120 Meta Build",controls:["Optimize stats at level 120"],desc:"Level 120 is the PvP meta. 40/40 Quality or 60 DEX are standard.",why:"Soft caps at 40, hard caps at 60. Don't level past 120 for active PvP matchmaking."}
  ]
},
{
  id:"lies-of-p",name:"Lies of P",genre:"Action RPG / Souls-like",category:"rpg",icon:"🎭",color:"#1a0a3a",
  desc:"Puppet-themed Souls-like. Perfect Guard, Legion Arms, and Fable Arts in Krat.",
  tags:["Action","RPG","Souls-like","Gothic"],
  tips:[
    {level:"beginner",section:"Combat",title:"Attack",controls:["R1 (light) / R2 (heavy)"],desc:"R1 for quick, R2 for charged heavy attacks.",why:"R2 charged attacks deal massive damage and break guard."},
    {level:"beginner",section:"Combat",title:"Block",controls:["L1 (hold)"],desc:"Hold L1 to block.",why:"Blocking in Lies of P still takes chip damage through the guard. Perfect Guard is better."},
    {level:"beginner",section:"Combat",title:"Perfect Guard",controls:["L1 (tap at impact)"],desc:"Tap L1 at the exact moment of impact for Perfect Guard.",why:"CORE MECHANIC. No chip damage, builds enemy stagger, and recovers your HP. Master this."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["○"],desc:"Press Circle to dodge.",why:"Dodge unblockable red attacks. Perfect Guard handles everything else."},
    {level:"beginner",section:"Combat",title:"Legion Arm",controls:["L2"],desc:"Press L2 to use your equipped Legion Arm ability.",why:"Each arm has a unique powerful ability. Puppet String pulls enemies close."},
    {level:"intermediate",section:"Combat",title:"Fable Arts",controls:["L1 + R1 (light) / L1 + R2 (heavy)"],desc:"Spend Fable gauge for powerful weapon abilities.",why:"Fable Arts are your strongest moves. Build gauge with attacks, spend on arts."},
    {level:"intermediate",section:"Combat",title:"Stagger System",controls:["Attack until white bar fills → Fatal Attack"],desc:"Fill the white stagger bar to stagger the enemy for a Fatal Attack.",why:"Fatal Attacks deal massive damage. The primary way to kill bosses."},
    {level:"intermediate",section:"Combat",title:"Guard Regain",controls:["Attack after blocking to recover HP"],desc:"Attacks after blocking recover the gray portion of your lost HP.",why:"Like Bloodborne's rally — aggression after defense heals you."},
    {level:"intermediate",section:"Weapons",title:"Weapon Assembly",controls:["Combine handles and blades"],desc:"Mix and match weapon blades and handles for custom combos.",why:"A heavy blade on a fast handle creates unique hybrid weapons."},
    {level:"advanced",section:"Combat",title:"Perfect Guard Chains",controls:["L1 tap repeatedly against combos"],desc:"Chain Perfect Guards against multi-hit enemy combos.",why:"Each Perfect Guard in a chain builds stagger. Long boss combos become stagger opportunities."},
    {level:"advanced",section:"Build",title:"P-Organ Upgrades",controls:["Quartz → upgrade tree"],desc:"Spend Quartz on the P-Organ upgrade tree for passive abilities.",why:"Some upgrades are transformative. Extra Pulse Cell, Perfect Guard window increase, etc."},
    {level:"advanced",section:"Build",title:"Ergo Management",controls:["Spend at Stargazers or risk losing"],desc:"Spend Ergo (souls) at every Stargazer. Death = dropped Ergo.",why:"Don't hoard. Level up or buy items. Losing a big Ergo pile is devastating."},
    {level:"expert",section:"Combat",title:"Perfect Guard → Charged R2 → Fatal",controls:["Perfect Guard chain → full charge → Fatal Attack"],desc:"Perfect Guard a combo, charge R2 to max during the opening, trigger Fatal Attack.",why:"The optimal damage loop. Guard → charge → stagger → Fatal Attack → repeat."},
    {level:"expert",section:"Build",title:"Motivity vs Technique",controls:["Pick one and commit"],desc:"Motivity = Strength weapons. Technique = Dexterity weapons. Don't split evenly.",why:"Focused builds deal dramatically more damage than split builds."}
  ]
},
{
  id:"bg3",name:"Baldur's Gate 3",genre:"CRPG / Tactical",category:"rpg",icon:"🎲",color:"#6b1a1a",
  desc:"D&D rules brought to life. Turn-based tactics, dialogue choices, and party management.",
  tags:["RPG","Tactical","Turn-Based","Co-op"],
  tips:[
    {level:"beginner",section:"Basics",title:"Move Character",controls:["Left Stick / X to confirm"],desc:"Move with stick, press X to confirm destination.",why:"Movement uses your speed stat. Don't waste movement going back and forth."},
    {level:"beginner",section:"Combat",title:"Attack",controls:["Select action → target"],desc:"Choose Attack action, then select your target.",why:"Basic attacks use your action. You get one action and one bonus action per turn."},
    {level:"beginner",section:"Combat",title:"Jump / Disengage",controls:["Bonus action → Jump"],desc:"Jump as a bonus action to disengage without provoking attacks.",why:"Moving away from enemies normally provokes opportunity attacks. Jump to avoid them."},
    {level:"beginner",section:"Basics",title:"Quicksave",controls:["F5 / Options"],desc:"Save frequently.",why:"Dice rolls fail. Conversations go wrong. Save before EVERYTHING important."},
    {level:"beginner",section:"Exploration",title:"Interact",controls:["X on highlighted objects"],desc:"Press X to interact with objects, talk to NPCs, pick up items.",why:"Interact with everything. BG3 hides content in unexpected places."},
    {level:"intermediate",section:"Combat",title:"Bonus Actions",controls:["Separate from main action"],desc:"Shove, drink potion, offhand attack, jump, hide — all bonus actions.",why:"Never waste a bonus action. Always shove enemies off cliffs, drink potions, or hide."},
    {level:"intermediate",section:"Combat",title:"Shove",controls:["Select Shove → target near edge"],desc:"Push an enemy off a cliff or into a hazard.",why:"Shove kills ignore HP. A 500HP boss dies to a cliff fall just like anything else."},
    {level:"intermediate",section:"Combat",title:"Height Advantage",controls:["Position above enemies"],desc:"Higher ground gives advantage on ranged attacks (+2).",why:"Always take high ground. Archers on rooftops dominate encounters."},
    {level:"intermediate",section:"Combat",title:"Concentration",controls:["Only one concentration spell active"],desc:"You can only maintain one concentration spell at a time.",why:"Don't waste a new concentration spell over an active one. Plan your spell slots."},
    {level:"intermediate",section:"Social",title:"Persuasion / Deception",controls:["Dialogue choices + dice roll"],desc:"Speech checks use your Charisma + proficiency.",why:"Many fights can be avoided entirely through speech. A persuasion success saves resources."},
    {level:"advanced",section:"Combat",title:"Environmental Combos",controls:["Grease + Fire = explosion"],desc:"Create environmental hazards. Water + Lightning, Grease + Fire, etc.",why:"Environmental damage ignores resistance. Combo setups can wipe entire encounters."},
    {level:"advanced",section:"Combat",title:"Counterspell",controls:["Reaction → Counterspell"],desc:"Use your reaction to negate an enemy spell.",why:"Stopping a Fireball or Hold Person can save your party. Always keep Counterspell prepared."},
    {level:"advanced",section:"Build",title:"Multiclass",controls:["Level up → select different class"],desc:"Take levels in multiple classes for combo abilities.",why:"Some multiclass combos are incredibly powerful. Paladin 2 / Sorcerer X for smite + sorcery."},
    {level:"expert",section:"Combat",title:"Action Surge + Smite Nova",controls:["Fighter 2 / Paladin X → Action Surge → 4 smites in one turn"],desc:"Action Surge gives an extra action. Use it to dump 4 Divine Smites in one turn.",why:"The highest single-turn damage in the game. One-rounds most bosses."},
    {level:"expert",section:"Social",title:"Stacking Advantages",controls:["Enhance Ability + Guidance + Friends"],desc:"Stack speech-boosting spells before important conversations.",why:"Guidance + Enhance Ability + high CHA = near-guaranteed speech checks."}
  ]
},
{
  id:"diablo4",name:"Diablo IV",genre:"Action RPG / ARPG",category:"rpg",icon:"💀",color:"#8b0000",
  desc:"Slay demons across Sanctuary. Skills, Paragon, Helltides, and endgame grinding.",
  tags:["Action","RPG","Loot","Multiplayer"],
  tips:[
    {level:"beginner",section:"Combat",title:"Basic Attack",controls:["□"],desc:"Press Square for your basic attack.",why:"Basic attacks generate resource (Fury, Energy, Essence, etc.). Use to fuel skills."},
    {level:"beginner",section:"Combat",title:"Skills",controls:["R1/R2/L1/face buttons"],desc:"Each button maps to an equipped skill.",why:"Build around 6 skills that synergize. Don't spread randomly."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["○"],desc:"Press Circle to dodge roll. Has a cooldown.",why:"I-frames during the dodge. Essential for avoiding boss one-shots."},
    {level:"beginner",section:"Combat",title:"Potion",controls:["D-Pad up or assigned"],desc:"Use your healing potion.",why:"Potion has limited charges that refill from drops. Don't waste them on trash mobs."},
    {level:"beginner",section:"Basics",title:"Map / Teleport",controls:["Touchpad → select waypoint"],desc:"Open map and teleport to unlocked waypoints.",why:"Fast travel saves time. Unlock every waypoint you pass."},
    {level:"intermediate",section:"Build",title:"Skill Synergy",controls:["Read tooltips carefully"],desc:"Skills that enhance each other create powerful loops.",why:"A Frozen Orb that procs Ice Shards that proc Blizzard is exponentially stronger than individual skills."},
    {level:"intermediate",section:"Build",title:"Aspects",controls:["Codex of Power / Extracted from legendaries"],desc:"Imprint Aspects onto rare items to make them legendary.",why:"Aspects define your build. The right aspect can 5x your damage."},
    {level:"intermediate",section:"Combat",title:"Crowd Control",controls:["Stun, freeze, slow effects"],desc:"Enemies affected by CC take bonus damage from certain skills/aspects.",why:"CC chains (freeze → shatter) are the core of high-damage builds."},
    {level:"intermediate",section:"Progression",title:"Renown",controls:["Complete region activities"],desc:"Earn Renown from dungeons, side quests, exploration.",why:"Renown gives skill points, potion charges, and Paragon points. Huge power spikes."},
    {level:"advanced",section:"Endgame",title:"Helltide",controls:["Farm Aberrant Cinders → open chests"],desc:"Helltide zones drop special currency for guaranteed legendary chests.",why:"The most efficient legendary farming in the game. Focus on Helltides for gear."},
    {level:"advanced",section:"Endgame",title:"Nightmare Dungeons",controls:["Use Nightmare Sigils"],desc:"Higher tier sigils = better loot and more XP.",why:"Main source of Paragon XP endgame. Push the highest tier you can clear."},
    {level:"advanced",section:"Build",title:"Paragon Board",controls:["Level 50+ → Paragon tree"],desc:"Navigate the Paragon board for powerful passive nodes.",why:"Paragon boards make or break endgame builds. Plan your path for Glyphs and rare nodes."},
    {level:"expert",section:"Build",title:"Glyph Leveling",controls:["Level Glyphs in Nightmare Dungeons"],desc:"Glyphs gain XP from NM dungeons and provide massive stat boosts at level 15+.",why:"A level 15 Glyph is 3-5x more powerful than level 1. Prioritize Glyph leveling."},
    {level:"expert",section:"Build",title:"Uber Boss Preparation",controls:["Max resistances + defensive aspects"],desc:"Uber bosses require capped resistances and layered defenses to survive.",why:"You can't DPS a boss if you're dead. Defense is as important as offense for endgame."}
  ]
}
]);
