registerGames([
{
  id:"gow-ragnarok",name:"God of War Ragnarok",genre:"Action / Adventure",category:"action",icon:"🪓",color:"#8b0000",
  desc:"Master Kratos across all Nine Realms. Axe, Blades, Spear, and runic combat.",
  tags:["Action","Adventure","Story","Single Player"],
  tips:[
    {level:"beginner",section:"Combat",title:"Light Attack",controls:["R1"],desc:"Quick light attack. Fast and safe.",why:"Main damage tool. Fast enough to interrupt most enemy attacks."},
    {level:"beginner",section:"Combat",title:"Heavy Attack",controls:["R2"],desc:"Slower heavy attack with more damage and stagger.",why:"Staggers enemies faster. Use when you have an opening."},
    {level:"beginner",section:"Combat",title:"Block",controls:["L1 (hold)"],desc:"Hold L1 to block incoming attacks.",why:"Reduces damage. Yellow attacks can be parried, red attacks must be dodged."},
    {level:"beginner",section:"Combat",title:"Parry",controls:["L1 (tap at impact)"],desc:"Tap L1 right before impact for a parry that stuns enemies.",why:"Parrying opens massive damage windows. Essential on higher difficulties."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["X + direction"],desc:"Press X to dodge. Double tap for a roll.",why:"Red ring attacks are unblockable — dodge is your only option."},
    {level:"beginner",section:"Combat",title:"Axe Throw & Recall",controls:["L2 (aim) + R1/R2 (throw) / △ (recall)"],desc:"Aim, throw, and recall the Leviathan Axe.",why:"Recalled axe deals damage on return. Freeze one enemy, fight others, recall for bonus hit."},
    {level:"beginner",section:"Combat",title:"Atreus / Companion",controls:["□"],desc:"Press Square to command your companion to attack.",why:"Companion staggers enemies and applies status effects. Free DPS — use it constantly."},
    {level:"intermediate",section:"Weapons",title:"Weapon Switching",controls:["D-Pad left/right/down"],desc:"Left = Axe, Right = Blades of Chaos, Down = Draupnir Spear.",why:"Each weapon has elemental strengths. Switch to exploit enemy weaknesses."},
    {level:"intermediate",section:"Combat",title:"Runic Attacks",controls:["L1 + R1 (Light) / L1 + R2 (Heavy)"],desc:"Trigger powerful runic specials with cooldowns.",why:"Massive burst damage. Use to start fights or finish tough enemies quickly."},
    {level:"intermediate",section:"Combat",title:"Spartan Rage",controls:["L3 + R3"],desc:"Click both sticks when rage meter is full.",why:"Heals you with every hit. Save for when you're low HP — it's a survival tool."},
    {level:"intermediate",section:"Combat",title:"Shield Strike",controls:["L1 + L1"],desc:"Double tap L1 for a shield bash that breaks guards.",why:"Essential against shielded enemies and interrupts attacks."},
    {level:"intermediate",section:"Weapons",title:"Frost Awaken / Flame Whiplash",controls:["△ (hold)"],desc:"Hold Triangle to charge weapon ability for bonus elemental damage.",why:"Charged attacks deal massive elemental damage on your next hits."},
    {level:"advanced",section:"Combat",title:"Permafrost / Immolation",controls:["Consecutive hits without taking damage"],desc:"Build weapon glow by landing consecutive hits. Max glow = elemental damage on every hit.",why:"Massively increases DPS. One hit resets your buildup, so play carefully."},
    {level:"advanced",section:"Combat",title:"Stagger Management",controls:["Mix light/heavy to stagger bar"],desc:"Alternate between light and heavy attacks to fill the enemy stagger bar.",why:"Once staggered, enemies are vulnerable to a massive damage window."},
    {level:"advanced",section:"Weapons",title:"Spear Detonation",controls:["Impale with spear throws → △ to detonate"],desc:"Impale enemies with spear throws, then Triangle detonates all at once.",why:"Stack 3+ spears on a boss then detonate for massive AoE burst."},
    {level:"expert",section:"Combat",title:"Parry Window Mastery",controls:["Frame-perfect L1"],desc:"On Give Me No Mercy+, the parry window is tiny. Train exact timing.",why:"Parrying is almost mandatory on max difficulty. Highest skill expression in combat."},
    {level:"expert",section:"Combat",title:"Runic Cancel",controls:["Dodge during Runic attack"],desc:"Start a Runic, dodge to cancel recovery while keeping first-hit damage.",why:"Get burst damage without being animation-locked. Dramatically speeds up combat."},
    {level:"expert",section:"Combat",title:"Juggle Combos",controls:["Launch → air combo → slam"],desc:"Use shield bash or certain attacks to launch enemies, combo them midair, then slam.",why:"Airborne enemies can't fight back. Maximum damage with zero risk."}
  ]
},
{
  id:"spiderman2",name:"Marvel's Spider-Man 2",genre:"Action / Open World",category:"action",icon:"🕷️",color:"#cc0000",
  desc:"Swing through NYC as Peter and Miles. Web combat, symbiote powers, and traversal mastery.",
  tags:["Action","Open World","Superhero","PS5"],
  tips:[
    {level:"beginner",section:"Traversal",title:"Web Swing",controls:["R2"],desc:"Hold R2 to swing. Release at bottom of arc for max momentum.",why:"Timing release at the low point gives maximum speed and height."},
    {level:"beginner",section:"Traversal",title:"Zip to Point",controls:["R2 + X"],desc:"While swinging, press X to zip to a perch point.",why:"Maintains altitude and repositions quickly."},
    {level:"beginner",section:"Traversal",title:"Web Wings",controls:["△ (in air)"],desc:"Press Triangle while airborne to glide with web wings.",why:"Covers huge distances. Use wind tunnels for speed boosts."},
    {level:"beginner",section:"Combat",title:"Attack Combo",controls:["□ chain"],desc:"Press Square repeatedly for combo strings.",why:"Foundation of combat. Learn the full string before adding abilities."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["○"],desc:"Press Circle when spider-sense flashes to dodge.",why:"Perfect dodge (last second) slows time for free counterattacks."},
    {level:"beginner",section:"Combat",title:"Web Shoot",controls:["R1"],desc:"Tap R1 to shoot webs that slow and web up enemies near walls.",why:"Web up enemies near walls for instant KO. Free takedowns."},
    {level:"beginner",section:"Combat",title:"Heal",controls:["D-Pad down"],desc:"Press down on D-Pad to heal when focus bar has charges.",why:"Healing uses focus — same resource as finishers. Balance healing vs finishing."},
    {level:"intermediate",section:"Combat",title:"Air Launch",controls:["Hold □"],desc:"Hold Square to launch enemies into the air for air combos.",why:"Airborne enemies are isolated from allies. Easier to fight one-on-one."},
    {level:"intermediate",section:"Combat",title:"Yank & Throw",controls:["L1 + R1"],desc:"Hold L1+R1 to yank enemies or objects toward you and throw them.",why:"Thrown objects hit hard and can hit multiple enemies. Use environmental objects."},
    {level:"intermediate",section:"Combat",title:"Web Strike",controls:["△"],desc:"Press Triangle to zip to an enemy and attack.",why:"Closes distance instantly. Great for picking off ranged enemies."},
    {level:"intermediate",section:"Peter",title:"Symbiote Surge",controls:["L3 + R3"],desc:"Activate symbiote mode for enhanced AoE attacks.",why:"Dramatically increases AoE damage. Save for large groups."},
    {level:"intermediate",section:"Miles",title:"Venom Powers",controls:["L1 + face button"],desc:"Hold L1 and press a face button for bioelectric Venom abilities.",why:"Venom Punch breaks any guard. Venom Jump is the best crowd control."},
    {level:"intermediate",section:"Stealth",title:"Stealth Takedown",controls:["□ from above/behind"],desc:"Approach undetected and press Square for a silent takedown.",why:"Saves health and time. Clear outer enemies silently before going loud."},
    {level:"advanced",section:"Combat",title:"Parry",controls:["L1 (just before hit)"],desc:"Tap L1 just before impact to parry.",why:"Parried enemies are stunned longer than dodged ones. Works on specific attacks only."},
    {level:"advanced",section:"Combat",title:"Gadget Combos",controls:["R1 + gadget select"],desc:"Combine Web Grabber (groups enemies) + Impact Web (pins them all).",why:"Gadget combos end fights fast. Pair complementary gadgets."},
    {level:"advanced",section:"Stealth",title:"Web Line Takedown",controls:["Perch on web line → △"],desc:"Stealth takedown from a web line. Can grab two enemies at once.",why:"Clears pairs without detection. Essential for stealth base missions."},
    {level:"expert",section:"Combat",title:"Swing Kick",controls:["△ while swinging near enemies"],desc:"Press Triangle while swinging fast for a devastating kick.",why:"Highest single-hit damage. Build speed then swing kick into groups."},
    {level:"expert",section:"Combat",title:"Perfect Dodge Chain",controls:["○ → □ rapidly"],desc:"Perfect dodge then immediately attack for special counter.",why:"3x damage and rapid focus build. Chain perfect dodges for constant slow-mo."},
    {level:"expert",section:"Combat",title:"Focus Finisher",controls:["△ + ○ (focus bar full)"],desc:"Instant takedown on any regular enemy. Heals you.",why:"Instant kill + heal. Save focus for when overwhelmed or low HP."}
  ]
},
{
  id:"ghost",name:"Ghost of Tsushima",genre:"Action / Open World",category:"action",icon:"⛩️",color:"#4a0e0e",
  desc:"Become the Ghost. Samurai stances, stealth, standoffs, and Mythic Arts on Tsushima.",
  tags:["Action","Open World","Samurai","Stealth"],
  tips:[
    {level:"beginner",section:"Combat",title:"Quick Attack",controls:["□"],desc:"Square for a quick katana strike.",why:"Fast and versatile. Core of every combo."},
    {level:"beginner",section:"Combat",title:"Heavy Attack",controls:["△"],desc:"Triangle for a heavy, stance-breaking attack.",why:"Breaks guards. Essential against shielded enemies."},
    {level:"beginner",section:"Combat",title:"Block / Parry",controls:["L1 (hold/tap)"],desc:"Hold L1 to block, tap at the right moment to parry.",why:"Blue glint = parryable. Red = dodge only. Perfect parry creates huge openings."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["○"],desc:"Circle to dodge. Required for unblockable red attacks.",why:"Red attacks MUST be dodged. Learn enemy tells for red vs blue."},
    {level:"beginner",section:"Exploration",title:"Guiding Wind",controls:["Swipe Touchpad"],desc:"Swipe the touchpad to summon a guiding wind toward your objective.",why:"No minimap cluttering the screen. The wind IS your navigation."},
    {level:"intermediate",section:"Stances",title:"Switch Stances",controls:["R2 + □/△/○/X"],desc:"Hold R2 + face button: Stone (swords), Water (shields), Wind (spears), Moon (brutes).",why:"Each stance is STRONG against its enemy type. Wrong stance = dramatically less effective."},
    {level:"intermediate",section:"Combat",title:"Standoff",controls:["D-Pad up near enemies"],desc:"Challenge a group. Release Triangle at the right moment to instant-kill.",why:"Upgraded, kills up to 5 in a row. Best opener in the game."},
    {level:"intermediate",section:"Ghost",title:"Ghost Weapons",controls:["L2 + face button"],desc:"Kunai, smoke bombs, sticky bombs, wind chimes.",why:"Kunai staggers groups, smoke enables stealth kills. Overpowered tools."},
    {level:"intermediate",section:"Ghost",title:"Stealth Kill",controls:["□ from behind"],desc:"Approach undetected and press Square for an assassination.",why:"Silent, instant, and doesn't alert others if you're hidden."},
    {level:"intermediate",section:"Ranged",title:"Bow",controls:["L2 (aim) + R2 (fire)"],desc:"Aim and fire your bow. Half-bow for speed, longbow for range.",why:"Headshots kill most enemies instantly. Thin out groups before engaging."},
    {level:"intermediate",section:"Combat",title:"Resolve Heal",controls:["D-Pad down"],desc:"Spend Resolve to heal in combat.",why:"Resolve fills from combat. Balance between healing and Mythic Arts."},
    {level:"advanced",section:"Mythic",title:"Mythic Arts",controls:["Unlocked via Tales → special inputs"],desc:"Dance of Wrath (3 unblockable strikes), Heavenly Strike (fast stab), etc.",why:"Mythic Arts are your strongest moves. Each has specific situations where it excels."},
    {level:"advanced",section:"Combat",title:"Perfect Parry Chain",controls:["L1 tap repeatedly, perfectly timed"],desc:"Chain perfect parries against rapid attacks.",why:"Against dueling bosses, perfect parry chains are the fastest path to victory."},
    {level:"advanced",section:"Ghost",title:"Chain Assassination",controls:["Stealth kill → △ to chain"],desc:"After a stealth kill, press Triangle to chain to nearby enemies.",why:"Upgraded, kills 3 enemies in one sequence. Clears entire patrols."},
    {level:"expert",section:"Combat",title:"Heavenly Strike Cancel",controls:["Heavenly Strike → dodge → repeat"],desc:"Use Heavenly Strike, dodge cancel recovery, immediately repeat.",why:"Infinite Heavenly Strike loop is the highest DPS combo. Melts bosses on Lethal."},
    {level:"expert",section:"Combat",title:"Dance of Wrath + Smoke",controls:["Smoke bomb → Dance of Wrath"],desc:"Smoke a group, then Dance of Wrath while they're blinded.",why:"3 unblockable strikes into blinded enemies. Usually kills everything in the cloud."},
    {level:"expert",section:"Stances",title:"Stance Cancel Combos",controls:["Switch stances mid-combo"],desc:"Switch stances between swings for mixed combo strings.",why:"Catches enemies off-guard and deals with mixed enemy groups without pausing."}
  ]
},
{
  id:"sekiro",name:"Sekiro: Shadows Die Twice",genre:"Action / Souls-like",category:"action",icon:"🗡️",color:"#3a0a0a",
  desc:"Master the way of the shinobi. Deflection-based combat, prosthetics, and deathblows.",
  tags:["Action","Souls-like","Ninja","FromSoftware"],
  tips:[
    {level:"beginner",section:"Combat",title:"Attack",controls:["R1"],desc:"Press R1 for a quick sword strike.",why:"Attacking an enemy who's blocking builds their posture meter."},
    {level:"beginner",section:"Combat",title:"Deflect",controls:["L1 (tap at impact)"],desc:"Tap L1 just as an attack lands to deflect it perfectly.",why:"DEFLECTION IS THE CORE MECHANIC. Unlike other Souls games, deflecting is more important than dodging."},
    {level:"beginner",section:"Combat",title:"Block",controls:["L1 (hold)"],desc:"Hold L1 to block. Reduces damage but builds your posture.",why:"Blocking is a fallback. If your posture breaks, you're stunned. Deflect instead."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["○"],desc:"Press Circle to dodge/step. Quick step while locked on.",why:"Dodge grab attacks (red kanji) since they can't be deflected."},
    {level:"beginner",section:"Combat",title:"Jump",controls:["X"],desc:"Press X to jump. Can jump over sweep attacks.",why:"Jump over sweep attacks (red kanji sweep). Stomp on the enemy's head for posture damage."},
    {level:"beginner",section:"Combat",title:"Deathblow",controls:["R1 when posture broken or from stealth"],desc:"Press R1 when the red dot appears for an instant kill.",why:"Deathblows are your goal. Build posture until the dot appears, or sneak up for stealth kills."},
    {level:"beginner",section:"Stealth",title:"Crouch / Stealth",controls:["○ (hold)"],desc:"Hold Circle to crouch and move silently.",why:"Stealth deathblows skip entire health bars. Always sneak when possible."},
    {level:"intermediate",section:"Combat",title:"Mikiri Counter",controls:["○ toward thrust attack"],desc:"Dodge TOWARD a thrust attack (red kanji thrust) to Mikiri Counter.",why:"Deals massive posture damage. The most important skill to unlock and master."},
    {level:"intermediate",section:"Combat",title:"Prosthetic Tools",controls:["R2"],desc:"Press R2 to use your equipped prosthetic arm tool.",why:"Firecrackers stun beasts, axe breaks shields, shuriken hits airborne enemies."},
    {level:"intermediate",section:"Combat",title:"Prosthetic Swap",controls:["D-Pad up/right"],desc:"Swap between equipped prosthetic tools.",why:"Different bosses require different tools. Always have 3 relevant ones equipped."},
    {level:"intermediate",section:"Combat",title:"Combat Arts",controls:["L1 + R1"],desc:"Press L1+R1 for your equipped Combat Art.",why:"Combat Arts are powerful moves. Ichimonji Double restores your posture while dealing damage."},
    {level:"intermediate",section:"Combat",title:"Grapple",controls:["L2 toward grapple point"],desc:"Grapple to points for vertical traversal and gap crossing.",why:"Use grapples in combat to reposition and find stealth angles."},
    {level:"intermediate",section:"Items",title:"Gourd Heal",controls:["□"],desc:"Press Square to drink from your healing gourd.",why:"Limited charges. Bosses punish slow heals — only heal during safe windows."},
    {level:"advanced",section:"Combat",title:"Lightning Reversal",controls:["Jump → get hit by lightning → R1 before landing"],desc:"Jump, get hit by lightning in the air, press R1 to throw it back before landing.",why:"Sends the lightning back for massive damage and stun. Trivializes lightning bosses."},
    {level:"advanced",section:"Combat",title:"Posture Management",controls:["Hold block to recover posture"],desc:"When not attacking, hold block to steadily recover your posture meter.",why:"If posture breaks, you're staggered for a free hit. Step back and block to recover."},
    {level:"advanced",section:"Combat",title:"Ichimonji Double",controls:["Combat Art: L1 + R1"],desc:"Overhead slam that recovers your posture on hit.",why:"The best combat art for most of the game. Attack and heal posture simultaneously."},
    {level:"advanced",section:"Stealth",title:"Puppeteer Ninjutsu",controls:["Stealth deathblow → command"],desc:"After a stealth kill, use Puppeteer to make the victim fight their allies.",why:"Turns one enemy into your ally. They fight for you while you pick off the rest."},
    {level:"expert",section:"Combat",title:"Deflect → Mortal Draw",controls:["Perfect deflect → immediate Mortal Draw"],desc:"Deflect a boss attack then immediately use Mortal Draw combat art.",why:"Mortal Draw deals damage through blocks. The highest damage combo after a deflect window."},
    {level:"expert",section:"Combat",title:"Aggressive Deflect Rhythm",controls:["Attack → deflect → attack → deflect"],desc:"Alternate between attacking and deflecting in a constant rhythm against bosses.",why:"The 'dance' of Sekiro. Constant aggression builds their posture while deflects protect yours."},
    {level:"expert",section:"Combat",title:"Jump Stomp Loops",controls:["Jump over sweep → stomp → repeat"],desc:"On sweep-heavy enemies, jump and stomp repeatedly for free posture damage.",why:"Each stomp deals significant posture damage. Some bosses can be stomped to death."}
  ]
},
{
  id:"helldivers2",name:"Helldivers 2",genre:"Action / Shooter",category:"action",icon:"🦅",color:"#1a3a0a",
  desc:"Spread democracy. Stratagems, teamwork, and bug-squashing across the galaxy.",
  tags:["Action","Co-op","Shooter","Multiplayer"],
  tips:[
    {level:"beginner",section:"Combat",title:"Aim & Shoot",controls:["L2 (aim) + R2 (fire)"],desc:"Standard aim and fire.",why:"Hip-fire is inaccurate. Always ADS for anything beyond close range."},
    {level:"beginner",section:"Combat",title:"Reload",controls:["□"],desc:"Press Square to reload. Uses entire magazine.",why:"Magazines, not individual bullets. Reloading a half-full mag wastes the remaining rounds."},
    {level:"beginner",section:"Combat",title:"Melee",controls:["R3"],desc:"Click right stick for a melee attack.",why:"Last resort. Knife kills small bugs but you'll die trying to melee a Charger."},
    {level:"beginner",section:"Movement",title:"Sprint",controls:["L3 (click)"],desc:"Click left stick to toggle sprint.",why:"Sprinting is essential for repositioning and running from overwhelming forces."},
    {level:"beginner",section:"Movement",title:"Dive / Prone",controls:["○"],desc:"Press Circle to dive prone.",why:"Dive to avoid explosions, rockets, and charger attacks. I-frames during the dive."},
    {level:"beginner",section:"Stratagems",title:"Call Stratagem",controls:["L1 (hold) + D-Pad combo"],desc:"Hold L1 and input the D-Pad code shown for the stratagem, then throw the beacon.",why:"Stratagems are your heavy weapons, support, and orbital strikes. Memorize the codes."},
    {level:"beginner",section:"Stratagems",title:"Resupply",controls:["L1 → ↓↓↑→"],desc:"Call in an ammo resupply for your team.",why:"You will run out of ammo. Call resupply proactively, not when you're empty."},
    {level:"intermediate",section:"Combat",title:"Third-Person Aim",controls:["Hold L2 (zoomed)"],desc:"Some weapons have different zoom modes. Tap vs hold L2.",why:"Third-person aiming gives more situational awareness in chaotic fights."},
    {level:"intermediate",section:"Combat",title:"Grenade",controls:["R1"],desc:"Press R1 to throw a grenade.",why:"Grenades close bug holes permanently. Save some for objectives."},
    {level:"intermediate",section:"Stratagems",title:"Orbital Strike",controls:["L1 → specific combo"],desc:"Call in orbital bombardments on enemy positions.",why:"Clears entire areas. Throw the beacon AWAY from teammates — friendly fire is always on."},
    {level:"intermediate",section:"Stratagems",title:"Eagle Airstrike",controls:["L1 → specific combo"],desc:"Call in an Eagle airstrike that strafes a line.",why:"Aim the throw direction — the Eagle follows the line you threw it along."},
    {level:"intermediate",section:"Teamwork",title:"Reinforce",controls:["L1 → ↑↓→←↑"],desc:"Call in reinforcements to respawn dead teammates.",why:"Teammates have limited reinforces. Don't waste lives — play carefully."},
    {level:"intermediate",section:"Combat",title:"Switch Weapon",controls:["△"],desc:"Press Triangle to switch to your secondary or support weapon.",why:"Support weapons are your heavy hitters. Switch to them for armored targets."},
    {level:"advanced",section:"Stratagems",title:"Turret Placement",controls:["Call in turret → aim beacon placement"],desc:"Place turrets at choke points or objective defense locations.",why:"Turrets cover your flanks while you focus forward. Position matters more than firepower."},
    {level:"advanced",section:"Combat",title:"Armor Weak Points",controls:["Aim for soft spots on armored enemies"],desc:"Chargers: shoot the leg armor off, then shoot the exposed flesh. Bile Titans: underside.",why:"Don't waste ammo shooting armor plating. Target weak points for 10x damage."},
    {level:"advanced",section:"Teamwork",title:"Kiting Strategy",controls:["One player kites, others damage"],desc:"One player draws aggro by running while others shoot from safety.",why:"Kiting a Charger or Bile Titan while teammates unload support weapons is the safest strategy."},
    {level:"expert",section:"Stratagems",title:"Stratagem Spam Speed",controls:["Memorize D-Pad combos"],desc:"Memorize your loadout's codes so you can input them instantly without looking.",why:"Fast stratagem input in emergencies saves lives. 2 seconds of fumbling = team wipe."},
    {level:"expert",section:"Strategy",title:"Objective Priority",controls:["Side objectives → main → extract"],desc:"Complete side objectives first for bonus rewards, then main, then extract.",why:"Optimal mission flow maximizes samples and XP. Don't beeline for main objective."},
    {level:"expert",section:"Combat",title:"Friendly Fire Management",controls:["Check lines of fire constantly"],desc:"Always know where your teammates are. Orbital strikes and rockets kill you too.",why:"More players die to friendly fire than enemies at higher difficulties. Communicate before calling strikes."}
  ]
},
{
  id:"returnal",name:"Returnal",genre:"Action / Roguelike",category:"action",icon:"🌀",color:"#00838f",
  desc:"Die, loop, adapt. Bullet-hell roguelike with punishing combat on an alien planet.",
  tags:["Action","Roguelike","Shooter","PS5 Exclusive"],
  tips:[
    {level:"beginner",section:"Combat",title:"Shoot",controls:["R2 (half/full press)"],desc:"Half-press R2 for normal fire, full press for Alt-Fire mode.",why:"The DualSense adaptive trigger gives you two fire modes on one button. Master both."},
    {level:"beginner",section:"Combat",title:"Dash",controls:["○"],desc:"Press Circle to dash. You have I-frames during the dash.",why:"Dash THROUGH projectiles, not away from them. I-frames make you invincible mid-dash."},
    {level:"beginner",section:"Combat",title:"Melee",controls:["□"],desc:"Press Square for a melee strike.",why:"Melee is powerful and breaks shields. Use it when enemies get close."},
    {level:"beginner",section:"Combat",title:"ADS",controls:["L2"],desc:"Hold L2 to aim down sights.",why:"ADS is optional in Returnal. Many players hip-fire while dashing for better mobility."},
    {level:"beginner",section:"Exploration",title:"Scan",controls:["L1"],desc:"Press L1 to scan objects and lore.",why:"Scanning reveals item effects and advances the story. Do it on everything."},
    {level:"intermediate",section:"Combat",title:"Alt-Fire",controls:["R2 (full press, charged)"],desc:"Full press trigger for your weapon's alt-fire mode.",why:"Alt-fires are extremely powerful. Doombringer, Killsight, and Shieldbreaker are game-changers."},
    {level:"intermediate",section:"Combat",title:"Overload Reload",controls:["R2 at the right time during reload"],desc:"When reloading, press R2 in the highlighted zone for an instant reload.",why:"Like active reload from Gears. Faster reload AND sometimes bonus damage."},
    {level:"intermediate",section:"Survival",title:"Parasites",controls:["Pick up from environment"],desc:"Parasites give a positive AND negative effect. Weigh both.",why:"Some negative effects are trivial. A parasite that gives 25% damage but reduces obolites is worth it."},
    {level:"intermediate",section:"Survival",title:"Integrity (Health)",controls:["Collect Silphium when full for max HP increase"],desc:"When at full HP, Silphium increases your max health instead.",why:"Stay at full HP and every Silphium becomes a permanent max HP increase for the run."},
    {level:"advanced",section:"Combat",title:"Weapon Traits",controls:["Level up weapons by killing"],desc:"Each weapon has traits that level up through use. Higher trait levels = permanent unlocks.",why:"Leveling traits permanently upgrades the weapon pool. Prioritize unlocking good traits."},
    {level:"advanced",section:"Survival",title:"Adrenaline Management",controls:["Kill enemies without getting hit"],desc:"Adrenaline builds at 3, 5, 7, etc kills without damage. Each level gives a bonus.",why:"Level 5 adrenaline gives massive benefits. Play carefully to maintain your streak."},
    {level:"advanced",section:"Survival",title:"Malignancy Risk",controls:["Malignant items have curses"],desc:"Picking up malignant items may add a suit malfunction (debuff) that requires specific actions to remove.",why:"Sometimes the risk is worth it. A malignant large Silphium early on can carry a run."},
    {level:"expert",section:"Combat",title:"Bullet Hell Patterns",controls:["Focus on gaps, not projectiles"],desc:"Watch the gaps between projectiles, not the projectiles themselves.",why:"Your eyes track movement naturally. Focusing on gaps makes dodging intuitive."},
    {level:"expert",section:"Strategy",title:"Optimal Route",controls:["Biome 1 → 3 → 4 → 6 for fastest clear"],desc:"Once you unlock shortcuts, skip early biomes and push forward.",why:"Later biomes have better weapons. Spending too long in easy biomes wastes time."},
    {level:"expert",section:"Combat",title:"Rotgland Lobber Abuse",controls:["One shot DoT → move on"],desc:"The Rotgland Lobber applies damage over time. Shoot once and let it tick.",why:"Most efficient weapon in the game. One shot per enemy, let DoT do the work while you dodge."}
  ]
},
{
  id:"bloodborne",name:"Bloodborne",genre:"Action RPG / Souls-like",category:"action",icon:"🩸",color:"#4a0000",
  desc:"Hunt beasts in Yharnam. Rally system, trick weapons, and aggressive FROM Software combat.",
  tags:["Action","RPG","Souls-like","PS Exclusive"],
  tips:[
    {level:"beginner",section:"Combat",title:"Attack",controls:["R1 (light) / R2 (heavy)"],desc:"R1 for quick attacks, R2 for charged heavy attacks.",why:"Bloodborne rewards aggression over defense. Attack constantly."},
    {level:"beginner",section:"Combat",title:"Dodge / Quickstep",controls:["○"],desc:"Press Circle to dodge. Quickstep while locked on.",why:"Quickstep has generous I-frames. Dodge INTO attacks for counter windows."},
    {level:"beginner",section:"Combat",title:"Heal (Blood Vial)",controls:["△"],desc:"Press Triangle to use a Blood Vial.",why:"You carry 20 max. Don't hoard them — you farm more. Heal aggressively."},
    {level:"beginner",section:"Combat",title:"Gun / Parry",controls:["L2"],desc:"Press L2 to fire your gun. Timing it with an enemy attack triggers a parry.",why:"Gun parry into visceral attack is THE core mechanic. Master the timing."},
    {level:"beginner",section:"Combat",title:"Lock On",controls:["R3"],desc:"Click right stick to lock on.",why:"Lock on for humanoid enemies. Unlock for large beasts where the camera struggles."},
    {level:"intermediate",section:"Combat",title:"Rally System",controls:["Attack after taking damage"],desc:"After being hit, you have a brief window where attacking recovers the lost HP.",why:"This is why Bloodborne is aggressive. You HEAL by attacking. Never retreat after getting hit — attack."},
    {level:"intermediate",section:"Weapons",title:"Trick Weapon Transform",controls:["L1"],desc:"Press L1 to transform your weapon between two forms.",why:"Each weapon has two movesets. Transform attacks (L1 mid-combo) are often the strongest moves."},
    {level:"intermediate",section:"Combat",title:"Visceral Attack",controls:["R1 after successful gun parry"],desc:"After a gun parry staggers the enemy, press R1 up close for a visceral attack.",why:"Massive damage that scales with Skill stat. The most efficient damage in the game."},
    {level:"intermediate",section:"Combat",title:"Charged R2 → Backstab",controls:["Charged R2 from behind → R1"],desc:"Fully charge R2 behind an enemy for a stagger, then R1 for a visceral.",why:"Same visceral damage as a parry, but doesn't require timing a gun shot."},
    {level:"intermediate",section:"Items",title:"Pebble / Throwing Knife",controls:["□ (use item)"],desc:"Use throwing items to pull single enemies from groups.",why:"Fighting one enemy is always easier than three. Pull them out of groups carefully."},
    {level:"advanced",section:"Combat",title:"Transform Attack Combos",controls:["R1 → L1 (mid-combo)"],desc:"During a combo, press L1 to transform attack. It's a unique animation with bonus damage.",why:"Transform attacks are usually the strongest single hits. Weave them into every combo."},
    {level:"advanced",section:"Combat",title:"Dodge → Charged R2",controls:["Dodge behind → hold R2"],desc:"Dodge behind an enemy during their attack and begin charging R2 immediately.",why:"Their recovery animation gives you time to fully charge. Leads to backstab visceral."},
    {level:"advanced",section:"Build",title:"Quality vs Skill vs Arcane",controls:["Level up appropriately"],desc:"Pick a build: Strength (big weapons), Skill (fast weapons + viscerals), Arcane (magic tools).",why:"Spread stats = weak character. Focus your build for maximum effectiveness."},
    {level:"expert",section:"Combat",title:"Parry Windows by Enemy",controls:["Learn each enemy's parry window"],desc:"Every enemy has different parry timing. Learn the specific frames for each.",why:"Some enemies are parryable on the wind-up, others at the swing. Each is different."},
    {level:"expert",section:"Combat",title:"Rally Abuse on Bosses",controls:["Trade hits intentionally"],desc:"Intentionally trade hits with a boss, then rally back the HP with aggressive attacks.",why:"Against bosses with long recovery, you can heal more than you lost through rally."},
    {level:"expert",section:"Build",title:"Arcane Build",controls:["Level Arcane → use Hunter Tools"],desc:"50+ Arcane with tools like Executioner's Gloves and A Call Beyond.",why:"Arcane builds have infinite ranged damage that destroys every boss from safety."}
  ]
},
{
  id:"dmc5",name:"Devil May Cry 5",genre:"Action / Hack & Slash",category:"action",icon:"😈",color:"#8b0000",
  desc:"SSS-rank stylish action. Dante, Nero, and V with deep combo systems.",
  tags:["Action","Hack & Slash","Stylish","Combo"],
  tips:[
    {level:"beginner",section:"Combat",title:"Melee Attack",controls:["△"],desc:"Press Triangle for melee combos.",why:"The base of your combo. Timing the button presses changes the combo string."},
    {level:"beginner",section:"Combat",title:"Ranged Attack",controls:["□"],desc:"Press Square to shoot your gun.",why:"Guns keep combos alive in the air and at range. Style points for mixing them in."},
    {level:"beginner",section:"Combat",title:"Jump",controls:["X"],desc:"Press X to jump. Can double jump.",why:"Air combos are a huge part of DMC. Launch enemies and keep them airborne."},
    {level:"beginner",section:"Combat",title:"Lock On",controls:["R1 (hold)"],desc:"Hold R1 to lock onto an enemy.",why:"Lock-on changes your move inputs. R1 + back + Triangle = different move than just Triangle."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["R1 + ○/X + direction"],desc:"Lock on and press jump/action + direction to dodge roll or table hop.",why:"Dodging in DMC is tied to lock-on. Practice the different dodge types."},
    {level:"beginner",section:"Nero",title:"Exceed (Nero)",controls:["L2 during sword swing"],desc:"Press L2 at the exact moment Nero's sword connects to Exceed-charge it.",why:"Exceeded attacks deal WAY more damage. Max-Act (perfect timing) triples damage."},
    {level:"intermediate",section:"Nero",title:"Devil Breaker (Nero)",controls:["○"],desc:"Press Circle to use Nero's equipped mechanical arm ability.",why:"Each arm has a unique powerful attack. Swap arms frequently for variety."},
    {level:"intermediate",section:"Nero",title:"Buster Arm Grab (Nero)",controls:["○ on staggered enemy"],desc:"Use Buster arm on a staggered enemy for a huge grab attack.",why:"Buster does massive damage. One of the highest single hits in the game."},
    {level:"intermediate",section:"Dante",title:"Style Switching (Dante)",controls:["D-Pad directions"],desc:"Up = Trickster, Right = Swordmaster, Down = Royal Guard, Left = Gunslinger.",why:"Real-time style switching is what makes Dante legendary. Each style adds new moves."},
    {level:"intermediate",section:"Dante",title:"Weapon Switch (Dante)",controls:["L2/R2 cycle through melee/ranged"],desc:"L2 cycles ranged weapons, R2 cycles melee weapons.",why:"Switching weapons mid-combo extends combos and boosts style rank."},
    {level:"intermediate",section:"Style",title:"Style Rank",controls:["Use varied attacks"],desc:"Your style rank (D through SSS) goes up with varied combos and drops when hit.",why:"Higher style ranks give more red orbs and look amazing. Never repeat the same move."},
    {level:"advanced",section:"Dante",title:"Royal Guard",controls:["D-Pad down → ○ to release / □ to guard"],desc:"Switch to Royal Guard, press Square to parry. Release stored energy with Circle.",why:"Perfect Royal Guards store massive energy. Release at SSS rank for insane damage."},
    {level:"advanced",section:"Dante",title:"Jump Cancel (JC)",controls:["Attack → jump → attack → jump in air"],desc:"Attack, enemy step (jump off enemy), attack again to loop infinite air combos.",why:"Jump canceling is the core of high-level DMC play. Infinite air time = infinite combos."},
    {level:"advanced",section:"Combat",title:"Launcher → Air Combo",controls:["R1 + back + △ → air chain"],desc:"Lock on, hold back and press melee to launch. Follow into the air for a full air combo.",why:"Air combos give more style points and enemies can't fight back while airborne."},
    {level:"expert",section:"Nero",title:"Max-Act Loop",controls:["Exceed on every single swing"],desc:"Perfect Exceed timing on every swing for constant triple damage.",why:"Max-Act every hit turns Nero into a damage machine. Requires frame-perfect timing."},
    {level:"expert",section:"Dante",title:"Style Switch Combos",controls:["Trickster → Swordmaster → Royal Guard in one combo"],desc:"Switch between 3-4 styles within a single combo string.",why:"The highest expression of DMC combat. Each style adds unique moves to the chain."},
    {level:"expert",section:"Style",title:"SSS Rank Maintenance",controls:["Never stop attacking, never get hit, always vary"],desc:"Mix melee, ranged, styles, weapons, and air/ground seamlessly.",why:"Maintaining SSS for entire fights is the ultimate DMC challenge and reward."}
  ]
},
{
  id:"nioh2",name:"Nioh 2",genre:"Action RPG / Souls-like",category:"action",icon:"👹",color:"#5a0000",
  desc:"Yokai-infused samurai combat. Three stances, Ki Pulse, Burst Counter, and deep builds.",
  tags:["Action","RPG","Souls-like","Yokai"],
  tips:[
    {level:"beginner",section:"Combat",title:"Attack",controls:["□ (quick) / △ (strong)"],desc:"Square for quick attacks, Triangle for strong attacks.",why:"Quick attacks are safe, strong attacks deal more Ki damage to enemies."},
    {level:"beginner",section:"Combat",title:"Block",controls:["L1"],desc:"Hold L1 to block incoming attacks.",why:"Blocking drains Ki. If Ki runs out, your guard breaks."},
    {level:"beginner",section:"Combat",title:"Dodge",controls:["○"],desc:"Press Circle to dodge. Dodge type changes with stance.",why:"Low stance = fast dodge. Mid = balanced. High = slow but more I-frames."},
    {level:"beginner",section:"Stances",title:"Switch Stances",controls:["R1 + □/△/X"],desc:"R1+Square = High, R1+Triangle = Mid, R1+X = Low.",why:"High = damage, Mid = balanced/blocking, Low = speed/dodging. Switch constantly."},
    {level:"beginner",section:"Combat",title:"Ki Pulse",controls:["R1 after attacking"],desc:"Press R1 after an attack combo to recover Ki (stamina).",why:"Ki Pulse is THE core mechanic. Without it you run out of stamina and die. Always pulse."},
    {level:"intermediate",section:"Combat",title:"Burst Counter",controls:["R2 + ○ when enemy glows red"],desc:"When an enemy glows red for a burst attack, press R2+Circle to counter it.",why:"Burst Counters deal massive Ki damage and prevent devastating attacks. Essential against Yokai."},
    {level:"intermediate",section:"Combat",title:"Yokai Abilities",controls:["R2 + □ or △"],desc:"Use equipped Yokai soul cores for powerful special attacks.",why:"Yokai abilities have unique effects — some grab, some AoE, some buff. They use Anima, not Ki."},
    {level:"intermediate",section:"Combat",title:"Yokai Shift",controls:["△ + ○ when Amrita gauge full"],desc:"Transform into your Yokai form for temporary super mode.",why:"Massive damage and near-invincibility. Save for boss phases or emergencies."},
    {level:"intermediate",section:"Stances",title:"Flux (Stance Switch on Ki Pulse)",controls:["R1 + stance button during Ki Pulse"],desc:"Switch stances during your Ki Pulse for bonus Ki recovery.",why:"Flux I = bonus Ki. Flux II (switch twice) = even more Ki. Dramatically increases your sustain."},
    {level:"intermediate",section:"Combat",title:"Ninjutsu & Onmyo",controls:["D-Pad shortcuts"],desc:"Use shuriken, bombs, elemental talismans, and buffs.",why:"Buffs and debuffs multiply your damage. Sloth talisman makes bosses trivial."},
    {level:"advanced",section:"Combat",title:"Active Skills",controls:["Specific inputs per weapon"],desc:"Each weapon has active skills — unique moves mapped to specific inputs in each stance.",why:"Active skills are your best moves. Learn 2-3 per stance for your weapon."},
    {level:"advanced",section:"Combat",title:"Grapple",controls:["△ + ○ on Ki-broken enemy"],desc:"When an enemy's Ki is depleted, grapple them for massive damage.",why:"Grapples deal 5-10x normal damage. The reward for aggressive Ki pressure."},
    {level:"advanced",section:"Build",title:"Set Bonuses",controls:["Equip matching armor pieces"],desc:"Wearing multiple pieces of the same set grants powerful bonuses.",why:"Set bonuses define your build. Grace of Susano for melee, Onmyo sets for magic, etc."},
    {level:"expert",section:"Combat",title:"Zero Ki Combat",controls:["Deplete enemy Ki → combo → grapple → repeat"],desc:"Keep enemies at zero Ki for continuous grapples and combos.",why:"Top players never let bosses recover Ki. Permanent stagger loop = boss can never attack."},
    {level:"expert",section:"Build",title:"Anima Bonus Builds",controls:["Stack Anima generation"],desc:"Build around Anima generation to spam Yokai abilities constantly.",why:"Some soul cores are game-breakingly powerful. Infinite spam = infinite damage."}
  ]
}
]);
