registerGames([
{id:"cod",name:"Call of Duty (Latest)",genre:"FPS / Shooter",category:"shooter",icon:"🎯",color:"#2a2a2a",
desc:"Multiplayer, Warzone, and Zombies. Fast-paced FPS action across all modes.",tags:["FPS","Multiplayer","Battle Royale","Zombies"],
tips:[
{level:"beginner",section:"Combat",title:"Aim Down Sights",controls:["L2"],desc:"Hold L2 to ADS for better accuracy.",why:"Hip-fire inaccurate at range. ADS for anything beyond close."},
{level:"beginner",section:"Movement",title:"Sprint",controls:["L3"],desc:"Click left stick to sprint.",why:"Movement speed wins gunfights."},
{level:"beginner",section:"Movement",title:"Slide",controls:["○ while sprinting"],desc:"Circle while sprinting to slide.",why:"Slides under crosshairs. Get into cover or around corners."},
{level:"beginner",section:"Movement",title:"Crouch / Prone",controls:["○ (tap/hold)"],desc:"Tap for crouch, hold for prone.",why:"Lower profile = harder to hit."},
{level:"beginner",section:"Combat",title:"Reload",controls:["□"],desc:"Square to reload.",why:"Reload behind cover. Never in the open."},
{level:"beginner",section:"Combat",title:"Equipment",controls:["L1 (tactical) / R1 (lethal)"],desc:"Stun/flash grenades and frag/semtex.",why:"Pre-thrown stun wins fights before they start."},
{level:"beginner",section:"Combat",title:"Switch Weapon",controls:["△"],desc:"Triangle to swap weapons.",why:"Switching is faster than reloading in emergencies."},
{level:"intermediate",section:"Movement",title:"Mount",controls:["L2 near edge → L3"],desc:"Mount weapon on surfaces for reduced recoil.",why:"Zero recoil while mounted. Great for holding angles."},
{level:"intermediate",section:"Combat",title:"Pre-Aim Corners",controls:["L2 before rounding corners"],desc:"ADS before turning corners.",why:"Already-aiming player wins 90% of corner fights."},
{level:"intermediate",section:"Warzone",title:"Plate Up",controls:["Hold △"],desc:"Apply armor plates.",why:"Always be fully plated. Plates = extra health."},
{level:"intermediate",section:"Warzone",title:"Ping",controls:["L1"],desc:"Ping enemies and items for your team.",why:"Communication without a mic. Ping everything useful."},
{level:"intermediate",section:"Combat",title:"Aim for Upper Chest",controls:["Crosshair placement"],desc:"Keep crosshair at upper chest height while moving.",why:"Upper chest recoil pulls to head for headshot bonus."},
{level:"advanced",section:"Movement",title:"Slide Cancel",controls:["Slide → crouch → sprint → slide"],desc:"Cancel slide recovery for continuous fast movement.",why:"Maintains sprint speed while breaking aim assist tracking."},
{level:"advanced",section:"Movement",title:"Camera Breaking",controls:["Sprint past corner → snap aim"],desc:"Sprint past a corner and snap onto enemies.",why:"Camera angle advantage — you see them before they see you."},
{level:"advanced",section:"Movement",title:"Drop Shot",controls:["R3 while shooting"],desc:"Go prone while continuing to fire.",why:"Hitbox drops instantly. Enemy loses aim while you keep shooting."},
{level:"advanced",section:"Aiming",title:"Centering",controls:["Pre-aim head height always"],desc:"Always keep crosshair at head height on common angles.",why:"#1 skill gap. Minimizes the distance you need to flick to target."},
{level:"expert",section:"Movement",title:"Bunny Hop Chain",controls:["Jump → slide → cancel → jump"],desc:"Chain jumps and slides for unpredictable movement.",why:"Nearly impossible to track. Top movement tech."},
{level:"expert",section:"Strategy",title:"Spawn Knowledge",controls:["Learn spawn logic per map"],desc:"Understand where enemies will spawn based on your team's position.",why:"Spawn knowledge lets you predict where enemies come from before they appear."}
]},
{id:"apex",name:"Apex Legends",genre:"FPS / Battle Royale",category:"shooter",icon:"🔺",color:"#cc0000",
desc:"Legend abilities, movement mastery, and squad tactics in the Outlands.",tags:["FPS","Battle Royale","Multiplayer","Hero Shooter"],
tips:[
{level:"beginner",section:"Combat",title:"Aim & Shoot",controls:["L2 + R2"],desc:"Standard ADS and fire.",why:"Hip-fire is viable in Apex up close. ADS for medium/long range."},
{level:"beginner",section:"Movement",title:"Slide",controls:["○ while sprinting"],desc:"Slide for speed and smaller hitbox.",why:"Sliding is fundamental to Apex movement. Slide everywhere."},
{level:"beginner",section:"Movement",title:"Sprint",controls:["L3"],desc:"Click left stick to sprint. Can't shoot while sprinting.",why:"Holster weapon (hold △) for faster sprint speed."},
{level:"beginner",section:"Abilities",title:"Tactical Ability",controls:["L1"],desc:"Use your Legend's tactical ability.",why:"Each Legend has a unique tactical. Learn yours — it defines your playstyle."},
{level:"beginner",section:"Abilities",title:"Ultimate Ability",controls:["L1 + R1"],desc:"Activate your ultimate when charged.",why:"Ultimates can win fights. Don't hoard them — they recharge."},
{level:"beginner",section:"Teamwork",title:"Ping",controls:["R1"],desc:"Ping locations, enemies, items, and danger.",why:"The best communication tool. Ping EVERYTHING for your squad."},
{level:"beginner",section:"Combat",title:"Swap Weapon",controls:["△"],desc:"Triangle to swap between your two weapons.",why:"Swap to second weapon instead of reloading in a fight."},
{level:"intermediate",section:"Movement",title:"Slide Jump",controls:["Sprint → ○ → X"],desc:"Sprint, slide, then immediately jump for a long slide-jump.",why:"Covers more distance and maintains momentum. Core movement."},
{level:"intermediate",section:"Movement",title:"Wall Jump",controls:["Slide jump at wall → jump off"],desc:"Jump at a wall and jump again to spring off it.",why:"Changes your trajectory mid-air. Confuses enemy aim."},
{level:"intermediate",section:"Combat",title:"Strafe While Shooting",controls:["Left Stick side-to-side + R2"],desc:"Move side to side while shooting to make yourself harder to hit.",why:"Standing still = easy target. AD strafe is mandatory."},
{level:"intermediate",section:"Combat",title:"Shield Swap",controls:["Death box → swap armor"],desc:"Swap your cracked armor for a full one from a death box.",why:"Instant full shields. Faster than using shield cells."},
{level:"intermediate",section:"Combat",title:"Armor Types",controls:["White → Blue → Purple → Gold → Red"],desc:"Higher tier = more HP. Gold has fast heal. Red is max.",why:"Prioritize armor upgrades. Red Evo has 125 shield HP."},
{level:"advanced",section:"Movement",title:"Bunny Hop Heal",controls:["Slide → jump → heal → jump → jump"],desc:"Slide, then bunny hop while using a healing item to maintain speed.",why:"Heal while moving instead of standing still. Huge survival boost."},
{level:"advanced",section:"Movement",title:"Tap Strafe",controls:["Slide jump → scroll/tap forward rapidly"],desc:"Redirect momentum mid-air by rapidly tapping forward.",why:"Instant 90-degree turns in the air. Extremely hard to track."},
{level:"advanced",section:"Combat",title:"Peeker's Advantage",controls:["Wide swing from cover"],desc:"Swing wide out of cover to see the enemy before they see you.",why:"Netcode favors the aggressor. Peeking = information advantage."},
{level:"advanced",section:"Strategy",title:"Ring Rotation",controls:["Rotate early with good position"],desc:"Move to the next ring early and hold a strong position.",why:"Teams caught rotating late get third-partied and die."},
{level:"expert",section:"Movement",title:"Superglide",controls:["Climb → crouch + jump at ledge top"],desc:"At the exact top of a mantle, press crouch and jump simultaneously for a speed boost.",why:"Massive speed burst. Chain superglides for the fastest ground movement possible."},
{level:"expert",section:"Strategy",title:"Third Party Timing",controls:["Push after hearing gunfight end"],desc:"Wait for a fight to finish (one team knocked), then push the weakened winners.",why:"The winning team has cracked shields and low health. Free kills with good timing."}
]},
{id:"fortnite",name:"Fortnite",genre:"Battle Royale / Shooter",category:"shooter",icon:"🏗️",color:"#7b2ff2",
desc:"Build, shoot, and survive. Battle Royale with building and no-build modes.",tags:["Battle Royale","Building","Multiplayer","Cross-Platform"],
tips:[
{level:"beginner",section:"Combat",title:"Aim & Shoot",controls:["L2 + R2"],desc:"Standard aim and shoot.",why:"Bloom means bullets spread randomly. Crouch and ADS for tighter bloom."},
{level:"beginner",section:"Movement",title:"Sprint",controls:["L3 (toggle)"],desc:"Toggle sprint on.",why:"Always be sprinting when not in combat."},
{level:"beginner",section:"Movement",title:"Jump",controls:["X"],desc:"Jump to avoid shots and navigate terrain.",why:"Jump shots make you harder to hit but less accurate."},
{level:"beginner",section:"Building",title:"Build Wall",controls:["○ (switch to build) → R2"],desc:"Switch to build mode and place a wall.",why:"Walls are your instant cover. One button saves your life."},
{level:"beginner",section:"Building",title:"Build Ramp",controls:["Build mode → □"],desc:"Place a ramp for height advantage.",why:"High ground = shooting advantage. Ramp up immediately in fights."},
{level:"beginner",section:"Combat",title:"Harvest Materials",controls:["R2 on objects with pickaxe"],desc:"Hit trees, rocks, buildings for materials.",why:"You need materials to build. Farm 500+ of each before fights."},
{level:"beginner",section:"Basics",title:"Inventory",controls:["D-Pad / touchpad"],desc:"Manage your 5 inventory slots.",why:"Optimize your loadout: AR + Shotgun + Heal + Utility + Flex."},
{level:"intermediate",section:"Building",title:"90s",controls:["Wall → ramp → turn 90° → repeat"],desc:"Place wall+ramp, turn 90 degrees, repeat to build a tower fast.",why:"The fundamental build technique. Gains height quickly in build fights."},
{level:"intermediate",section:"Building",title:"Box Up",controls:["4 walls + floor + roof"],desc:"Build a 1x1 box around yourself instantly.",why:"Instant protection. Reset the fight, heal, and re-engage."},
{level:"intermediate",section:"Combat",title:"Shotgun Edit Play",controls:["Edit wall → shoot → reset edit"],desc:"Edit a window in your wall, shotgun the enemy, close the edit.",why:"Peak and shoot without full exposure. The core of box fighting."},
{level:"intermediate",section:"No Build",title:"Sprint Slide",controls:["Sprint → ○"],desc:"Slide for speed and lower profile.",why:"In no-build mode, sliding is your best defensive movement."},
{level:"intermediate",section:"No Build",title:"Cover Usage",controls:["Use natural terrain"],desc:"Without building, use rocks, trees, and buildings as cover.",why:"Natural cover replaces building. Position near cover always."},
{level:"advanced",section:"Building",title:"Tunneling",controls:["Floor + wall + ramp while moving"],desc:"Build a protected tunnel as you move through the zone.",why:"Rotates safely through open ground in competitive play."},
{level:"advanced",section:"Building",title:"Piece Control",controls:["Place builds around enemy"],desc:"Surround the enemy with YOUR builds so they can't edit.",why:"Your builds = your edits. Controlling the pieces controls the fight."},
{level:"advanced",section:"Combat",title:"Right-Hand Peek",controls:["Peek from right side of cover"],desc:"Your character model exposes less when peeking right.",why:"Third-person camera favors right-side peeks. Use it always."},
{level:"expert",section:"Building",title:"Mongraal Classic",controls:["Floor + wall + edit floor + pump"],desc:"Place floor over enemy, wall, edit floor open, shotgun down.",why:"Named after the pro player. Instant high-ground retake into free shot."},
{level:"expert",section:"Strategy",title:"Storm Surge",controls:["Deal damage before zone closes"],desc:"In competitive, you must deal enough damage or take storm surge damage.",why:"Passive play gets punished. Take shots to stay above the damage threshold."}
]},
{id:"destiny2",name:"Destiny 2",genre:"FPS / Looter Shooter",category:"shooter",icon:"⚡",color:"#0a3a8b",
desc:"Space magic gunplay. Raids, PvP Crucible, subclasses, and exotic builds.",tags:["FPS","Looter","MMO","Co-op"],
tips:[
{level:"beginner",section:"Combat",title:"Shoot",controls:["R2 (hip) / L2 + R2 (ADS)"],desc:"Standard hip-fire and ADS.",why:"Hip-fire works surprisingly well in Destiny. ADS for precision."},
{level:"beginner",section:"Abilities",title:"Grenade",controls:["L1"],desc:"Throw your subclass grenade.",why:"Grenades deal massive damage and have unique effects per subclass."},
{level:"beginner",section:"Abilities",title:"Melee",controls:["R1"],desc:"Powered melee ability.",why:"Melee abilities are often more powerful than regular melees."},
{level:"beginner",section:"Abilities",title:"Class Ability",controls:["○ + ○"],desc:"Double-tap Circle for your class ability (barrier, dodge, rift).",why:"Titan barrier = cover. Warlock rift = heal/damage. Hunter dodge = reload/invis."},
{level:"beginner",section:"Abilities",title:"Super",controls:["L1 + R1 when full"],desc:"Activate your super ability.",why:"Supers are the most powerful abilities. Save for bosses or PvP clutch moments."},
{level:"beginner",section:"Movement",title:"Jump Ability",controls:["X + X"],desc:"Double jump (varies by class).",why:"Each class has unique jumps. Warlock glide, Titan lift, Hunter double/triple jump."},
{level:"intermediate",section:"Combat",title:"Weapon Types",controls:["Kinetic / Energy / Power slots"],desc:"Three weapon slots with different ammo economies.",why:"Primary ammo is infinite. Special is scarce. Heavy is rare. Plan accordingly."},
{level:"intermediate",section:"Combat",title:"Champion Mods",controls:["Equip anti-champion mods on arms"],desc:"Specific mods counter specific champion types.",why:"Champions in endgame REQUIRE the right mods. Unstoppable, Overload, Barrier."},
{level:"intermediate",section:"Build",title:"Armor Mods",controls:["Apply mods to armor slots"],desc:"Each armor piece has mod slots for stat boosts and ability mods.",why:"Mods define your build. Stack ability regeneration or damage resistance."},
{level:"intermediate",section:"Build",title:"Exotic Armor",controls:["One exotic weapon + one exotic armor max"],desc:"Exotics have unique perks. You can only equip one of each type.",why:"Your exotic choice defines your build. Choose one that synergizes with your subclass."},
{level:"intermediate",section:"Subclass",title:"Fragment & Aspect System",controls:["Customize subclass in menu"],desc:"Aspects give abilities, Fragments give passive boosts.",why:"The customization depth is massive. Look up builds for your subclass."},
{level:"advanced",section:"PvP",title:"Map Control",controls:["Control heavy ammo spawn"],desc:"Control the heavy ammo spawn point and power positions on the map.",why:"Heavy weapons (rockets, swords) dominate PvP. Deny them to enemies."},
{level:"advanced",section:"PvE",title:"Well of Radiance",controls:["Warlock super"],desc:"The most important PvE super. Places a healing/damage zone.",why:"Well of Radiance is almost mandatory for raids. Keeps the whole team alive."},
{level:"advanced",section:"Build",title:"Ability Loops",controls:["Kill → ability → kill → repeat"],desc:"Build for ability regeneration that creates infinite ability loops.",why:"The best builds never use guns. Just chain abilities endlessly."},
{level:"expert",section:"PvP",title:"Peek Shooting",controls:["Strafe out → shoot → strafe back"],desc:"Peek from cover, fire one shot, retreat.",why:"Minimizes your exposure time. Forces the enemy to react to your timing."},
{level:"expert",section:"Raids",title:"DPS Phase Optimization",controls:["Debuff → buff → heavy ammo dump"],desc:"Stack team debuffs/buffs then dump all heavy ammo during boss DPS phase.",why:"Well of Radiance + Weapons of Light + Divinity + Linear Fusions = max raid DPS."}
]},
{id:"overwatch2",name:"Overwatch 2",genre:"FPS / Hero Shooter",category:"shooter",icon:"🦸",color:"#f99e1a",
desc:"Hero-based team combat. Tanks, DPS, and Supports across objective modes.",tags:["FPS","Hero Shooter","Multiplayer","Competitive"],
tips:[
{level:"beginner",section:"Combat",title:"Primary Fire",controls:["R2"],desc:"Fire your hero's primary weapon.",why:"Every hero has a different weapon. Learn your hero's range and fire rate."},
{level:"beginner",section:"Combat",title:"Secondary Fire",controls:["L2"],desc:"Alternate fire mode (scope, charge, etc).",why:"Some heroes have vastly different secondary fires. Learn both."},
{level:"beginner",section:"Abilities",title:"Ability 1",controls:["L1"],desc:"First ability (varies by hero).",why:"Abilities define heroes more than guns. Learn cooldowns and usage."},
{level:"beginner",section:"Abilities",title:"Ability 2",controls:["R1"],desc:"Second ability.",why:"Combo abilities together for maximum impact."},
{level:"beginner",section:"Abilities",title:"Ultimate",controls:["△"],desc:"Activate your ultimate ability when charged.",why:"Ultimates win team fights. Coordinate with your team for combo ults."},
{level:"beginner",section:"Basics",title:"Reload",controls:["□"],desc:"Reload your weapon.",why:"Reload in safe moments. Getting caught reloading in a fight = death."},
{level:"intermediate",section:"Teamwork",title:"Group Up",controls:["Communication wheel"],desc:"Regroup with your team before pushing.",why:"Staggering in 1-by-1 feeds the enemy ult charge. Group up and push together."},
{level:"intermediate",section:"Teamwork",title:"Ult Tracking",controls:["Track enemy ult charge mentally"],desc:"Estimate when enemies have their ultimates ready.",why:"Knowing an enemy has Graviton ready changes how you position entirely."},
{level:"intermediate",section:"Tanks",title:"Space Creation",controls:["Push forward to make space for DPS"],desc:"Tanks exist to create space. Push forward and absorb pressure.",why:"If the tank doesn't push, DPS can't get angles and supports can't heal safely."},
{level:"intermediate",section:"Support",title:"Heal Priority",controls:["Focus heals on tanks and low-HP allies"],desc:"Heal the person most likely to die, not whoever is closest.",why:"A dead tank = a lost fight. Keep your frontline alive."},
{level:"advanced",section:"DPS",title:"Off-Angle",controls:["Attack from unexpected angles"],desc:"Don't shoot from the same angle as your team. Flank or take high ground.",why:"Cross-fire forces enemies to choose which angle to block. They can't block both."},
{level:"advanced",section:"Teamwork",title:"Ult Combos",controls:["Combo ultimates together"],desc:"Zarya Grav + Hanzo Dragonstrike, Ana Nano + Genji Blade, etc.",why:"Combo ults are exponentially stronger than individual ults."},
{level:"advanced",section:"Movement",title:"Cover Discipline",controls:["Always be near cover"],desc:"Never stand in the open. Always have cover within one step.",why:"The #1 survival tip. Open ground = instant death at higher ranks."},
{level:"expert",section:"Teamwork",title:"Ult Economy",controls:["Don't waste ults on won/lost fights"],desc:"If the fight is already won, don't ult. If it's lost, don't ult. Save for the next fight.",why:"Ult economy wins matches. Wasting ults means the next fight starts at a disadvantage."},
{level:"expert",section:"DPS",title:"Tracer Blink Management",controls:["Never use all 3 blinks"],desc:"Keep one blink as an escape. Use 2 max for aggression.",why:"A Tracer with no blinks is a dead Tracer. Always have an exit."}
]},
{id:"r6siege",name:"Rainbow Six Siege",genre:"FPS / Tactical",category:"shooter",icon:"🛡️",color:"#1a1a3a",
desc:"Tactical 5v5 with destructible environments. Operators, intel, and precision.",tags:["FPS","Tactical","Multiplayer","Competitive"],
tips:[
{level:"beginner",section:"Basics",title:"Aim & Shoot",controls:["L2 + R2"],desc:"Standard ADS. Always ADS in Siege — hip-fire is terrible.",why:"Siege requires precision. Every bullet matters. Always ADS."},
{level:"beginner",section:"Basics",title:"Lean",controls:["L1 (lean left) / R1 (lean right) while ADS"],desc:"Lean to peek around corners while minimizing exposure.",why:"Leaning exposes only your head. Standing out exposes everything."},
{level:"beginner",section:"Movement",title:"Crouch / Prone",controls:["○ / hold ○"],desc:"Tap for crouch, hold for prone. Both reduce noise.",why:"Moving while crouched is much quieter. Sound is information in Siege."},
{level:"beginner",section:"Movement",title:"Walk (Slow)",controls:["Move stick slightly"],desc:"Gentle left stick movement for silent walking.",why:"Footsteps are LOUD in Siege. Enemies hear you coming."},
{level:"beginner",section:"Gadgets",title:"Operator Gadget",controls:["L1/R1"],desc:"Use your operator's unique gadget.",why:"Gadgets define the game. Thermite's breach, Bandit's batteries, etc."},
{level:"beginner",section:"Intel",title:"Drone",controls:["Spawn drone → camera view"],desc:"Deploy your drone to scout ahead.",why:"Information wins rounds. ALWAYS drone before entering a room."},
{level:"intermediate",section:"Destruction",title:"Shoot Walls / Floors",controls:["R2 on soft surfaces"],desc:"Soft walls and floors can be shot through and destroyed.",why:"Open sightlines through walls for unexpected angles. Siege is about destruction."},
{level:"intermediate",section:"Destruction",title:"Breach Charge",controls:["Place on soft wall → detonate"],desc:"Blow open soft walls for entry or rotation.",why:"Creating your own doorways bypasses defender setup entirely."},
{level:"intermediate",section:"Defense",title:"Reinforcement",controls:["Place on walls"],desc:"Reinforce soft walls as defender to prevent breaching.",why:"Reinforce critical walls around the objective. Don't reinforce rotations."},
{level:"intermediate",section:"Intel",title:"Camera Check",controls:["D-Pad → switch cameras"],desc:"Check defender cameras and attacker drones for intel.",why:"Dead players should always be on cameras giving callouts."},
{level:"intermediate",section:"Combat",title:"Headshots",controls:["Aim for the head always"],desc:"One headshot kills regardless of weapon.",why:"This is the BIGGEST rule in Siege. Head level crosshair at ALL times."},
{level:"advanced",section:"Audio",title:"Sound Whoring",controls:["Listen for footsteps, gadgets, barricades"],desc:"Audio gives position information. Listen for everything.",why:"You can hear enemies through walls. Use headphones. Audio is your best intel."},
{level:"advanced",section:"Strategy",title:"Vertical Play",controls:["Shoot through floors/ceilings"],desc:"Attack or defend from above/below through destructible floors.",why:"Vertical play bypasses all horizontal defenses. Buck/Sledge from above is devastating."},
{level:"advanced",section:"Strategy",title:"Crossfire Setup",controls:["Two players watch the same angle from different spots"],desc:"Set up crossfires so enemies peek into two guns simultaneously.",why:"Crossfires are nearly impossible to win against. The enemy can only aim at one of you."},
{level:"expert",section:"Strategy",title:"Time Management (Attack)",controls:["Drone phase → slow push → fast execute"],desc:"Use 2:30 to gather intel, then execute in the last 30-45 seconds.",why:"Early aggression without intel gets you killed. Slow intel → fast execute."},
{level:"expert",section:"Strategy",title:"Pixel Peeks",controls:["Create tiny holes for minimal exposure angles"],desc:"Make pinholes in walls to see through while being nearly invisible.",why:"A 1-pixel line of sight gives you full intel while being essentially invisible."}
]},
{id:"doom-eternal",name:"Doom Eternal",genre:"FPS / Action",category:"shooter",icon:"💀",color:"#8b0000",
desc:"Rip and tear. Resource loop combat — chainsaw, glory kill, flame belch, repeat.",tags:["FPS","Action","Single Player","Intense"],
tips:[
{level:"beginner",section:"Combat",title:"Shoot",controls:["R2"],desc:"Fire your equipped weapon.",why:"Always be shooting. Standing still = death."},
{level:"beginner",section:"Combat",title:"Switch Weapon",controls:["L2 / weapon wheel"],desc:"L2 for quick swap, hold for wheel.",why:"Constant weapon switching is MANDATORY. No single weapon works alone."},
{level:"beginner",section:"Movement",title:"Dash",controls:["○"],desc:"Double dash for quick repositioning.",why:"Dash has I-frames. Dash through attacks."},
{level:"beginner",section:"Movement",title:"Jump",controls:["X + X (double jump)"],desc:"Double jump for platforming and combat.",why:"Air time makes you harder to hit. Stay airborne."},
{level:"beginner",section:"Resources",title:"Glory Kill",controls:["R3 on staggered enemy"],desc:"When enemies flash, melee for a glory kill that drops HP.",why:"Glory kills are your PRIMARY healing method. Low HP? Glory kill something."},
{level:"beginner",section:"Resources",title:"Chainsaw",controls:["□"],desc:"Chainsaw enemies for ammo drops.",why:"Chainsaw is your ammo factory. Out of ammo? Chainsaw a fodder demon."},
{level:"intermediate",section:"Resources",title:"Flame Belch",controls:["L1"],desc:"Flame belch makes enemies drop armor shards when damaged.",why:"Flame Belch = armor. Chainsaw = ammo. Glory Kill = health. The holy trinity."},
{level:"intermediate",section:"Combat",title:"Weapon Mods",controls:["R1 (fire mod) / R1 hold (switch mod)"],desc:"Each weapon has two mods. Switch with R1.",why:"Lock-On rockets for single targets. Micro missiles for groups. Match mod to situation."},
{level:"intermediate",section:"Combat",title:"Super Shotgun Meathook",controls:["ADS + R2 (Super Shotgun)"],desc:"ADS with Super Shotgun fires a grapple that pulls you to the enemy.",why:"Gap closer + point-blank Super Shotgun blast = massive damage."},
{level:"intermediate",section:"Combat",title:"Weak Points",controls:["Destroy specific parts"],desc:"Arachnotron turret, Mancubus arm cannons, Revenant launchers.",why:"Destroying weak points removes their most dangerous attacks."},
{level:"advanced",section:"Combat",title:"Resource Loop",controls:["Chainsaw → Flame Belch → Glory Kill cycle"],desc:"Keep all three resource tools on cooldown. You should never be low on anything.",why:"Doom Eternal is a resource management game disguised as a shooter."},
{level:"advanced",section:"Combat",title:"Ballista → SSG Quick Swap",controls:["Ballista shot → swap to SSG → meathook → SSG blast"],desc:"Instant swap between Ballista and Super Shotgun for burst combos.",why:"Highest burst DPS combo. Kills heavy demons in seconds."},
{level:"advanced",section:"Combat",title:"Ice Bomb Combos",controls:["Ice bomb → Super Shotgun group"],desc:"Freeze a group then blast them all with Super Shotgun.",why:"Frozen enemies take extra damage and can't attack."},
{level:"expert",section:"Combat",title:"Weapon Swap Combos",controls:["Rocket → Ballista → SSG → Rocket seamlessly"],desc:"Chain 3-4 weapons with zero downtime by constantly swapping.",why:"Animation canceling through weapon swaps = DPS ceiling. Master this for Nightmare difficulty."},
{level:"expert",section:"Strategy",title:"Priority Targeting",controls:["Kill Buff Totems → Archviles → Marauders"],desc:"Kill support demons before heavy demons.",why:"Buff Totems make everything unkillable. Archviles summon more. Kill them FIRST."}
]}
]);
