// PS Game Helper - Game Database
// Games updated yearly: Madden, 2K, FIFA marked with yearlyUpdate flag
const CURRENT_YEAR = new Date().getFullYear();
const NEXT_YEAR = (CURRENT_YEAR + 1).toString().slice(-2);

const GAMES = [
  {
    id: "madden",
    name: `Madden NFL ${CURRENT_YEAR}`,
    yearlyUpdate: true,
    genre: "Sports / Football",
    icon: "🏈",
    color: "#1a5e1a",
    desc: `Master every play in Madden NFL ${CURRENT_YEAR}. From basic passes to elite audibles and hot routes.`,
    tags: ["Sports", "Football", "Multiplayer", "Online"],
    tips: [
      { level: "beginner", title: "Snap the Ball", controls: ["X"], desc: "Press X to hike the ball and start the play.", why: "Everything starts here. Get comfortable with timing your snap." },
      { level: "beginner", title: "Basic Pass", controls: ["X / ○ / △ / □ / R1"], desc: "Each button corresponds to a receiver. Press to throw to that receiver.", why: "Knowing your receiver buttons lets you make quick reads." },
      { level: "beginner", title: "Sprint", controls: ["R2 (hold)"], desc: "Hold R2 to sprint with the ball carrier.", why: "Essential for breaking away on open runs and after the catch." },
      { level: "beginner", title: "Dive / Slide", controls: ["□ (dive) / L1 (slide as QB)"], desc: "Dive forward for extra yards or slide to protect your QB.", why: "Sliding prevents fumbles on QB runs. Always slide near the first down marker." },
      { level: "beginner", title: "Play Selection", controls: ["D-Pad / Left Stick"], desc: "Navigate plays in the playbook. Use D-Pad for formation tabs.", why: "Quick play selection prevents delay of game penalties." },
      { level: "beginner", title: "Tackle", controls: ["X"], desc: "Press X near a ball carrier to tackle on defense.", why: "Fundamental defensive play. Get the timing right before learning advanced moves." },
      { level: "intermediate", title: "Pump Fake", controls: ["Double-tap receiver button"], desc: "Double-tap a receiver's icon to pump fake in that direction, freezing defenders.", why: "Opens up windows when safeties bite on the fake. Great against zone coverage." },
      { level: "intermediate", title: "Playmaker", controls: ["Left Stick (pre-snap, on receiver)"], desc: "Flick the right stick toward a receiver to motion them before the snap.", why: "Pre-snap motion reveals man vs zone. If the defender follows, it's man coverage." },
      { level: "intermediate", title: "Spin Move", controls: ["○"], desc: "Press Circle while running to spin past defenders.", why: "Best used in open space, not into traffic. Beats arm tackles consistently." },
      { level: "intermediate", title: "Juke", controls: ["Right Stick (left/right)"], desc: "Flick right stick left or right to juke in that direction.", why: "More effective than spin in tight spaces. Chain with sprint for deadly combos." },
      { level: "intermediate", title: "Ball Hawk (Defense)", controls: ["△"], desc: "Hold Triangle near a thrown ball to attempt an interception.", why: "Timing is critical — too early and you'll get beat for a big play." },
      { level: "intermediate", title: "Strafe (Defense)", controls: ["L2"], desc: "Hold L2 to strafe and stay in position on defense.", why: "Keeps your defender squared up. Essential for user-controlled coverage." },
      { level: "advanced", title: "Hot Routes", controls: ["△ then receiver + route"], desc: "Press Triangle, then select a receiver and choose a new route from the menu.", why: "Audible individual receivers against specific coverages. Slants destroy man, curls beat zone." },
      { level: "advanced", title: "Audible at the Line", controls: ["□ then play"], desc: "Press Square at the line to change the entire play based on the defensive look.", why: "If you see a blitz, audible to a quick screen. Reading the defense pre-snap is what separates good from great." },
      { level: "advanced", title: "Pass Lead", controls: ["Left Stick while throwing"], desc: "Hold a direction on the left stick while pressing a receiver button to lead the pass.", why: "Leads the throw away from defenders. High pass over linebackers, low pass away from safeties." },
      { level: "advanced", title: "Precision Passing", controls: ["L2 + receiver button"], desc: "Hold L2 and use the left stick to place the ball exactly where you want.", why: "Pinpoint accuracy for tight windows. The difference between a completion and a pick." },
      { level: "advanced", title: "Defensive Adjustments", controls: ["△/○ + D-Pad"], desc: "Triangle adjusts secondary (press, shade). Circle adjusts line (spread, pinch, crash).", why: "Shade inside vs slants, outside vs outs. Pinch the line to stop the run." },
      { level: "expert", title: "ID the Mike", controls: ["R1 + select LB"], desc: "Press R1 and select which linebacker to ID as the Mike (blocking assignment).", why: "Shifts your protection scheme. Essential vs exotic blitzes — ID the rusher to pick them up." },
      { level: "expert", title: "Slide Protection", controls: ["L1 + Left Stick"], desc: "Press L1 then flick left stick left or right to slide your O-line protection.", why: "Slide protect toward the blitz side. Keeps your QB clean on obvious pressure looks." },
      { level: "expert", title: "Manual Blitz Setup", controls: ["Select defender + ○ (blitz)"], desc: "Select individual defenders and assign them to blitz, zone, or man coverage.", why: "Create custom blitz packages. Send unexpected pressure from corners or safeties to confuse the offense." },
      { level: "expert", title: "RAC Catch vs Possession", controls: ["X (RAC) / □ (Possession) / △ (Aggressive)"], desc: "Choose catch type: X for run after catch, Square for possession, Triangle for aggressive.", why: "RAC in open field, possession on sidelines/3rd down, aggressive in the end zone. Wrong choice = dropped balls." }
    ]
  },
  {
    id: "nba2k",
    name: `NBA 2K${NEXT_YEAR}`,
    yearlyUpdate: true,
    genre: "Sports / Basketball",
    icon: "🏀",
    color: "#c44b16",
    desc: `Dominate the court in NBA 2K${NEXT_YEAR}. From basic shots to advanced dribble combos.`,
    tags: ["Sports", "Basketball", "Multiplayer", "MyCareer"],
    tips: [
      { level: "beginner", title: "Shoot", controls: ["□ or Right Stick up"], desc: "Press Square or pull the right stick down then release to shoot. Green the meter for a perfect release.", why: "Shooting is fundamental. Practice the timing in MyCourt until it's muscle memory." },
      { level: "beginner", title: "Pass", controls: ["X"], desc: "Press X to pass to the nearest teammate, or use the icon passing with the receiver buttons.", why: "Good passing creates open shots. Always look for the extra pass." },
      { level: "beginner", title: "Sprint", controls: ["R2"], desc: "Hold R2 to sprint. Drains stamina faster.", why: "Don't hold sprint 100% of the time — tired players miss shots and play worse defense." },
      { level: "beginner", title: "Call for Screen", controls: ["L1"], desc: "Press L1 to call for a pick and roll.", why: "The pick and roll is the foundation of NBA offense. Use it to create mismatches." },
      { level: "beginner", title: "Block / Contest", controls: ["△"], desc: "Press Triangle near a shooter to contest or block.", why: "Even without blocking, a good contest drops their shooting percentage dramatically." },
      { level: "beginner", title: "Steal", controls: ["□"], desc: "Press Square on defense to reach for a steal.", why: "Don't spam it — mistimed steals cause reach-in fouls. Use when the ball is exposed." },
      { level: "intermediate", title: "Euro Step", controls: ["R2 + Right Stick (left then right while driving)"], desc: "While driving, move the right stick to the off-hand side to Euro step around defenders.", why: "Avoids charge calls and gets around shot blockers. Elite finishing move." },
      { level: "intermediate", title: "Alley-Oop", controls: ["Double-tap △"], desc: "Double tap Triangle while a teammate is cutting to the basket for an alley-oop.", why: "High success rate with athletic finishers. Look for lob threats on the fast break." },
      { level: "intermediate", title: "Post Up", controls: ["L2 (hold near basket)"], desc: "Hold L2 near the basket to back down your defender in the post.", why: "Dominant with big men. Opens up hooks, fades, drop steps, and kick-outs." },
      { level: "intermediate", title: "Icon Switch (Defense)", controls: ["R1 + player icon"], desc: "Press R1 then the icon of the player you want to control.", why: "Switch to the best defender or to the player guarding the ball handler." },
      { level: "intermediate", title: "Bounce Pass", controls: ["○"], desc: "Press Circle for a bounce pass — harder to intercept in traffic.", why: "Bounce passes go under defenders' hands. Essential for feeding the post." },
      { level: "intermediate", title: "Pump Fake", controls: ["□ (tap quickly)"], desc: "Quick tap Square to pump fake and get the defender in the air.", why: "Draw fouls and create open layups. Most effective in the mid-range." },
      { level: "advanced", title: "Dribble Combos", controls: ["Right Stick combos"], desc: "Chain right stick flicks for crossovers, behind-the-back, and through-the-legs moves.", why: "Creates separation from defenders. Each combo has different speed and effectiveness ratings." },
      { level: "advanced", title: "Pick and Fade", controls: ["L1 then R1"], desc: "Call a screen with L1, then press R1 to make the screener fade to the perimeter instead of rolling.", why: "Destroys drop coverage. If the big can shoot, the pick and fade is devastating." },
      { level: "advanced", title: "Flashy Pass", controls: ["Double-tap ○"], desc: "Double tap Circle for a flashy pass — faster delivery but riskier.", why: "Gets the ball there quicker in tight windows. The speed boost can be the difference." },
      { level: "advanced", title: "Shot Cancel", controls: ["□ then ○ quickly"], desc: "Start a shot animation then press Circle to cancel it.", why: "Bait defenders into jumping, then drive past them. Elite footwork tool." },
      { level: "advanced", title: "Defensive Settings", controls: ["D-Pad left → settings"], desc: "Access team defensive settings: on-ball pressure, help defense, switch rules.", why: "Set tight on-ball vs shooters, go over/under screens correctly. Team settings win games." },
      { level: "expert", title: "Speed Boost", controls: ["Right Stick flick + R2"], desc: "Flick the right stick for a size-up then immediately hold R2 to trigger a speed boost out of the move.", why: "Creates instant separation. Requires high ball handle rating. The foundation of elite iso play." },
      { level: "expert", title: "Snatchback", controls: ["Right Stick down while moving"], desc: "Pull the right stick back while dribbling to snatch the ball back quickly.", why: "Creates space for a pull-up jumper. Deadly from three when combined with quick release badges." },
      { level: "expert", title: "Manual Cut (Off-Ball)", controls: ["Hold ○ + Left Stick toward basket"], desc: "Off-ball, hold Circle and drive toward the basket for a manual cut.", why: "AI cuts are predictable. Manual cuts catch the defense sleeping for easy baskets." },
      { level: "expert", title: "Rim Protector Timing", controls: ["△ (hold for timing)"], desc: "Hold Triangle and release at the apex of the shooter's jump for perfect block timing.", why: "Don't just mash Triangle. Timed blocks activate chase-down and pin animations." }
    ]
  },
  {
    id: "fc",
    name: `EA Sports FC ${CURRENT_YEAR}`,
    yearlyUpdate: true,
    genre: "Sports / Soccer",
    icon: "⚽",
    color: "#1a6b3c",
    desc: `Previously FIFA. Master skill moves, set pieces, and tactical defending in EA FC ${CURRENT_YEAR}.`,
    tags: ["Sports", "Soccer", "Ultimate Team", "Multiplayer"],
    tips: [
      { level: "beginner", title: "Pass", controls: ["X"], desc: "Press X to make a ground pass to the nearest teammate.", why: "Short passing builds possession. Accuracy drops with power — tap for short, hold for long." },
      { level: "beginner", title: "Shoot", controls: ["○"], desc: "Press Circle to shoot. Hold longer for more power.", why: "Aim for far post in most situations. 2-3 bars of power from inside the box is the sweet spot." },
      { level: "beginner", title: "Through Ball", controls: ["△"], desc: "Press Triangle to play a through ball into space for a runner.", why: "The most dangerous pass in the game. Time it when your striker starts their run." },
      { level: "beginner", title: "Sprint", controls: ["R2"], desc: "Hold R2 to sprint with the ball.", why: "Sprinting reduces ball control. Only sprint in open space, not when dribbling in tight areas." },
      { level: "beginner", title: "Switch Player", controls: ["L1"], desc: "Press L1 to switch to another defender.", why: "Don't chase with one defender. Switch to cut passing lanes instead." },
      { level: "beginner", title: "Tackle", controls: ["○"], desc: "Press Circle to standing tackle when near the ball carrier.", why: "Time your tackles — mistimed ones give away fouls in dangerous areas." },
      { level: "intermediate", title: "Driven Pass", controls: ["R1 + X"], desc: "Press R1 and X together for a fast, low driven pass.", why: "Cuts through traffic much faster than a normal pass. Essential for quick counters." },
      { level: "intermediate", title: "Finesse Shot", controls: ["R1 + ○"], desc: "Hold R1 while shooting for a curling finesse shot.", why: "Deadly from the edge of the box, especially on the player's strong foot curling to far post." },
      { level: "intermediate", title: "Ball Roll", controls: ["Right Stick (hold sideways)"], desc: "Hold the right stick left or right to roll the ball past a defender.", why: "Simple but incredibly effective. Creates space in tight areas without losing the ball." },
      { level: "intermediate", title: "Jockey (Defense)", controls: ["L2"], desc: "Hold L2 to jockey — stay goal-side and track the attacker.", why: "Don't dive in. Jockeying forces the attacker to make the first move. Patience wins." },
      { level: "intermediate", title: "Lob Through Ball", controls: ["L1 + △"], desc: "Press L1 + Triangle for an aerial through ball over the defense.", why: "Exploits high defensive lines. Perfect for pacey wingers making diagonal runs." },
      { level: "intermediate", title: "Fake Shot", controls: ["○ then X (quickly)"], desc: "Start a shot then quickly press X to cancel into a fake shot.", why: "Sends the goalkeeper and defenders the wrong way. One of the most versatile skill moves." },
      { level: "advanced", title: "Timed Finishing", controls: ["○ then ○ (green timing)"], desc: "Press shoot, then press it again just as your player strikes the ball for a power boost.", why: "Green timed shots are significantly more accurate and powerful. Red timing makes it worse though." },
      { level: "advanced", title: "Skill Moves: Elastico", controls: ["Right Stick: → then ← quickly (4★+)"], desc: "Flick right stick from ball-side to off-side for an Elastico. Requires 4-star skill moves.", why: "One of the best 1v1 skill moves. Changes direction instantly and wrong-foots defenders." },
      { level: "advanced", title: "Manual Switching", controls: ["Right Stick flick"], desc: "Flick the right stick toward the player you want to switch to for precise control.", why: "L1 switching is random. Right stick switching lets you pick exactly who you control." },
      { level: "advanced", title: "Tactical Sprint", controls: ["R2 double-tap"], desc: "Double-tap R2 to enter an explosive sprint burst.", why: "Knockes the ball ahead for a burst of speed. Best used in open space on the counter." },
      { level: "advanced", title: "Player Lock", controls: ["L3 + R3"], desc: "Click both sticks to lock onto your current player and make manual off-ball runs.", why: "Make your own runs instead of relying on AI. Create space that the CPU would never find." },
      { level: "expert", title: "Trivela Shot", controls: ["L2 + ○ (outside foot angle)"], desc: "Use L2 + shoot when at an angle to hit a trivela (outside of the foot) shot.", why: "Unpredictable trajectory that keepers can't read. Devastating with players who have the trait." },
      { level: "expert", title: "Directional Nutmeg", controls: ["L1 + R1 + Right Stick"], desc: "Hold L1+R1 and flick right stick toward defender to attempt a nutmeg.", why: "If it connects, the defender is completely beaten. High risk but game-changing in the box." },
      { level: "expert", title: "Custom Tactics Mid-Game", controls: ["D-Pad up/down for preset tactics"], desc: "Set up multiple tactical presets and switch between them with the D-Pad during gameplay.", why: "Switch from defensive to ultra-attacking without pausing. React to game state in real-time." },
      { level: "expert", title: "Canceled Skill Moves", controls: ["L2 + R2 during skill"], desc: "Press L2+R2 during any skill move to cancel the animation.", why: "The ultimate mind game. Start an Elastico, cancel it, go the other way. Unpredictable and deadly." }
    ]
  },
  {
    id: "hogwarts",
    name: "Hogwarts Legacy",
    genre: "Action RPG",
    icon: "🧙",
    color: "#5c2d91",
    desc: "Explore the wizarding world. Master spell combos, broom flight, and magical combat.",
    tags: ["RPG", "Open World", "Magic", "Single Player"],
    tips: [
      { level: "beginner", title: "Basic Cast", controls: ["R2"], desc: "Press R2 to fire your basic cast at targeted enemies.", why: "Your bread and butter. Free damage between spell cooldowns. Always be casting." },
      { level: "beginner", title: "Protego (Shield)", controls: ["△"], desc: "Press Triangle when you see the indicator above your head to block incoming attacks.", why: "Timing it perfectly stuns the attacker, opening them up for a counter." },
      { level: "beginner", title: "Dodge Roll", controls: ["○"], desc: "Press Circle to dodge roll in any direction.", why: "Some attacks can't be blocked (red indicators). Dodge is your only option for those." },
      { level: "beginner", title: "Lock On", controls: ["R3"], desc: "Click the right stick to lock onto an enemy.", why: "Keeps your spells focused on one target. Essential in fights with multiple enemies." },
      { level: "beginner", title: "Revelio", controls: ["Left on D-Pad"], desc: "Press left on D-Pad to reveal hidden items, collectibles, and interactive objects.", why: "Use it constantly while exploring. You'll miss tons of loot and puzzles without it." },
      { level: "beginner", title: "Spell Switching", controls: ["R1 + face buttons"], desc: "Hold R1 and press a face button to cast from your spell diamond. Tap R1 to switch sets.", why: "You have 4 spell sets of 4 spells each = 16 equipped spells. Organize by combat role." },
      { level: "intermediate", title: "Perfect Protego Counter", controls: ["△ (perfect timing)"], desc: "Block at the exact moment of impact for a perfect Protego — stuns and reflects projectiles.", why: "Reflected projectiles deal massive damage. Practice the timing against basic enemies first." },
      { level: "intermediate", title: "Spell Combos: Launch + Slam", controls: ["Levioso → Accio → Descendo"], desc: "Cast Levioso to float an enemy, Accio to pull them close, then Descendo to slam them down.", why: "This combo deals enormous damage and works on most enemies. The core combo of the game." },
      { level: "intermediate", title: "Ancient Magic Meter", controls: ["L1 + R1 (when full)"], desc: "Press L1+R1 together when your Ancient Magic meter is full for a devastating finisher.", why: "One-shots most regular enemies. Build meter by landing varied spell combos." },
      { level: "intermediate", title: "Disillusionment (Stealth)", controls: ["Cast from spell menu"], desc: "Cast Disillusionment to become nearly invisible. Sneak up for Petrificus Totalus.", why: "Petrificus Totalus is an instant kill on unaware enemies. Clear camps without combat." },
      { level: "intermediate", title: "Broom Controls", controls: ["X (mount) / R2 (boost) / L2 (brake)"], desc: "Mount broom with X, boost with R2, and brake/reverse with L2.", why: "Broom is the fastest travel method. Boost through Balloon Pop challenges for rewards." },
      { level: "intermediate", title: "Wingardium Leviosa Weapons", controls: ["Cast then throw objects"], desc: "Use Wingardium Leviosa on environmental objects, then flick them at enemies.", why: "Barrels and crates deal huge damage and break shields. Free damage from the environment." },
      { level: "advanced", title: "Shield Breaker Combos", controls: ["Match spell color to shield"], desc: "Yellow shields = Control spells (Levioso, Glacius). Purple = Force (Accio, Depulso). Red = Damage (Incendio, Confringo).", why: "You MUST match colors to break shields. Keep one of each type equipped at all times." },
      { level: "advanced", title: "Talent Synergies", controls: ["Talent menu"], desc: "Key talents: Protego Absorption (heal on block), Spell Knowledge III (more spell sets), Enduring Curse (Crucio spreads).", why: "The talent tree makes or breaks your build. Prioritize Spell Knowledge for more spell slots early." },
      { level: "advanced", title: "Transformation + Cliff", controls: ["Transformation spell near edges"], desc: "Cast Transformation near cliff edges — transformed enemies can be launched off for instant kills.", why: "Works on any enemy that can be transformed. Trivializes difficult encounters near ledges." },
      { level: "advanced", title: "Room of Requirement Optimization", controls: ["Conjure + Harvest"], desc: "Fill your Room of Requirement with potion stations and beast breeding pens for passive resource generation.", why: "Maxed potions and beast materials give massive combat advantages without spending gold." },
      { level: "expert", title: "Crucio + Curse Chain", controls: ["Crucio → basic casts spread curse"], desc: "Cast Crucio on one enemy, then basic cast other enemies to spread the curse to them.", why: "With the right talents, every cursed enemy takes 30% more damage from everything. Room-wide debuff." },
      { level: "expert", title: "Animation Canceling", controls: ["Dodge → Spell immediately"], desc: "Dodge roll and immediately cast to cancel the recovery animation of your previous spell.", why: "Dramatically increases your DPS. Cast, dodge, cast — never stop dealing damage." },
      { level: "expert", title: "Ancient Magic Throw Combos", controls: ["R1 → throw during combo"], desc: "Pick up an object with Ancient Magic during a juggle combo for devastating finishers.", why: "The thrown object benefits from combo multipliers. Highest single-hit damage in the game." },
      { level: "expert", title: "Invisible Potion + Petrificus Chain", controls: ["Invisibility Potion → spam Petrificus Totalus"], desc: "Drink an invisibility potion and chain Petrificus Totalus on every enemy before they detect you.", why: "Clears entire enemy camps instantly. The potion lasts long enough for 8-10 kills if you're fast." }
    ]
  },
  {
    id: "gow",
    name: "God of War Ragnarok",
    genre: "Action / Adventure",
    icon: "🪓",
    color: "#8b0000",
    desc: "Master Kratos and Atreus across all Nine Realms. Axe, Blades, and Spear combat mastery.",
    tags: ["Action", "Adventure", "Story", "Single Player"],
    tips: [
      { level: "beginner", title: "Light Attack", controls: ["R1"], desc: "Press R1 for a quick light attack. Fast and safe.", why: "Your main damage tool. Light attacks are quick enough to interrupt most enemy attacks." },
      { level: "beginner", title: "Heavy Attack", controls: ["R2"], desc: "Press R2 for a heavy attack. Slower but more damage and stagger.", why: "Staggers enemies faster than light attacks. Use when you have an opening." },
      { level: "beginner", title: "Block / Parry", controls: ["L1 (hold/tap)"], desc: "Hold L1 to block, tap it right before impact to parry.", why: "Parrying stuns enemies and opens massive damage windows. Essential on higher difficulties." },
      { level: "beginner", title: "Dodge", controls: ["X + direction"], desc: "Press X to dodge. Double tap for a roll.", why: "Red ring attacks are unblockable — dodge is your only option. Yellow can be parried or dodged." },
      { level: "beginner", title: "Throw & Recall Axe", controls: ["L2 (aim) + R1/R2 (throw) / △ (recall)"], desc: "Aim with L2, throw with R1 or R2, recall with Triangle.", why: "Recalled axe deals damage on the way back. Freeze an enemy, fight others, recall for bonus damage." },
      { level: "intermediate", title: "Weapon Switching", controls: ["D-Pad left/right/down"], desc: "Left = Axe, Right = Blades, Down = Spear. Swap instantly mid-combo.", why: "Different weapons have different elemental effects. Switch to exploit weaknesses." },
      { level: "intermediate", title: "Runic Attacks", controls: ["L1 + R1 (Light) / L1 + R2 (Heavy)"], desc: "Trigger equipped Runic attacks for powerful special moves with cooldowns.", why: "Runic attacks deal massive burst damage. Use them to start fights or finish tough enemies." },
      { level: "intermediate", title: "Atreus Commands", controls: ["□"], desc: "Press Square to command Atreus to shoot arrows or cast abilities.", why: "Atreus staggers enemies and applies status effects. Keep pressing it — his arrows are free DPS." },
      { level: "intermediate", title: "Spartan Rage", controls: ["L3 + R3"], desc: "Click both sticks when your rage meter is full to activate Spartan Rage.", why: "Heals you with every hit. Save it for when you're low on health — it's a survival tool." },
      { level: "advanced", title: "Frost Awaken / Flame Whiplash", controls: ["△ (hold)"], desc: "Hold Triangle to charge weapon: Frost Awaken (Axe) or Flame Whiplash (Blades).", why: "Charges your next attacks with massive elemental damage. Frost Awaken + heavy attack is devastating." },
      { level: "advanced", title: "Permafrost / Immolation", controls: ["Land hits without taking damage"], desc: "Consecutive hits without damage build weapon glow. Max glow = bonus elemental damage on every hit.", why: "Massively increases DPS. Play carefully — one hit resets your buildup." },
      { level: "advanced", title: "Shield Strike", controls: ["L1 + L1 (double tap)"], desc: "Double tap L1 for a shield bash that breaks guard and interrupts attacks.", why: "Breaks enemy block stances. Essential against shielded enemies." },
      { level: "expert", title: "Parry Window Extension", controls: ["Last-second L1 tap"], desc: "The parry window is tighter on higher difficulties. Train the exact frame timing.", why: "On Give Me No Mercy+, parrying is almost mandatory. It's the highest skill expression in combat." },
      { level: "expert", title: "Runic Cancel", controls: ["Dodge during Runic"], desc: "Start a Runic attack and dodge to cancel it while keeping the damage of the first hit.", why: "Get the burst damage without being locked in the animation. Speeds up combat dramatically." },
      { level: "expert", title: "Spear Detonation Chains", controls: ["Spear impale → △ to detonate"], desc: "Impale multiple enemies with spear throws, then press Triangle to detonate all at once.", why: "Each impaled spear detonates for AoE damage. Stack 3+ on a boss then detonate for massive burst." }
    ]
  },
  {
    id: "spiderman2",
    name: "Spider-Man 2",
    genre: "Action / Adventure",
    icon: "🕷️",
    color: "#cc0000",
    desc: "Swing through NYC as Peter and Miles. Master web combat, symbiote powers, and traversal.",
    tags: ["Action", "Open World", "Superhero", "Single Player"],
    tips: [
      { level: "beginner", title: "Web Swing", controls: ["R2"], desc: "Hold R2 to swing. Release and press again for momentum.", why: "Timing your release at the bottom of the arc gives maximum speed and height." },
      { level: "beginner", title: "Attack / Combo", controls: ["□"], desc: "Press Square repeatedly for a basic combo string.", why: "The foundation of combat. Learn the full string before adding abilities." },
      { level: "beginner", title: "Dodge", controls: ["○"], desc: "Press Circle when spider-sense flashes to dodge incoming attacks.", why: "Perfect dodge (last second) slows time and opens up counterattacks." },
      { level: "beginner", title: "Web Shoot", controls: ["R1"], desc: "Tap R1 to shoot webs that slow and eventually web up enemies.", why: "Web up enemies near walls to instantly KO them. Free takedowns." },
      { level: "beginner", title: "Zip to Point", controls: ["R2 + X"], desc: "While swinging, press X to zip to a perch point.", why: "Great for maintaining altitude and repositioning quickly in the city." },
      { level: "intermediate", title: "Air Combat", controls: ["□ + X (launch) then □ in air"], desc: "Hold Square to launch an enemy into the air, then continue comboing in midair.", why: "Airborne enemies can't be helped by their allies. Isolate tough enemies this way." },
      { level: "intermediate", title: "Yank & Throw", controls: ["L1 + R1"], desc: "Hold L1+R1 to yank enemies or objects toward you, then throw them.", why: "Thrown objects deal massive damage and can hit multiple enemies. Use environmental objects." },
      { level: "intermediate", title: "Symbiote Surge (Peter)", controls: ["L3 + R3"], desc: "Activate symbiote powers for enhanced attacks and tendrils.", why: "Dramatically increases AoE damage. Save for large groups or tough encounters." },
      { level: "intermediate", title: "Venom Powers (Miles)", controls: ["L1 + face button"], desc: "Hold L1 and press a face button to use Venom (bioelectric) abilities.", why: "Venom Punch breaks any guard. Venom Jump is the best crowd control in the game." },
      { level: "advanced", title: "Web Line Double Takedown", controls: ["Stealth + △ on web line"], desc: "Perch on a web line between two points, then stealth takedown two enemies at once.", why: "Clears two enemies simultaneously without being detected. Essential for stealth bases." },
      { level: "advanced", title: "Parry", controls: ["L1 (right before hit)"], desc: "Tap L1 just before an attack connects to parry it.", why: "Only works on certain attacks. Parried enemies are stunned longer than dodged ones." },
      { level: "advanced", title: "Gadget Combos", controls: ["R1 + gadget selection"], desc: "Combine Web Grabber to group enemies, then use Impact Web to pin them all.", why: "Gadget combos can end fights before they start. Pair gadgets that complement each other." },
      { level: "expert", title: "Swing Kick Launch", controls: ["△ (while swinging near enemies)"], desc: "Press Triangle while swinging to perform a devastating swing kick.", why: "Highest single-hit damage move. Build speed then swing kick into a group for massive AoE." },
      { level: "expert", title: "Perfect Dodge Chain", controls: ["○ → □ rapidly"], desc: "Perfect dodge then immediately attack to chain into a special counterattack.", why: "Perfect dodge counters deal 3x damage and build focus rapidly for finishers." },
      { level: "expert", title: "Focus Finisher", controls: ["△ + ○ (when focus bar full)"], desc: "With full focus, press Triangle + Circle for an instant takedown on any regular enemy.", why: "Instant kill that heals you. Save focus for when you're overwhelmed or low HP." }
    ]
  },
  {
    id: "gtav",
    name: "GTA V / GTA Online",
    genre: "Action / Open World",
    icon: "🚗",
    color: "#2d5016",
    desc: "Los Santos awaits. Driving, shooting, heists, and everything in between.",
    tags: ["Action", "Open World", "Multiplayer", "Crime"],
    tips: [
      { level: "beginner", title: "Enter Vehicle", controls: ["△"], desc: "Press Triangle to get in/out of vehicles.", why: "Tap for nearest door. Approach from the driver side to avoid running around the car." },
      { level: "beginner", title: "Aim & Shoot", controls: ["L2 (aim) + R2 (fire)"], desc: "Hold L2 to aim your weapon, R2 to fire.", why: "Aim assist snaps to enemies. Use it for quick target acquisition in firefights." },
      { level: "beginner", title: "Sprint", controls: ["X (tap repeatedly)"], desc: "Tap X repeatedly to sprint on foot.", why: "Stamina increases the more you run. Early game you'll tire quickly." },
      { level: "beginner", title: "Cover System", controls: ["R1"], desc: "Press R1 near a wall or object to take cover.", why: "You die fast in the open. Cover is essential for surviving any gunfight." },
      { level: "beginner", title: "Phone", controls: ["D-Pad up"], desc: "Press up on D-Pad to open your phone for contacts, internet, and jobs.", why: "The phone is your hub for missions, calling contacts, and accessing Online features." },
      { level: "intermediate", title: "Drive-By Shooting", controls: ["L1 (aim from car) + R1 (fire)"], desc: "While driving, L1 aims and R1 fires your weapon out the window.", why: "Essential for chase missions. Use an SMG or micro SMG for drive-bys." },
      { level: "intermediate", title: "Combat Roll", controls: ["□ while aiming"], desc: "Press Square while aiming to dive/roll in any direction.", why: "Invincibility frames during the roll. Dodge rockets and grenades." },
      { level: "intermediate", title: "Quick Weapon Switch", controls: ["L1 (hold) + Right Stick"], desc: "Hold L1 to open weapon wheel, use right stick to select category and weapon.", why: "Practice quick-switching. In PvP, weapon swap speed is a huge advantage." },
      { level: "intermediate", title: "Handbrake Turn", controls: ["R1 (in vehicle)"], desc: "Press R1 while driving to handbrake. Combine with steering for tight turns.", why: "Essential for escaping cops and tight city driving. Better than braking into turns." },
      { level: "advanced", title: "First Person Aim", controls: ["Touchpad → first person + aim"], desc: "Switch to first person view for tighter aim controls in gunfights.", why: "First person has less recoil and more precision. Used by top PvP players." },
      { level: "advanced", title: "Stunt Jump Landing", controls: ["Left Stick + R2 mid-air"], desc: "Tilt your vehicle with the left stick mid-air to land flat.", why: "Flat landings maintain speed and prevent wipeouts. Essential for races and stunts." },
      { level: "advanced", title: "Heist Quick Restart", controls: ["Pause → quick restart on checkpoint"], desc: "If a heist step goes wrong, quick restart from the last checkpoint instead of restarting entirely.", why: "Saves massive time on setups and finales. Know your checkpoint locations." },
      { level: "expert", title: "Off-Radar Ghost Org", controls: ["Interaction Menu → SecuroServ → Ghost Organization"], desc: "Activate Ghost Organization in Online to go off radar for 3 minutes.", why: "Completely invisible to other players. Use for deliveries, escapes, or ambushes." },
      { level: "expert", title: "BST + Sniper Combo (Online)", controls: ["Bull Shark Testosterone + Heavy Sniper"], desc: "Use BST from your CEO menu for damage boost, then snipe.", why: "One-shots most players through body shots. The most feared PvP combo in Online." },
      { level: "expert", title: "Orbital Cannon Counter", controls: ["Go inside building/facility"], desc: "Enter any interior to become untargetable by Orbital Cannons.", why: "If a griefer has an Orbital Cannon, step inside. They waste $750K for nothing." }
    ]
  },
  {
    id: "eldenring",
    name: "Elden Ring",
    genre: "Action RPG / Souls-like",
    icon: "⚔️",
    color: "#8b7500",
    desc: "Conquer the Lands Between. Melee, magic, and mounted combat across a massive open world.",
    tags: ["RPG", "Open World", "Souls-like", "Single Player"],
    tips: [
      { level: "beginner", title: "Light Attack", controls: ["R1"], desc: "Press R1 for a light attack.", why: "Fast and stamina-efficient. Your safest damage option against new enemies." },
      { level: "beginner", title: "Heavy Attack", controls: ["R2"], desc: "Press R2 for a heavy attack. Can be charged by holding.", why: "Charged heavies break poise faster. Hold R2 when enemies are recovering." },
      { level: "beginner", title: "Dodge Roll", controls: ["○"], desc: "Press Circle to roll. You have invincibility frames during the roll.", why: "I-frames are at the START of the roll. Roll INTO attacks, not away. This is counterintuitive but critical." },
      { level: "beginner", title: "Lock On", controls: ["R3"], desc: "Click right stick to lock onto an enemy. Click again to switch targets.", why: "Lock-on keeps your camera on the boss. Unlock for large enemies where the camera struggles." },
      { level: "beginner", title: "Heal (Flask)", controls: ["□"], desc: "Press Square to use a Flask of Crimson Tears (heal).", why: "Time your heals during safe windows. Healing has a long animation that can be punished." },
      { level: "beginner", title: "Guard", controls: ["L1"], desc: "Hold L1 to block with your shield.", why: "Blocking costs stamina. If stamina breaks, you're staggered and wide open." },
      { level: "intermediate", title: "Guard Counter", controls: ["L1 (block hit) → R2"], desc: "Block an attack with L1, then immediately press R2 for a guard counter.", why: "Massive poise damage. Two guard counters often break an enemy's stance for a critical hit." },
      { level: "intermediate", title: "Summon Spirit Ashes", controls: ["Select from item menu near rebirth monument"], desc: "Use Spirit Ashes near summoning pools to call AI allies.", why: "Mimic Tear and Black Knife Tiche are the best. They draw aggro and deal real damage." },
      { level: "intermediate", title: "Torrent (Mount)", controls: ["Use Spectral Steed Whistle"], desc: "Use the whistle to summon Torrent. R1/R2 for mounted attacks.", why: "Mounted combat is easier for open-world bosses. Hit and run on horseback." },
      { level: "intermediate", title: "Jump Attack", controls: ["X → R1 or R2"], desc: "Jump then attack for a jumping strike that deals bonus poise damage.", why: "Jumping attacks are the best way to break poise. Pair with heavy weapons for staggers." },
      { level: "intermediate", title: "Two-Hand Weapon", controls: ["△ + R1 (right) or △ + L1 (left)"], desc: "Hold Triangle and press R1 or L1 to two-hand your right or left weapon.", why: "Two-handing multiplies your strength by 1.5x and changes your moveset. More damage, no shield." },
      { level: "advanced", title: "Ash of War Swapping", controls: ["Grace → Ashes of War menu"], desc: "Change your weapon's Ash of War at any Site of Grace to change its skill and scaling.", why: "Match your Ash of War to your build. Keen for Dex, Heavy for Str, Quality for both." },
      { level: "advanced", title: "Bleed Buildup", controls: ["Use weapons with blood loss"], desc: "Bleed weapons build up hemorrhage. When it procs, it deals a % of max HP.", why: "Bleed destroys bosses. Rivers of Blood and dual curved swords are the meta." },
      { level: "advanced", title: "Stance Breaking", controls: ["Charged R2 + Jump R2 combos"], desc: "Mix charged heavy attacks and jump attacks to break a boss's stance for a critical.", why: "Criticals deal 3-5x your normal damage. It's the most efficient way to kill tough bosses." },
      { level: "expert", title: "Animation Cancel with Items", controls: ["Use item → roll to cancel"], desc: "Use a consumable then roll to cancel the end of the animation.", why: "Lets you buff faster. Stack multiple buffs (grease, perfume, physick) without huge time investment." },
      { level: "expert", title: "Status Effect Stacking", controls: ["Frostbite → Bleed → repeat"], desc: "Apply Frostbite first (resets with fire), then Bleed. Repeat the cycle.", why: "Frostbite + Bleed is the highest DPS combo in the game. Both proc for % HP damage." },
      { level: "expert", title: "Crouch Poke (Thrusting Swords)", controls: ["Crouch → R1 with thrusting sword"], desc: "Crouch and press R1 with a thrusting sword for an extremely fast poke.", why: "Fastest attack in the game. Almost unpunishable in PvP. The meta move for duels." }
    ]
  },
  {
    id: "tlou2",
    name: "The Last of Us Part II",
    genre: "Action / Survival",
    icon: "🍄",
    color: "#3a5a2e",
    desc: "Survive in a brutal post-apocalyptic world. Stealth, crafting, and intense combat.",
    tags: ["Action", "Survival", "Stealth", "Story"],
    tips: [
      { level: "beginner", title: "Listen Mode", controls: ["R1 (hold)"], desc: "Hold R1 to activate listen mode and see enemies through walls.", why: "Plan your approach before engaging. Know every enemy position." },
      { level: "beginner", title: "Crouch / Stealth", controls: ["○"], desc: "Press Circle to crouch and move silently.", why: "Stealth kills save ammo. Resources are scarce — avoid open combat when possible." },
      { level: "beginner", title: "Melee Attack", controls: ["□"], desc: "Press Square for melee strikes.", why: "Melee saves ammo but is risky. Combine with stealth for silent kills." },
      { level: "beginner", title: "Aim & Shoot", controls: ["L2 + R2"], desc: "Hold L2 to aim, R2 to fire.", why: "Aim sways without upgrades. Hold your breath with R1 while aiming to steady it." },
      { level: "intermediate", title: "Prone", controls: ["○ (while crouched)"], desc: "Press Circle while crouched to go prone. Crawl under objects and through grass.", why: "Enemies can't see you in tall grass while prone. Crawl under cars to hide." },
      { level: "intermediate", title: "Craft on the Move", controls: ["Hold D-Pad → select item"], desc: "Open crafting without pausing. Craft health kits and molotovs in real-time.", why: "Time doesn't stop. Find a safe spot, but don't waste time in menus during action." },
      { level: "intermediate", title: "Throw Brick/Bottle", controls: ["L2 + R1"], desc: "Aim with L2, throw with R1. Distracts enemies or stuns them on direct hit.", why: "Lure enemies into ambush positions. A stunned enemy is a free stealth kill." },
      { level: "advanced", title: "Dodge in Melee", controls: ["L1 while in melee"], desc: "Press L1 to dodge melee attacks from enemies.", why: "Dodge, then counter with Square for a devastating combo. Essential against Shamblers and Bloaters." },
      { level: "advanced", title: "Trip Mine + Bait", controls: ["Place mine → throw bottle nearby"], desc: "Place a trap mine, then throw a brick/bottle near it to lure enemies into the explosion.", why: "Can kill 3-4 enemies at once. The most efficient use of your limited explosives." },
      { level: "expert", title: "Stealth Chain Kills", controls: ["Stealth kill → immediate prone → next kill"], desc: "After a stealth kill, immediately go prone and crawl to the next target.", why: "Nearby enemies briefly look toward the kill location. Prone makes you invisible while they search." },
      { level: "expert", title: "Smoke + Shiv Rush", controls: ["Smoke bomb → rush with shiv"], desc: "Throw a smoke bomb then rush in with a shiv for multiple instant kills while enemies are blinded.", why: "Clears entire rooms of enemies using only a smoke bomb and shiv. Maximum efficiency." }
    ]
  },
  {
    id: "horizon",
    name: "Horizon Forbidden West",
    genre: "Action RPG",
    icon: "🦖",
    color: "#c45a1a",
    desc: "Hunt mechanical beasts as Aloy. Master ranged combat, traps, and machine overrides.",
    tags: ["Action", "RPG", "Open World", "Sci-Fi"],
    tips: [
      { level: "beginner", title: "Shoot Arrow", controls: ["L2 (aim) + R2 (fire)"], desc: "Aim with L2, fire with R2. Hold R2 to charge for more damage.", why: "Charged shots deal significantly more damage. Always fully charge when you have time." },
      { level: "beginner", title: "Dodge Roll", controls: ["○"], desc: "Press Circle to dodge. Can chain multiple dodges.", why: "I-frames during the roll. Side dodge for most attacks, back dodge for charge attacks." },
      { level: "beginner", title: "Focus Scan", controls: ["R3"], desc: "Click R3 to scan machines and reveal weak points, components, and patrol paths.", why: "ALWAYS scan before fighting. Hitting weak points deals 3-5x damage." },
      { level: "beginner", title: "Concentration", controls: ["R3 while aiming"], desc: "Click R3 while aiming to slow time temporarily.", why: "Lets you line up precise shots on moving weak points. Essential for hitting canisters." },
      { level: "intermediate", title: "Tear Components Off", controls: ["Use Tearblast arrows"], desc: "Equip Tearblast arrows and shoot machine components to rip them off.", why: "Removes machine weapons AND you can pick them up to use against them. Double benefit." },
      { level: "intermediate", title: "Weapon Techniques", controls: ["R1 combos"], desc: "Each weapon type has unique techniques. Hold R1 for special attacks.", why: "Weapon techniques deal massive damage and apply status effects much faster than normal attacks." },
      { level: "intermediate", title: "Elemental Weakness", controls: ["Scan → match element"], desc: "Fire arrows on Frost machines, Shock on water machines, etc.", why: "Hitting elemental weaknesses deals bonus damage AND can trigger explosions on canisters." },
      { level: "advanced", title: "Valor Surge", controls: ["L1 + R1 when meter full"], desc: "Activate your equipped Valor Surge for a powerful temporary buff.", why: "Ranged Master Valor Surge makes every arrow deal massive damage. Pop it before a tough fight." },
      { level: "advanced", title: "Override Machines", controls: ["Sneak behind → △"], desc: "Approach stealthily from behind and press Triangle to override a machine to fight for you.", why: "Overridden machines are incredibly powerful allies. Override the biggest machine in a group." },
      { level: "advanced", title: "Triple Notch", controls: ["Skill → R2 hold to notch multiple"], desc: "With the skill unlocked, hold R2 to notch up to 3 arrows simultaneously.", why: "3 arrows at once = triple damage. Makes short work of even the largest machines." },
      { level: "expert", title: "Canister Chain Explosions", controls: ["Shoot canister → detonates nearby canisters"], desc: "Hit one canister to trigger a chain reaction if machines are grouped.", why: "A single well-placed Tearblast + fire arrow can kill an entire group through chain explosions." },
      { level: "expert", title: "Mounted Combat", controls: ["Override mount → R1/R2 on mount"], desc: "Override a Charger or Bristleback, ride it into battle with mounted attacks.", why: "Mounted charge attacks deal enormous damage and you can flee instantly. Mobile artillery." }
    ]
  },
  {
    id: "ghost",
    name: "Ghost of Tsushima",
    genre: "Action / Open World",
    icon: "⛩️",
    color: "#4a0e0e",
    desc: "Become the Ghost. Samurai combat stances, stealth, and standoffs on Tsushima Island.",
    tags: ["Action", "Open World", "Samurai", "Stealth"],
    tips: [
      { level: "beginner", title: "Quick Attack", controls: ["□"], desc: "Press Square for a quick katana strike.", why: "Fast and versatile. The core of every combo in the game." },
      { level: "beginner", title: "Heavy Attack", controls: ["△"], desc: "Press Triangle for a heavy, stance-breaking attack.", why: "Breaks guards and stagger. Essential against shielded enemies." },
      { level: "beginner", title: "Block / Parry", controls: ["L1 (hold/tap)"], desc: "Hold L1 to block, tap at the right moment to parry.", why: "Perfect parry creates a huge opening. Blue glint = parryable. Red = dodge only." },
      { level: "beginner", title: "Dodge", controls: ["○"], desc: "Press Circle to dodge. Works against unblockable attacks.", why: "Red attacks MUST be dodged. Learn the enemy tells for red vs blue attacks." },
      { level: "intermediate", title: "Switch Stances", controls: ["R2 + face button"], desc: "Hold R2 and press a face button: Stone (swords), Water (shields), Wind (spears), Moon (brutes).", why: "Each stance is STRONG against its enemy type. Using the wrong stance is like fighting with a wet noodle." },
      { level: "intermediate", title: "Standoff", controls: ["D-Pad up (near enemies)"], desc: "Approach a group and press up to challenge them to a standoff. Release Triangle at the right moment.", why: "Instant kills the first enemy. Upgraded, can kill up to 5 in a row. Best opener in the game." },
      { level: "intermediate", title: "Ghost Weapons", controls: ["L2 + face button"], desc: "Hold L2 and use face buttons for kunai, smoke bombs, sticky bombs, or wind chimes.", why: "Kunai staggers groups, smoke lets you stealth-kill multiple enemies. Ghost weapons are overpowered." },
      { level: "advanced", title: "Perfect Parry Chain", controls: ["L1 (perfect timing, repeatedly)"], desc: "Chain perfect parries against rapid attacks for a flow of counterstrikes.", why: "Against Dueling bosses, perfect parry chains are the fastest way to win." },
      { level: "advanced", title: "Resolve Management", controls: ["Use for healing or special moves"], desc: "Resolve fills from combat. Spend on healing (D-Pad down) or on Mythic Arts.", why: "Don't hoard resolve. Use it for Mythic Arts when fighting groups, heal against bosses." },
      { level: "expert", title: "Dance of Wrath + Smoke", controls: ["Smoke bomb → Dance of Wrath"], desc: "Smoke bomb a group, then use Dance of Wrath Mythic Art while they're disoriented.", why: "3 unblockable strikes into blinded enemies. Usually kills everything in the smoke cloud." },
      { level: "expert", title: "Heavenly Strike Cancel", controls: ["Heavenly Strike → dodge → repeat"], desc: "Use Heavenly Strike (stab), dodge cancel the recovery, then immediately Heavenly Strike again.", why: "Infinite Heavenly Strike loop is the highest DPS combo. Melts bosses on Lethal difficulty." }
    ]
  },
  {
    id: "rdr2",
    name: "Red Dead Redemption 2",
    genre: "Action / Open World",
    icon: "🤠",
    color: "#654321",
    desc: "The Wild West as Arthur Morgan. Gunslinging, hunting, and outlaw life.",
    tags: ["Action", "Open World", "Western", "Story"],
    tips: [
      { level: "beginner", title: "Shoot", controls: ["L2 (aim) + R2 (fire)"], desc: "Hold L2 to aim, R2 to fire. Auto-aim snaps to enemies.", why: "Weapons have different bloom. Wait for the reticle to shrink before firing for accuracy." },
      { level: "beginner", title: "Mount Horse", controls: ["△"], desc: "Press Triangle near your horse to mount/dismount.", why: "Always hitch your horse or it may wander. Bonding increases speed and stamina." },
      { level: "beginner", title: "Cover", controls: ["R1"], desc: "Press R1 near cover to take cover behind it.", why: "You die very fast in the open. Always fight from cover." },
      { level: "beginner", title: "Eagle Eye", controls: ["L3 + R3"], desc: "Click both sticks to activate Eagle Eye. Highlights trails, animals, and clues.", why: "Essential for tracking in hunting missions and finding collectibles." },
      { level: "intermediate", title: "Dead Eye", controls: ["R3 while aiming"], desc: "Click R3 while aiming to activate Dead Eye (slow motion targeting).", why: "Paint targets with R1 in Dead Eye, then fire. Clears entire groups in seconds." },
      { level: "intermediate", title: "Quick Draw", controls: ["L2 (tap quickly) + R2"], desc: "Lightly tap L2 to quick draw and immediately fire with R2.", why: "Faster than a full aim. Essential for duels and surprise encounters." },
      { level: "intermediate", title: "Clean Weapons", controls: ["Gun oil from item wheel"], desc: "Apply gun oil from the item wheel to maintain weapon condition.", why: "Dirty weapons lose damage and accuracy. Clean before every major mission." },
      { level: "advanced", title: "Dead Eye Headshot Paint", controls: ["Dead Eye → flick to heads → fire"], desc: "In Dead Eye, quickly flick between enemies' heads and paint all targets.", why: "6 painted headshots = 6 instant kills. The fastest way to clear a room." },
      { level: "advanced", title: "Horse Drift", controls: ["R1 + direction while riding"], desc: "While riding fast, press R1 and turn to perform a sharp skid turn.", why: "Sharp turns without losing your horse. Essential for chases and tight trails." },
      { level: "expert", title: "Deadeye Tonics + Dual Wield", controls: ["Tonic → dual wield → Dead Eye"], desc: "Drink a Dead Eye tonic for slow-mo, then dual-wield with Dead Eye for 12 painted shots.", why: "12 simultaneous kills. The most devastating attack possible. Clears any encounter instantly." },
      { level: "expert", title: "Perfect Pelt Hunting", controls: ["Study → use correct weapon → headshot"], desc: "Study animal with binoculars, use the recommended weapon class, aim for the head.", why: "3-star pelts require perfect kills. Wrong weapon = ruined pelt = wasted time." }
    ]
  },
  {
    id: "ff16",
    name: "Final Fantasy XVI",
    genre: "Action RPG",
    icon: "🔥",
    color: "#4a1a8a",
    desc: "Eikon powers and stylish combat as Clive Rosfield in Valisthea.",
    tags: ["Action", "RPG", "Story", "Fantasy"],
    tips: [
      { level: "beginner", title: "Melee Combo", controls: ["□ chain"], desc: "Press Square repeatedly for a sword combo.", why: "Your basic damage. Learn the combo rhythm for maximum hits." },
      { level: "beginner", title: "Magic Burst", controls: ["△"], desc: "Press Triangle for a ranged magic attack.", why: "Use between melee combos for continuous damage. No cooldown, no cost." },
      { level: "beginner", title: "Dodge", controls: ["R1"], desc: "Press R1 to dodge. Precision Dodge (last moment) slows time.", why: "Precision Dodge gives a HUGE window for free damage. Master the timing." },
      { level: "beginner", title: "Eikon Abilities", controls: ["L2 + face buttons"], desc: "Hold L2 and press face buttons to use equipped Eikon abilities.", why: "Your most powerful attacks. Rotate between cooldowns for constant DPS." },
      { level: "intermediate", title: "Stagger System", controls: ["Half-bar = stagger"], desc: "Every enemy has a stagger bar. Deplete it to stun them for massive damage.", why: "During stagger, all damage is multiplied. Save your biggest abilities for stagger windows." },
      { level: "intermediate", title: "Lunge", controls: ["□ (hold) → release toward enemy"], desc: "Hold Square to charge, release to lunge at a distant enemy.", why: "Closes distance instantly. Keeps your combo going when enemies retreat." },
      { level: "intermediate", title: "Eikon Swap", controls: ["L2 + L1/R1"], desc: "While holding L2, press L1 or R1 to swap between your three Eikon sets.", why: "Swap when abilities are on cooldown. Always have abilities ready to use." },
      { level: "advanced", title: "Zantetsuken (Odin)", controls: ["Build gauge → L2 + □+△"], desc: "Build the Zantetsuken gauge with attacks, then unleash for massive damage.", why: "The highest single-hit damage in the game. Full gauge Zantetsuken can one-shot mid-bosses." },
      { level: "advanced", title: "Aerial Combo", controls: ["Launch → □ chain in air"], desc: "Use Phoenix Shift or Gouge to launch enemies, then combo them midair.", why: "Enemies can't attack while airborne. Free damage with zero risk." },
      { level: "expert", title: "Stagger Burst Window", controls: ["All abilities during stagger"], desc: "When an enemy staggers, unleash every Eikon ability, swap sets, and continue. Time your biggest hits.", why: "Top players deal 70% of boss HP during stagger windows. It's a damage race during those seconds." },
      { level: "expert", title: "Precision Counter → Full Combo", controls: ["Precision Dodge → □ → △ → all abilities"], desc: "Precision dodge into a full melee chain into magic into every Eikon ability.", why: "The perfect flow state. Dodge, counter, combo, swap, ability, swap, ability. Non-stop DPS." }
    ]
  },
  {
    id: "cod",
    name: "Call of Duty (Latest)",
    genre: "FPS / Shooter",
    icon: "🎯",
    color: "#2a2a2a",
    desc: "Multiplayer, Warzone, and Zombies. Fast-paced FPS action.",
    tags: ["FPS", "Multiplayer", "Battle Royale", "Zombies"],
    tips: [
      { level: "beginner", title: "Aim Down Sights", controls: ["L2"], desc: "Hold L2 to aim down sights for much better accuracy.", why: "Hip-fire is inaccurate at range. ADS for any target beyond close range." },
      { level: "beginner", title: "Slide", controls: ["○ while sprinting"], desc: "Press Circle while sprinting to slide.", why: "Slides under enemy crosshairs. Use to get into cover or round corners." },
      { level: "beginner", title: "Reload", controls: ["□"], desc: "Press Square to reload your weapon.", why: "Reload behind cover, never in the open. Reload cancel (sprint or weapon swap) if surprised mid-reload." },
      { level: "beginner", title: "Tactical & Lethal", controls: ["L1 (tactical) / R1 (lethal)"], desc: "L1 for stun/flash grenades, R1 for frag/semtex.", why: "Always use your equipment. A pre-thrown stun wins gunfights before they start." },
      { level: "intermediate", title: "Mount", controls: ["L2 near edge → L3"], desc: "Aim near a ledge or wall and press L3 to mount your weapon for reduced recoil.", why: "Virtually zero recoil while mounted. Great for holding angles and long-range fights." },
      { level: "intermediate", title: "Pre-Aim Corners", controls: ["L2 before rounding corners"], desc: "ADS before you turn a corner so you're ready to fire instantly.", why: "The player who's already aiming wins 90% of corner fights. Pre-aim common spots." },
      { level: "intermediate", title: "Plate Up (Warzone)", controls: ["Hold △ for armor"], desc: "Hold Triangle to apply armor plates in Warzone.", why: "Always be fully plated. Plates are the difference between winning and losing gunfights." },
      { level: "advanced", title: "Slide Cancel", controls: ["Slide → crouch → sprint → slide"], desc: "Slide, then immediately crouch and sprint again to cancel the slide recovery.", why: "Maintains your sprint speed while breaking enemy aim assist. The core movement mechanic." },
      { level: "advanced", title: "Camera Breaking", controls: ["Sprint past corner → snap aim"], desc: "Sprint past a corner where an enemy is holding and snap your aim onto them.", why: "Due to camera angles, you see them before they see you for a split second. Huge advantage." },
      { level: "advanced", title: "Drop Shot", controls: ["R3 (prone) while shooting"], desc: "Press R3 to go prone while continuing to fire.", why: "Your hitbox drops instantly. The enemy loses their aim while you keep shooting." },
      { level: "expert", title: "Bunny Hop + Slide Cancel Chain", controls: ["Jump → slide → cancel → jump → slide"], desc: "Chain jumps and slide cancels together for unpredictable movement.", why: "Nearly impossible to track. Top players chain these constantly in Warzone and Ranked." },
      { level: "expert", title: "Centering", controls: ["Keep crosshair at head height always"], desc: "Always keep your crosshair at head height and pre-aimed at common angles.", why: "The #1 skill that separates pros from casuals. Minimizes the distance you need to flick." }
    ]
  },
  {
    id: "persona5",
    name: "Persona 5 Royal",
    genre: "JRPG / Social Sim",
    icon: "🎭",
    color: "#e60012",
    desc: "Steal hearts and manage your time. Combat, confidants, and the Metaverse.",
    tags: ["JRPG", "Story", "Turn-Based", "Social Sim"],
    tips: [
      { level: "beginner", title: "Exploit Weaknesses", controls: ["Analyze → hit weakness"], desc: "Use the Analyze ability, then hit shadows with their elemental weakness for extra turns.", why: "Hitting weaknesses gives you One More actions. This is the core of combat — never attack without knowing weaknesses." },
      { level: "beginner", title: "All-Out Attack", controls: ["Knock all down → All-Out Attack prompt"], desc: "When all enemies are knocked down, trigger an All-Out Attack for massive damage.", why: "Usually one-shots regular encounters. The reward for exploiting every weakness." },
      { level: "beginner", title: "Guard", controls: ["Select Guard in battle"], desc: "Choose Guard to halve incoming damage for one turn.", why: "Guard when you know a powerful attack is coming. Essential for boss survival." },
      { level: "intermediate", title: "Baton Pass", controls: ["After One More → pass to ally"], desc: "After getting a One More, pass your turn to an ally to boost their attack power.", why: "Each Baton Pass increases damage. Pass through 3 allies for a hugely powered-up final attack." },
      { level: "intermediate", title: "Time Management", controls: ["Plan daily activities carefully"], desc: "Every day has limited time slots. Prioritize confidants and social stats.", why: "You can't max everything on a first playthrough without a guide. Focus on the confidants you want most." },
      { level: "intermediate", title: "Persona Fusion", controls: ["Velvet Room → Fuse"], desc: "Fuse Personas in the Velvet Room to create stronger ones that inherit skills.", why: "Fused Personas are ALWAYS stronger than found ones. Fuse often and inherit the best skills." },
      { level: "advanced", title: "Confidant Priority: Temperance & Fortune", controls: ["Level Kawakami & Chihaya"], desc: "Kawakami lets you do activities at night even after Metaverse. Chihaya boosts confidant points.", why: "These two confidants give you MORE TIME, the most valuable resource. Max them early." },
      { level: "advanced", title: "Technical Damage", controls: ["Status ailment → specific element"], desc: "Apply a status ailment then hit with the corresponding element for Technical damage.", why: "Technical damage knocks down enemies. Combined with Baton Pass, this is the advanced combat loop." },
      { level: "expert", title: "Fusion Alarm Abuse", controls: ["Trigger alarm → fuse for boosted results"], desc: "Fusion Alarms in Mementos boost fusion results. Can create Personas with extra skills and stats.", why: "Alarm fusions can create Personas that are 2-3x stronger than normal. The key to superboss fights." },
      { level: "expert", title: "Itemize Personas", controls: ["Velvet Room → Electric Chair"], desc: "Itemize specific Personas into powerful equipment and skill cards.", why: "Some of the best weapons and accessories in the game come from itemization, not shops or drops." }
    ]
  },
  {
    id: "demon",
    name: "Demon's Souls Remake",
    genre: "Action RPG / Souls-like",
    icon: "👻",
    color: "#1a1a3a",
    desc: "The original Souls game, remade for PS5. Punishing combat in Boletaria.",
    tags: ["RPG", "Souls-like", "PS5 Exclusive", "Single Player"],
    tips: [
      { level: "beginner", title: "Light / Heavy Attack", controls: ["R1 / R2"], desc: "R1 for light, R2 for heavy attacks.", why: "Light attacks are safer and faster. Heavy attacks for openings only." },
      { level: "beginner", title: "Block", controls: ["L1"], desc: "Hold L1 to block with your shield.", why: "A good shield trivializes early game. Purple Flame Shield from 1-1 blocks fire." },
      { level: "beginner", title: "Roll", controls: ["○"], desc: "Press Circle to roll. I-frames depend on equip load.", why: "Under 50% equip load for normal roll. Under 25% for fast roll. Over 50% = fat roll = death." },
      { level: "beginner", title: "Lock On", controls: ["R3"], desc: "Lock onto enemies for tracking attacks.", why: "Unlock for large bosses where camera is a problem." },
      { level: "intermediate", title: "World Tendency", controls: ["Die in human form = darker"], desc: "Dying in human form shifts World Tendency toward Black. Pure White/Black unlock secrets.", why: "Die in the Nexus (suicide) to stay in soul form and prevent world darkening. This is critical knowledge." },
      { level: "intermediate", title: "Backstab", controls: ["Get behind enemy → R1"], desc: "Position yourself behind an enemy and press R1 for a backstab critical hit.", why: "Massive damage multiplier. Circle-strafe slow enemies to get behind them." },
      { level: "intermediate", title: "Magic is OP", controls: ["Soul Arrow / Firestorm"], desc: "Magic builds are significantly easier. Royalty class starts with Soul Arrow.", why: "Royalty is the best starting class for beginners. MP regenerates with the starting ring." },
      { level: "advanced", title: "Hyper Mode", controls: ["Morion Blade + Clever Rat Ring at low HP"], desc: "Equip Morion Blade and Clever Rat Ring, get below 30% HP for massive damage boost.", why: "Combined they boost damage by 140%. One-shots most bosses with strong spells." },
      { level: "advanced", title: "Firestorm Cheese", controls: ["Get close to boss → Firestorm"], desc: "Walk up to a boss and cast Firestorm. Each pillar hits for massive damage.", why: "Kills most bosses in 1-3 casts. The most overpowered spell in any Souls game." },
      { level: "expert", title: "Luck Build (Blueblood Sword)", controls: ["Blueblood Sword + Light Weapon + Luck"], desc: "Max Luck, equip Blueblood Sword, buff with Light Weapon for the highest damage build.", why: "Blueblood Sword scales with Luck and gets extra damage from buffs. Highest physical DPS possible." },
      { level: "expert", title: "Boss Rush via World Order", controls: ["Complete worlds in optimal order"], desc: "Do 1-1, 2-1, 4-1, then push each world sequentially for optimal soul farming and gear.", why: "Specific world order gets you the best gear earliest. 4-1 gives Crescent Falchion, the best early weapon." }
    ]
  },
  {
    id: "ratchet",
    name: "Ratchet & Clank: Rift Apart",
    genre: "Action / Platformer",
    icon: "🔧",
    color: "#1a6baa",
    desc: "Dimension-hopping action with creative weapons and platforming across rifts.",
    tags: ["Action", "Platformer", "PS5 Exclusive", "Family"],
    tips: [
      { level: "beginner", title: "Shoot", controls: ["R2"], desc: "Press R2 to fire your equipped weapon.", why: "Different weapons for different situations. Experiment with all of them." },
      { level: "beginner", title: "Melee", controls: ["□"], desc: "Press Square to swing your wrench for close-range damage.", why: "Melee breaks crates for bolts and deals decent damage when ammo is low." },
      { level: "beginner", title: "Jump & Hover", controls: ["X (jump) / X again (hover)"], desc: "Press X to jump, press again at peak to hover with heli-pack.", why: "Hovering gives you more air time for platforming precision." },
      { level: "beginner", title: "Dash", controls: ["○"], desc: "Press Circle to dash. Works in air too.", why: "Invincible during dash. Use for dodging AND for crossing gaps." },
      { level: "intermediate", title: "Weapon Wheel", controls: ["△ (hold)"], desc: "Hold Triangle to open the weapon wheel and quickly swap.", why: "Swap weapons constantly. Using all weapons levels them all up evenly." },
      { level: "intermediate", title: "Rift Tether", controls: ["L1"], desc: "Press L1 to tether to a dimensional rift and teleport to it.", why: "Repositions you instantly. Use it to dodge attacks AND to cross large gaps." },
      { level: "intermediate", title: "Adaptive Trigger Weapons", controls: ["R2 half/full press"], desc: "Some weapons have dual fire modes with the PS5 adaptive triggers. Half-press vs full-press.", why: "The Enforcer fires one barrel on half-press, both on full. Master this for ammo efficiency." },
      { level: "advanced", title: "Topiary Sprinkler + DPS", controls: ["Place Topiary → swap to DPS weapon"], desc: "Deploy Topiary Sprinkler to freeze enemies in place, then blast them with your strongest weapon.", why: "The best combo in the game. Frozen enemies take full damage while completely helpless." },
      { level: "advanced", title: "Weapon Level Priority", controls: ["Use underleveled weapons"], desc: "Intentionally use lower-level weapons to level them up. Maxed weapons unlock Omega versions.", why: "Omega weapons in Challenge Mode are insanely powerful. Get every weapon to max before NG+." },
      { level: "expert", title: "Challenge Mode Bolt Multiplier", controls: ["Kill streaks without getting hit"], desc: "In Challenge Mode, your bolt multiplier increases with consecutive kills and resets when hit.", why: "A 20x multiplier means 20x bolts. Essential for affording all Omega weapon upgrades." },
      { level: "expert", title: "RYNO 8", controls: ["Collect all Spybots"], desc: "Find all 9 Spybots to unlock the RYNO 8 — the most powerful weapon that pulls objects from other dimensions.", why: "Literally rains objects from other PlayStation games. Absurdly overpowered and hilarious." }
    ]
  }
];
