registerGames([
{
  id:"madden",name:`Madden NFL ${CURRENT_YEAR}`,yearlyUpdate:true,genre:"Sports / Football",category:"sports",icon:"🏈",color:"#1a5e1a",
  desc:`Master every play in Madden NFL ${CURRENT_YEAR}. From basic passes to elite audibles, hot routes, and defensive schemes.`,
  tags:["Sports","Football","Multiplayer","Online"],
  tips:[
    {level:"beginner",section:"Basics",title:"Snap the Ball",controls:["X"],desc:"Press X to hike the ball and start the play.",why:"Everything starts here. Get comfortable with snap timing to avoid delay of game."},
    {level:"beginner",section:"Basics",title:"Select a Play",controls:["D-Pad / Left Stick"],desc:"Navigate formations and plays. D-Pad switches tabs, Left Stick browses plays.",why:"Quick play selection prevents delay of game penalties. Learn your favorite formations."},
    {level:"beginner",section:"Basics",title:"Pause / Timeout",controls:["Options / Touchpad"],desc:"Options pauses the game. Touchpad calls a timeout.",why:"Timeouts stop the clock. Use them to save time at the end of halves."},
    {level:"beginner",section:"Passing",title:"Throw to Receivers",controls:["X / ○ / △ / □ / R1"],desc:"Each button maps to a receiver. Press to throw to that receiver after the snap.",why:"Knowing your receiver icons lets you make quick reads and avoid sacks."},
    {level:"beginner",section:"Passing",title:"Throw the Ball Away",controls:["Right Stick click (R3)"],desc:"Press R3 outside the tackle box to throw the ball away and avoid a sack.",why:"Taking a sack loses yards. Throwing it away just costs you the down — much better."},
    {level:"beginner",section:"Passing",title:"Lob vs Bullet Pass",controls:["Tap (lob) / Hold (bullet)"],desc:"Tap receiver button for a lob pass, hold it for a bullet pass.",why:"Lobs over linebackers on deep routes. Bullets for short/medium into tight windows."},
    {level:"beginner",section:"Running",title:"Sprint",controls:["R2 (hold)"],desc:"Hold R2 to sprint with the ball carrier.",why:"Essential for breaking away. But don't sprint into traffic — you lose agility."},
    {level:"beginner",section:"Running",title:"Dive",controls:["□"],desc:"Press Square to dive forward for extra yards.",why:"Dive at the goal line or first down marker. Protects the ball better than running upright."},
    {level:"beginner",section:"Running",title:"Slide (QB)",controls:["L1 (while scrambling)"],desc:"Press L1 while running as the QB to slide and give yourself up safely.",why:"Sliding prevents fumbles. ALWAYS slide on designed QB runs unless you're in the open field."},
    {level:"beginner",section:"Defense",title:"Tackle",controls:["X"],desc:"Press X near the ball carrier to make a tackle.",why:"The most fundamental defensive play. Time it properly to avoid whiffing."},
    {level:"beginner",section:"Defense",title:"Switch Player",controls:["○"],desc:"Press Circle to switch to the nearest defender to the ball.",why:"Control the right player at the right time. Don't chase with the wrong defender."},
    {level:"intermediate",section:"Passing",title:"Pump Fake",controls:["Double-tap receiver button"],desc:"Double-tap a receiver's icon to pump fake in that direction.",why:"Freezes safeties and linebackers. Opens windows when they bite on the fake."},
    {level:"intermediate",section:"Passing",title:"Pass Lead",controls:["Left Stick while throwing"],desc:"Hold a direction while throwing to lead the pass high, low, left, or right.",why:"Lead throws away from defenders. High pass over LBs, low away from safeties."},
    {level:"intermediate",section:"Running",title:"Spin Move",controls:["○"],desc:"Press Circle while running to spin past defenders.",why:"Best in open space. Beats arm tackles consistently. Don't use into a crowd."},
    {level:"intermediate",section:"Running",title:"Juke",controls:["Right Stick left/right"],desc:"Flick right stick left or right to juke.",why:"More effective than spin in tight spaces. Chain with sprint for devastating moves."},
    {level:"intermediate",section:"Running",title:"Stiff Arm",controls:["X"],desc:"Press X while running to stiff arm a nearby defender.",why:"Sheds tacklers without slowing down. Great against smaller DBs."},
    {level:"intermediate",section:"Running",title:"Hurdle",controls:["△"],desc:"Press Triangle to hurdle over a diving defender.",why:"Jumps over low tackles. Risky but can break a big play open."},
    {level:"intermediate",section:"Running",title:"Truck Stick",controls:["Right Stick up"],desc:"Flick right stick forward to truck through a defender.",why:"Power move for big backs. Can cause fumbles on the defender but risky with small runners."},
    {level:"intermediate",section:"Running",title:"Pitch / Lateral",controls:["L1"],desc:"Press L1 to pitch the ball to a nearby teammate.",why:"Option pitches and desperation laterals. Be careful — dropped laterals are fumbles."},
    {level:"intermediate",section:"Pre-Snap",title:"Motion a Player",controls:["Left Stick on receiver pre-snap"],desc:"Flick the right stick toward a receiver to put them in motion before the snap.",why:"Pre-snap motion reveals man vs zone. If the defender follows, it's man coverage."},
    {level:"intermediate",section:"Defense",title:"Strafe",controls:["L2"],desc:"Hold L2 to strafe and stay square on defense.",why:"Keeps your defender in position. Essential for user-controlled coverage in the secondary."},
    {level:"intermediate",section:"Defense",title:"Ball Hawk / Intercept",controls:["△"],desc:"Hold Triangle near a thrown ball to attempt an interception.",why:"Timing is critical. Too early = beaten for a big play. Too late = no animation."},
    {level:"intermediate",section:"Defense",title:"Swat Ball",controls:["□"],desc:"Press Square to swat the ball away instead of intercepting.",why:"Safer than INT attempt. Use when you're not in perfect position."},
    {level:"intermediate",section:"Defense",title:"Hit Stick",controls:["Right Stick up"],desc:"Flick right stick up for a big hit that can cause fumbles.",why:"High risk, high reward. Whiffing means a missed tackle. Landing one can change the game."},
    {level:"intermediate",section:"Defense",title:"Strip Ball",controls:["R1"],desc:"Press R1 while tackling to attempt to strip the ball.",why:"Won't always work but can force turnovers in crucial moments."},
    {level:"advanced",section:"Pre-Snap",title:"Hot Routes",controls:["△ then receiver + route"],desc:"Press Triangle, select a receiver, and assign a new route (slant, curl, streak, etc).",why:"Audible individual receivers. Slants beat man, curls beat zone, streaks beat blitz."},
    {level:"advanced",section:"Pre-Snap",title:"Audible",controls:["□ then play"],desc:"Press Square at the line to change the entire play.",why:"Read the defense pre-snap. See a blitz? Audible to a screen. See single-high? Go deep."},
    {level:"advanced",section:"Pre-Snap",title:"Flip Play",controls:["L1 pre-snap"],desc:"Press L1 to flip the entire play design to the other side.",why:"If the defense is overloaded to one side, flip the play to attack the weak side."},
    {level:"advanced",section:"Passing",title:"Precision Passing",controls:["L2 + receiver button + Left Stick"],desc:"Hold L2 while throwing and use left stick to place the ball exactly.",why:"Pinpoint accuracy for tight windows. The difference between a completion and a pick."},
    {level:"advanced",section:"Defense",title:"Defensive Adjustments",controls:["△ (secondary) / ○ (D-line)"],desc:"Triangle adjusts secondary (press, shade inside/outside). Circle adjusts line (spread, pinch, crash).",why:"Shade inside vs slants, outside vs outs. Pinch line to stop inside runs."},
    {level:"advanced",section:"Defense",title:"Zone Drops",controls:["D-Pad assignments"],desc:"Adjust zone depth — hook zones, curl-flat, cloud, hard flat.",why:"Different zone drops cover different route combos. Match them to what the offense runs."},
    {level:"advanced",section:"Defense",title:"Contain",controls:["R1 on D-ends"],desc:"Set your defensive ends to contain to prevent the QB from scrambling.",why:"Mobile QBs destroy you without contain. Forces them to stay in the pocket."},
    {level:"advanced",section:"Defense",title:"QB Spy",controls:["Select LB → spy"],desc:"Assign a linebacker to QB spy. They mirror the QB's movement.",why:"Shuts down scrambling QBs while maintaining zone coverage."},
    {level:"expert",section:"Pre-Snap",title:"ID the Mike",controls:["R1 + select LB"],desc:"Press R1 and select which linebacker is the Mike for your blocking scheme.",why:"Shifts protection. Against exotic blitzes, ID the extra rusher to pick them up."},
    {level:"expert",section:"Pre-Snap",title:"Slide Protection",controls:["L1 + Left Stick left/right"],desc:"Press L1 then flick left stick to slide your O-line protection left or right.",why:"Slide toward the blitz side. Keeps the QB clean against edge pressure."},
    {level:"expert",section:"Pre-Snap",title:"RPO Reads",controls:["Watch LB after snap"],desc:"On RPO plays, read the linebacker. If he bites on the run, throw. If he drops, hand off.",why:"RPOs are unstoppable when read correctly. The LB tells you everything."},
    {level:"expert",section:"Pre-Snap",title:"Option Reads",controls:["Read DE → keep or give"],desc:"On option plays, read the unblocked defensive end. If he crashes, keep. If he stays, give.",why:"Option football forces the defense to be wrong every time when read properly."},
    {level:"expert",section:"Receiving",title:"RAC vs Possession vs Aggressive",controls:["X (RAC) / □ (Possession) / △ (Aggressive)"],desc:"Choose catch type: X for run after catch, Square for possession, Triangle for aggressive.",why:"RAC in open field, possession on sidelines, aggressive in the end zone. Wrong choice = drops."},
    {level:"expert",section:"Defense",title:"Manual Blitz Design",controls:["Select defender + ○ (blitz)"],desc:"Individually assign defenders to blitz, zone, or man coverage.",why:"Create custom pressure. Send unexpected rushers from corners or safeties."},
    {level:"expert",section:"Special Teams",title:"Onside Kick",controls:["Aim + tap for power"],desc:"On kickoffs, aim to the side and use minimal power for an onside kick.",why:"Surprise onside kicks have the highest recovery rate. Use when least expected."},
    {level:"expert",section:"Special Teams",title:"Fake Punt / FG",controls:["Audible in special teams"],desc:"Audible from punt or field goal formation to a pass or run play.",why:"If the defense isn't set, fake kicks convert at a high rate and are momentum changers."}
  ]
},
{
  id:"nba2k",name:`NBA 2K${NEXT_YEAR}`,yearlyUpdate:true,genre:"Sports / Basketball",category:"sports",icon:"🏀",color:"#c44b16",
  desc:`Dominate the court in NBA 2K${NEXT_YEAR}. From basic shots to advanced dribble god combos and lockdown defense.`,
  tags:["Sports","Basketball","Multiplayer","MyCareer"],
  tips:[
    {level:"beginner",section:"Offense",title:"Shoot (Button)",controls:["□"],desc:"Press and release Square to shoot. Release at the top of the jump for best timing.",why:"Green releases are perfect. Practice in MyCourt until the timing is muscle memory."},
    {level:"beginner",section:"Offense",title:"Shoot (Pro Stick)",controls:["Right Stick down + release"],desc:"Pull right stick down and release for a shot. Aiming adds skill bonus.",why:"Pro Stick shooting gives a slight boost over button shooting when aimed correctly."},
    {level:"beginner",section:"Offense",title:"Pass",controls:["X"],desc:"Press X to pass to the nearest open teammate.",why:"Ball movement creates open shots. Look for the extra pass."},
    {level:"beginner",section:"Offense",title:"Bounce Pass",controls:["○"],desc:"Press Circle for a bounce pass that goes under defenders.",why:"Bounce passes are harder to intercept in traffic. Essential for feeding the post."},
    {level:"beginner",section:"Offense",title:"Lob Pass",controls:["△"],desc:"Press Triangle for a lob pass.",why:"Lobs over defenders but slower. Use for alley-oops and over zone defenses."},
    {level:"beginner",section:"Offense",title:"Sprint",controls:["R2"],desc:"Hold R2 to sprint.",why:"Drains stamina fast. Don't hold it the entire time — tired players miss shots."},
    {level:"beginner",section:"Offense",title:"Call for Screen",controls:["L1"],desc:"Press L1 to call for a pick and roll.",why:"Pick and roll is the foundation of basketball offense. Creates mismatches every time."},
    {level:"beginner",section:"Offense",title:"Post Up",controls:["L2 near basket"],desc:"Hold L2 near the basket to back down your defender.",why:"Dominant with big men. Opens hooks, fades, drop steps, and kick-outs."},
    {level:"beginner",section:"Defense",title:"Intense D",controls:["L2"],desc:"Hold L2 for an intense defensive stance.",why:"Moves laterally faster and contests shots better. Always hold this on-ball."},
    {level:"beginner",section:"Defense",title:"Block",controls:["△"],desc:"Press Triangle near a shooter to attempt a block.",why:"Even without blocking, a contest drops their percentage significantly."},
    {level:"beginner",section:"Defense",title:"Steal",controls:["□"],desc:"Press Square to reach for a steal.",why:"Don't spam — mistimed steals cause reach-in fouls. Use when the ball is exposed."},
    {level:"intermediate",section:"Offense",title:"Euro Step",controls:["Right Stick left/right while driving"],desc:"While driving, flick right stick to the off-hand side for a Euro step.",why:"Avoids charges and gets around shot blockers. Elite finishing move."},
    {level:"intermediate",section:"Offense",title:"Alley-Oop",controls:["Double-tap △"],desc:"Double tap Triangle while a teammate cuts to throw an alley-oop.",why:"High success with athletic bigs. Look for it on fast breaks."},
    {level:"intermediate",section:"Offense",title:"Pump Fake",controls:["□ (quick tap)"],desc:"Quick tap Square to pump fake.",why:"Gets defenders in the air. Step through for an open layup or draw the foul."},
    {level:"intermediate",section:"Offense",title:"Hop Step",controls:["□ while driving (tap)"],desc:"Tap Square while driving for a hop step gather.",why:"Creates space for a shot or pass. Can't be stripped during the hop."},
    {level:"intermediate",section:"Offense",title:"Floater",controls:["Right Stick forward (close range)"],desc:"Flick right stick forward in the lane for a floater.",why:"Goes over shot blockers. Essential for small guards against bigs."},
    {level:"intermediate",section:"Offense",title:"Icon Pass",controls:["R1 + player icon"],desc:"Press R1 then the icon of the specific player you want to pass to.",why:"Precise passing. Skip the AI's choice and get it to exactly who you want."},
    {level:"intermediate",section:"Offense",title:"Pick and Fade",controls:["L1 then R1"],desc:"Call screen with L1, then press R1 to make the screener pop to the perimeter.",why:"If your big can shoot, the pick and pop is devastating against drop coverage."},
    {level:"intermediate",section:"Defense",title:"Take Charge",controls:["○"],desc:"Press Circle to plant your feet and attempt to draw a charge.",why:"High IQ play. Position yourself in the driving lane before they start their move."},
    {level:"intermediate",section:"Defense",title:"Icon Switch",controls:["R1 + player icon"],desc:"Press R1 then the icon of the player you want to control.",why:"Switch to the best defender or whoever is guarding the ball handler."},
    {level:"intermediate",section:"Defense",title:"Double Team",controls:["L1 (hold on-ball)"],desc:"Hold L1 while guarding the ball handler to send a double team.",why:"Traps ball handlers but leaves someone open. Use in the post or against weak passers."},
    {level:"advanced",section:"Dribbling",title:"Crossover",controls:["Right Stick left/right"],desc:"Flick right stick opposite your dribble hand for a crossover.",why:"The foundation of dribble moves. Creates space laterally."},
    {level:"advanced",section:"Dribbling",title:"Behind the Back",controls:["Right Stick down-left or down-right"],desc:"Flick right stick diagonally backward for a behind-the-back move.",why:"Protects the ball while changing direction. Harder to steal than a crossover."},
    {level:"advanced",section:"Dribbling",title:"Stepback",controls:["R2 + Right Stick down"],desc:"While holding sprint, pull right stick back for a stepback jumper.",why:"Creates instant separation for a three-pointer. The Harden special."},
    {level:"advanced",section:"Offense",title:"Shot Cancel",controls:["□ then ○ quickly"],desc:"Start a shot and press Circle to cancel.",why:"Bait defenders into jumping then drive past them. Elite footwork tool."},
    {level:"advanced",section:"Offense",title:"Flashy Pass",controls:["Double-tap ○"],desc:"Double tap Circle for a faster, riskier pass.",why:"Gets the ball there quicker in tight windows. Speed can be the difference."},
    {level:"advanced",section:"Defense",title:"Defensive Settings",controls:["D-Pad left → settings"],desc:"Access on-ball pressure, help defense, switch rules, and hedge settings.",why:"Set tight on-ball vs shooters, go over/under screens. Team settings win games."},
    {level:"advanced",section:"Defense",title:"Off-Ball Steal",controls:["□ in passing lane"],desc:"Press Square in a passing lane to deflect the ball.",why:"Anticipate passes and jump the lane for easy steals and fast breaks."},
    {level:"expert",section:"Dribbling",title:"Speed Boost",controls:["Right Stick flick + R2"],desc:"Flick right stick for a size-up then immediately hold R2 to speed boost out.",why:"Creates instant separation. Requires high ball handle. Foundation of elite iso play."},
    {level:"expert",section:"Dribbling",title:"Snatchback",controls:["Right Stick down while moving"],desc:"Pull right stick back while dribbling to snatch the ball back.",why:"Creates space for a pull-up three. Deadly with quick release badges."},
    {level:"expert",section:"Offense",title:"Manual Cut",controls:["Hold ○ + Left Stick toward basket"],desc:"Off-ball, hold Circle and drive toward the basket for a manual cut.",why:"AI cuts are predictable. Manual cuts catch the defense sleeping for easy baskets."},
    {level:"expert",section:"Offense",title:"Give and Go",controls:["X (pass) then hold X"],desc:"Pass then hold X to immediately cut to the basket for a return pass.",why:"Simple but effective. The AI rarely defends the give and go properly."},
    {level:"expert",section:"Defense",title:"Rim Protector Timing",controls:["△ (hold + release)"],desc:"Hold Triangle and release at the apex of the shooter's jump.",why:"Timed blocks activate chase-down and pin animations. Don't just mash it."},
    {level:"expert",section:"Defense",title:"Bait Passing Lanes",controls:["Sag off then jump lane"],desc:"Intentionally sag off your man to bait a pass, then jump the lane with Square.",why:"The highest IQ defensive play. Creates turnovers that lead to fast break points."}
  ]
},
{
  id:"fc",name:`EA Sports FC ${CURRENT_YEAR}`,yearlyUpdate:true,genre:"Sports / Soccer",category:"sports",icon:"⚽",color:"#1a6b3c",
  desc:`Master skill moves, set pieces, and tactical defending in EA FC ${CURRENT_YEAR}. Every control from basic to elite.`,
  tags:["Sports","Soccer","Ultimate Team","Multiplayer"],
  tips:[
    {level:"beginner",section:"Passing",title:"Ground Pass",controls:["X"],desc:"Press X to make a ground pass. Hold longer for more power.",why:"Short passing builds possession. Tap for short, hold for long range."},
    {level:"beginner",section:"Passing",title:"Through Ball",controls:["△"],desc:"Press Triangle to play a through ball into space ahead of a runner.",why:"The most dangerous pass. Time it when your striker starts their run."},
    {level:"beginner",section:"Passing",title:"Lob Pass",controls:["□"],desc:"Press Square for a lofted pass over defenders.",why:"Switches play to the opposite wing. Beats high press defenses."},
    {level:"beginner",section:"Passing",title:"Cross",controls:["□ in wide areas"],desc:"Press Square near the byline to whip in a cross.",why:"Crosses to tall strikers are lethal. Aim for the far post."},
    {level:"beginner",section:"Shooting",title:"Shoot",controls:["○"],desc:"Press Circle to shoot. Hold longer for more power. 2-3 bars from inside the box.",why:"Aim for far post in most situations. Power control is everything."},
    {level:"beginner",section:"Movement",title:"Sprint",controls:["R2"],desc:"Hold R2 to sprint with the ball.",why:"Sprinting reduces ball control. Only sprint in open space, not in tight areas."},
    {level:"beginner",section:"Movement",title:"Protect Ball",controls:["L2"],desc:"Hold L2 to shield the ball from defenders.",why:"Buys time for teammates to make runs. Essential when pressured."},
    {level:"beginner",section:"Defense",title:"Tackle",controls:["○"],desc:"Press Circle for a standing tackle.",why:"Time your tackles — mistimed ones give fouls in dangerous areas."},
    {level:"beginner",section:"Defense",title:"Switch Player",controls:["L1"],desc:"Press L1 to switch to another player.",why:"Don't chase with one defender. Switch to cut passing lanes."},
    {level:"beginner",section:"Defense",title:"Jockey",controls:["L2"],desc:"Hold L2 to jockey — stay goal-side and track the attacker.",why:"Don't dive in. Jockeying forces the attacker to make the first move."},
    {level:"intermediate",section:"Passing",title:"Driven Pass",controls:["R1 + X"],desc:"R1+X for a fast, low driven pass.",why:"Cuts through traffic faster. Essential for quick counters and one-touch play."},
    {level:"intermediate",section:"Passing",title:"Lob Through Ball",controls:["L1 + △"],desc:"L1+Triangle for an aerial through ball over the defense.",why:"Exploits high defensive lines. Perfect for pacey wingers."},
    {level:"intermediate",section:"Shooting",title:"Finesse Shot",controls:["R1 + ○"],desc:"R1+Circle for a curling finesse shot.",why:"Deadly from the edge of the box curling to far post on the strong foot."},
    {level:"intermediate",section:"Shooting",title:"Chip Shot",controls:["L1 + ○"],desc:"L1+Circle to chip the ball over an advancing keeper.",why:"When the keeper rushes out, a chip is almost unstoppable."},
    {level:"intermediate",section:"Shooting",title:"Driven Shot",controls:["L1 + R1 + ○"],desc:"L1+R1+Circle for a low driven shot.",why:"Stays low and hard. Keepers struggle to save these."},
    {level:"intermediate",section:"Skills",title:"Ball Roll",controls:["Right Stick hold sideways"],desc:"Hold right stick left or right to roll the ball past a defender.",why:"Simple but incredibly effective. Creates space without losing the ball."},
    {level:"intermediate",section:"Skills",title:"Fake Shot",controls:["○ then X quickly"],desc:"Start a shot then quickly press X to cancel into a fake shot.",why:"Sends keeper and defenders wrong way. One of the most versatile moves."},
    {level:"intermediate",section:"Skills",title:"Drag Back",controls:["R1 + Left Stick back"],desc:"R1+pull left stick back to drag the ball behind you.",why:"Quick direction change. Great for creating shooting angles."},
    {level:"intermediate",section:"Defense",title:"Sliding Tackle",controls:["□"],desc:"Press Square for a sliding tackle.",why:"Risky — miss and you're out of position. Use as last resort or in the box."},
    {level:"intermediate",section:"Defense",title:"Second Man Press",controls:["R1"],desc:"Hold R1 to have an AI teammate pressure while you jockey.",why:"Creates a 2v1 against the ball carrier. The meta defensive strategy."},
    {level:"advanced",section:"Shooting",title:"Timed Finishing",controls:["○ then ○ again"],desc:"Press shoot, then press again as your player strikes the ball for a power boost.",why:"Green timed = more power/accuracy. Red = worse. High risk/reward."},
    {level:"advanced",section:"Skills",title:"Elastico",controls:["Right Stick → then ← quickly (4★+)"],desc:"Flick from ball-side to off-side rapidly.",why:"One of the best 1v1 moves. Changes direction instantly."},
    {level:"advanced",section:"Skills",title:"La Croqueta",controls:["L1 + Right Stick sideways (4★+)"],desc:"Quick lateral shift of the ball between feet.",why:"Tiny movement but enough to beat a jockeying defender at close range."},
    {level:"advanced",section:"Skills",title:"Berba Spin",controls:["Right Stick forward then sideways (4★+)"],desc:"Touch ball forward then spin 90 degrees.",why:"Great for turning the corner from wing into the box."},
    {level:"advanced",section:"Movement",title:"Tactical Sprint",controls:["R2 double-tap"],desc:"Double-tap R2 for an explosive sprint burst.",why:"Knocks ball ahead for max speed. Best in open space on the counter."},
    {level:"advanced",section:"Movement",title:"Player Lock",controls:["L3 + R3"],desc:"Click both sticks to lock onto your player and make manual runs.",why:"Make runs the CPU would never find. Create your own space."},
    {level:"advanced",section:"Defense",title:"Manual Switch",controls:["Right Stick flick"],desc:"Flick right stick toward the player you want.",why:"L1 switching is random. Right stick lets you pick exactly who."},
    {level:"advanced",section:"Defense",title:"Offside Trap",controls:["D-Pad up (twice)"],desc:"Push the defensive line up to catch attackers offside.",why:"Dangerous but effective against teams spamming through balls."},
    {level:"advanced",section:"Set Pieces",title:"Free Kick Aim",controls:["Left Stick + ○ (power) + Right Stick (spin)"],desc:"Aim with left stick, power with Circle, add spin with right stick after pressing shoot.",why:"Curling free kicks around the wall are scoreable from 20-30 yards."},
    {level:"expert",section:"Shooting",title:"Trivela Shot",controls:["L2 + ○ (outside foot angle)"],desc:"L2+shoot at an angle for an outside-of-the-foot shot.",why:"Unpredictable trajectory keepers can't read. Devastating with the right players."},
    {level:"expert",section:"Skills",title:"Directional Nutmeg",controls:["L1 + R1 + Right Stick"],desc:"Hold L1+R1 and flick right stick toward a defender to nutmeg them.",why:"Completely beats the defender if it connects. Game-changing in the box."},
    {level:"expert",section:"Skills",title:"Skill Cancel",controls:["L2 + R2 during skill"],desc:"Press L2+R2 during any skill move to cancel the animation.",why:"Start an Elastico, cancel it, go the other way. The ultimate mind game."},
    {level:"expert",section:"Tactics",title:"Custom Tactics",controls:["D-Pad up/down for presets"],desc:"Set up 4 tactical presets and switch mid-game.",why:"Switch defensive to ultra-attacking without pausing. React to game state instantly."},
    {level:"expert",section:"Tactics",title:"Manual Controls",controls:["Assisted → Semi → Manual in settings"],desc:"Switch passing/shooting to manual for full control.",why:"Manual gives 100% control over direction and power. The skill ceiling is infinite."},
    {level:"expert",section:"Set Pieces",title:"Short Corner Routine",controls:["Call short → pass → cross/shoot"],desc:"Call a player short on corners for a quick pass before crossing.",why:"Bypasses the entire set-piece defense. Creates open shots at the edge of the box."}
  ]
},
{
  id:"mlb",name:`MLB The Show ${CURRENT_YEAR}`,yearlyUpdate:true,genre:"Sports / Baseball",category:"sports",icon:"⚾",color:"#002d72",
  desc:`Hit dingers, paint corners, and make diving catches. Every batting, pitching, and fielding control.`,
  tags:["Sports","Baseball","Multiplayer","Diamond Dynasty"],
  tips:[
    {level:"beginner",section:"Batting",title:"Normal Swing",controls:["X"],desc:"Press X for a normal swing with balanced power and contact.",why:"The safest swing. Use this until you're comfortable with timing."},
    {level:"beginner",section:"Batting",title:"Power Swing",controls:["□"],desc:"Press Square for a power swing with more home run potential.",why:"Smaller sweet spot but more exit velocity. Use on hitter's counts."},
    {level:"beginner",section:"Batting",title:"Contact Swing",controls:["○"],desc:"Press Circle for maximum contact chance, less power.",why:"Use with 2 strikes to protect the plate. Fouls off tough pitches."},
    {level:"beginner",section:"Batting",title:"Bunt",controls:["△"],desc:"Press Triangle to bunt the ball.",why:"Sacrifice bunts advance runners. Drag bunts with fast players can be hits."},
    {level:"beginner",section:"Batting",title:"Check Swing",controls:["Release button early"],desc:"Start swinging but release before committing.",why:"Saved check swings prevent strikeouts. The ump may still call it a swing."},
    {level:"beginner",section:"Pitching",title:"Select Pitch",controls:["Right Stick / buttons"],desc:"Choose your pitch type from the selection menu.",why:"Mix pitches. Never throw the same pitch twice in a row."},
    {level:"beginner",section:"Pitching",title:"Aim Pitch",controls:["Left Stick"],desc:"Move the left stick to aim where you want to throw.",why:"Paint corners for strikes. Aim just off the plate for chases."},
    {level:"beginner",section:"Fielding",title:"Throw to Base",controls:["□(1B) △(2B) ○(3B) X(Home)"],desc:"After fielding, press the button corresponding to the base.",why:"Quick, accurate throws prevent extra bases. Pre-plan your throw before fielding."},
    {level:"beginner",section:"Fielding",title:"Dive / Jump",controls:["R1 (dive) / R2 (jump)"],desc:"R1 to dive for a ball, R2 to leap.",why:"Diving catches save hits. Timing is everything — too early and you miss."},
    {level:"beginner",section:"Baserunning",title:"Advance All",controls:["L1"],desc:"Press L1 to send all runners to the next base.",why:"Quick decision after a hit. Be aware of the outfielder's arm."},
    {level:"beginner",section:"Baserunning",title:"Retreat All",controls:["R1"],desc:"Press R1 to send all runners back to their base.",why:"If a fly ball is caught, runners must tag up. Retreat immediately."},
    {level:"intermediate",section:"Batting",title:"Zone Hitting",controls:["Left Stick + X/□/○"],desc:"Use left stick to position the PCI (reticle) over the pitch location before swinging.",why:"Zone hitting has the highest skill ceiling. Centering the PCI = crushed ball."},
    {level:"intermediate",section:"Batting",title:"Directional Hitting",controls:["Left Stick direction + swing"],desc:"Hold a direction while swinging to influence hit direction (pull/push/up).",why:"Easier than zone but less precise. Good for situational hitting."},
    {level:"intermediate",section:"Pitching",title:"Pinpoint Pitching",controls:["Right Stick gestures"],desc:"Trace the gesture shown on screen with the right stick, then follow through.",why:"Most accurate pitching method. Perfect gestures = perfect location."},
    {level:"intermediate",section:"Pitching",title:"Meter Pitching",controls:["X (start) → X (power) → X (accuracy)"],desc:"Press X three times: start, set power, set accuracy.",why:"Simpler than pinpoint. Land in the green zones for best results."},
    {level:"intermediate",section:"Fielding",title:"Cut-Off Throw",controls:["L1 + throw button"],desc:"Throw to the cut-off man instead of all the way to the base.",why:"Faster relay. Prevents overthrows and runners advancing on errors."},
    {level:"intermediate",section:"Baserunning",title:"Steal",controls:["L2"],desc:"Press L2 to attempt a steal when on base.",why:"Only steal with fast runners (80+ speed). Watch the pitcher's pickoff tendency."},
    {level:"intermediate",section:"Baserunning",title:"Hit and Run",controls:["L2 + swing"],desc:"Start the steal then swing at anything to protect the runner.",why:"Moves the runner and creates holes in the infield. Classic small ball."},
    {level:"advanced",section:"Batting",title:"Sit on a Pitch",controls:["Anticipate location + swing early/late"],desc:"Guess the pitch type and location before it's thrown. Pre-position your PCI.",why:"Top hitters sit on fastballs and react to off-speed. Cuts reaction time in half."},
    {level:"advanced",section:"Pitching",title:"Pitch Tunneling",controls:["Same release point, different movement"],desc:"Throw pitches that look identical out of the hand but break differently.",why:"Fastball up, change-up down with the same tunnel = unhittable combo."},
    {level:"advanced",section:"Pitching",title:"Pickoff Move",controls:["L1 + base button"],desc:"Press L1 + the base to throw a pickoff attempt.",why:"Keeps runners close. Vary timing — predictable pickoffs get ignored."},
    {level:"advanced",section:"Defense",title:"Defensive Shift",controls:["D-Pad → shift options"],desc:"Shift your fielders to match hitter tendencies.",why:"Pull shift against dead-pull hitters. Standard against balanced hitters."},
    {level:"expert",section:"Batting",title:"PCI Anchor Points",controls:["Pre-position PCI middle-up"],desc:"Start your PCI slightly up and react down, rather than starting center.",why:"Reacting up to a fastball is nearly impossible online. Anchor up, adjust down."},
    {level:"expert",section:"Pitching",title:"Back Door Slider",controls:["Start off plate → break back in"],desc:"Aim a slider outside that breaks back over the corner.",why:"Looks like a ball, becomes a strike. The most effective strikeout pitch in the game."},
    {level:"expert",section:"Baserunning",title:"Delayed Steal",controls:["Wait for catcher's throw back, then steal"],desc:"Start your steal as the catcher lobs the ball back to the pitcher.",why:"Catches the defense off guard. Works in situations where a normal steal wouldn't."}
  ]
},
{
  id:"nhl",name:`NHL ${CURRENT_YEAR}`,yearlyUpdate:true,genre:"Sports / Hockey",category:"sports",icon:"🏒",color:"#041e42",
  desc:`Hit the ice with every skating, shooting, and defensive control mastered.`,
  tags:["Sports","Hockey","Multiplayer","HUT"],
  tips:[
    {level:"beginner",section:"Skating",title:"Skate",controls:["Left Stick"],desc:"Move with the left stick. Speed depends on how far you push it.",why:"Skating is everything. Master acceleration and turning before anything else."},
    {level:"beginner",section:"Skating",title:"Sprint / Hustle",controls:["R2 (hold)"],desc:"Hold R2 for a burst of speed.",why:"Drains energy faster. Use in short bursts, not constantly."},
    {level:"beginner",section:"Offense",title:"Wrist Shot",controls:["Right Stick up (quick)"],desc:"Flick right stick up for a quick wrist shot.",why:"Fast release, good accuracy. Your go-to shot from the slot."},
    {level:"beginner",section:"Offense",title:"Slap Shot",controls:["Right Stick down then up"],desc:"Pull right stick back then push forward for a slap shot.",why:"Most power but slowest wind-up. Use on the power play from the point."},
    {level:"beginner",section:"Offense",title:"Pass",controls:["R1"],desc:"Press R1 to pass. Aim with left stick.",why:"Quick, tape-to-tape passes are the foundation of offense."},
    {level:"beginner",section:"Defense",title:"Poke Check",controls:["R1"],desc:"Press R1 to poke check the puck away.",why:"Safest defensive move. Reach in without committing your body."},
    {level:"beginner",section:"Defense",title:"Body Check",controls:["Right Stick toward opponent"],desc:"Push right stick toward an opponent to hip check or body check them.",why:"Physical play but risky. Missed checks = odd-man rush the other way."},
    {level:"beginner",section:"Defense",title:"Switch Player",controls:["L1"],desc:"Press L1 to switch to the nearest defender.",why:"Let the AI forecheck and control your D-men to stay in position."},
    {level:"intermediate",section:"Offense",title:"One-Timer",controls:["Pass → R1 to teammate → Right Stick up (recipient)"],desc:"Pass to a teammate in shooting position who immediately shoots with right stick.",why:"The most dangerous shot in hockey. Cross-crease one-timers are nearly unstoppable."},
    {level:"intermediate",section:"Offense",title:"Snap Shot",controls:["Right Stick up (hold slightly)"],desc:"A quicker version between wrist and slap shot.",why:"Good balance of speed and power. Great from the circles."},
    {level:"intermediate",section:"Offense",title:"Deke",controls:["Left Stick direction while skating"],desc:"Move the puck with the left stick while skating to deke around defenders.",why:"Deking past a defender creates odd-man rushes and open shots."},
    {level:"intermediate",section:"Offense",title:"Saucer Pass",controls:["L1 + R1"],desc:"Press L1+R1 for a pass that floats over sticks.",why:"Goes over poke checks and sticks. Essential when passing lanes are blocked."},
    {level:"intermediate",section:"Defense",title:"Stick Lift",controls:["L1 (on-ball defense)"],desc:"Press L1 to lift the opponent's stick.",why:"Less risky than a poke check but only works when close behind the puck carrier."},
    {level:"intermediate",section:"Defense",title:"Block Shot",controls:["○"],desc:"Press Circle to drop and block a shot.",why:"Blocking shots in front of the net is crucial on the penalty kill."},
    {level:"intermediate",section:"Goalie",title:"Goalie Movement",controls:["Left Stick (move) / R2 (hug post)"],desc:"Move with left stick, press R2 to hug the nearest post.",why:"Post-to-post movement stops cross-crease plays. Stay square to the puck."},
    {level:"advanced",section:"Offense",title:"Between-the-Legs",controls:["R1 + Left Stick through legs"],desc:"Deke the puck between your legs while skating.",why:"Style points AND effective. Goes under poke checks."},
    {level:"advanced",section:"Offense",title:"Michigan / Lacrosse Goal",controls:["Hold Right Stick back + scoop around"],desc:"Pick the puck up on your stick blade and tuck it from behind the net.",why:"Nearly impossible to save when executed. The flashiest goal in hockey."},
    {level:"advanced",section:"Offense",title:"Protect Puck",controls:["L2 + skate"],desc:"Hold L2 to use your body to shield the puck.",why:"Prevents poke checks. Use along the boards to maintain possession."},
    {level:"advanced",section:"Strategy",title:"Line Changes",controls:["L1 (hold)"],desc:"Hold L1 for a full line change during play.",why:"Fresh legs are faster and hit harder. Change when you have safe possession."},
    {level:"advanced",section:"Strategy",title:"Faceoff Technique",controls:["Right Stick directions"],desc:"Different right stick inputs win different types of faceoffs (tie up, forehand, backhand).",why:"Faceoff wins = possession. Learn what beats what based on opponent tendencies."},
    {level:"expert",section:"Offense",title:"Short-Side Snipe",controls:["Aim near post + wrist shot"],desc:"Aim for the short side (near post) with a quick wrist shot.",why:"The meta goal online. Short-side shots go in before the goalie reacts."},
    {level:"expert",section:"Offense",title:"Pull Goalie",controls:["Pause → pull goalie"],desc:"Replace your goalie with an extra attacker when trailing late.",why:"6v5 creates massive pressure. Only do it in the last 1-2 minutes when trailing."},
    {level:"expert",section:"Strategy",title:"Cycle Play",controls:["Pass behind net → to point → back down low"],desc:"Move the puck in a triangle from behind the net to the point and back.",why:"Tires the defense and creates cross-crease one-timer opportunities."}
  ]
},
{
  id:"ufc5",name:"UFC 5",genre:"Sports / Fighting",category:"sports",icon:"🥊",color:"#8b0000",
  desc:"Step into the Octagon. Striking, grappling, clinch, and ground game mastery.",
  tags:["Sports","Fighting","MMA","Multiplayer"],
  tips:[
    {level:"beginner",section:"Striking",title:"Jab",controls:["□"],desc:"Press Square for a quick jab.",why:"Fastest strike. Use to set up combos and keep distance."},
    {level:"beginner",section:"Striking",title:"Cross / Straight",controls:["△"],desc:"Press Triangle for a straight right (or left if southpaw).",why:"More power than jab, slower. The finisher of basic combos."},
    {level:"beginner",section:"Striking",title:"Hook",controls:["L1 + □ or △"],desc:"Hold L1 and press Square or Triangle for hooks.",why:"Hooks go around the guard. Target the body to drain stamina."},
    {level:"beginner",section:"Striking",title:"Uppercut",controls:["L1 + R1 + □ or △"],desc:"Hold L1+R1 and press Square or Triangle for uppercuts.",why:"Uppercuts catch ducking opponents. Devastating in the clinch."},
    {level:"beginner",section:"Striking",title:"Leg Kick",controls:["L2 + ○ or X"],desc:"Hold L2 and press Circle or X for leg kicks.",why:"Leg kicks drain mobility over time. Three good leg kicks slows them significantly."},
    {level:"beginner",section:"Defense",title:"Block",controls:["R2 (high) / R2 + L2 (low)"],desc:"Hold R2 to block high, add L2 to block low.",why:"Blocking reduces damage dramatically. Always block when not attacking."},
    {level:"beginner",section:"Movement",title:"Move / Footwork",controls:["Left Stick"],desc:"Move around the octagon with the left stick.",why:"Angles and distance management are everything. Don't stand still."},
    {level:"intermediate",section:"Striking",title:"Head Kicks",controls:["L1 + ○ or X"],desc:"Hold L1 and press Circle or X for head kicks.",why:"Head kicks can cause flash KOs. High risk but fight-ending reward."},
    {level:"intermediate",section:"Striking",title:"Body Kicks",controls:["○ or X"],desc:"Press Circle or X for body kicks.",why:"Body kicks drain stamina fast. A tired opponent can't defend takedowns."},
    {level:"intermediate",section:"Striking",title:"Spinning Attacks",controls:["L1 + L2 + strike"],desc:"Hold L1+L2 while throwing for spinning variations.",why:"Spinning back fist and spinning heel kick have KO power but are very punishable if whiffed."},
    {level:"intermediate",section:"Defense",title:"Head Movement",controls:["Right Stick"],desc:"Flick right stick to slip, duck, or lean away from strikes.",why:"Makes strikes whiff completely. Countering after a slip does extra damage."},
    {level:"intermediate",section:"Defense",title:"Parry",controls:["L1 + R1 timed with strike"],desc:"Press L1+R1 just before a strike lands to parry it.",why:"Stuns the opponent briefly. Perfect parries open huge counter windows."},
    {level:"intermediate",section:"Defense",title:"Check Leg Kicks",controls:["L2 + R2"],desc:"Hold L2+R2 to check incoming leg kicks.",why:"Checked leg kicks damage the kicker. Can break their leg over time."},
    {level:"intermediate",section:"Grappling",title:"Takedown",controls:["L2 + △ or □"],desc:"Hold L2 and press Triangle (single leg) or Square (double leg).",why:"Taking the fight to the ground neutralizes strikers."},
    {level:"intermediate",section:"Grappling",title:"Takedown Defense",controls:["R2 + △ or □ timed"],desc:"Time your sprawl with R2 + the button as the takedown comes in.",why:"Stuffing takedowns demoralizes wrestlers and keeps the fight standing."},
    {level:"advanced",section:"Grappling",title:"Ground Transitions",controls:["Right Stick directions on ground"],desc:"Use right stick to transition between positions on the ground.",why:"Advancing position gives you better strikes and submission opportunities."},
    {level:"advanced",section:"Grappling",title:"Deny Transitions",controls:["Right Stick match opponent's direction"],desc:"Match your right stick to the opponent's transition to block it.",why:"Stopping transitions frustrates grapplers and drains their stamina."},
    {level:"advanced",section:"Grappling",title:"Submissions",controls:["L2 + R2 on ground → mini-game"],desc:"Initiate a submission and win the mini-game to finish the fight.",why:"Submissions can end a fight from any position. Always threaten them on the ground."},
    {level:"advanced",section:"Striking",title:"Feints",controls:["L2 + strike button (quick tap)"],desc:"Quickly tap L2 + a strike button to feint without throwing.",why:"Feints make the opponent react to nothing. Follow with a real strike."},
    {level:"advanced",section:"Clinch",title:"Clinch Entry",controls:["L2 + R2 + X or □ up close"],desc:"Initiate the clinch when in close range.",why:"The clinch neutralizes range fighters and opens knees, elbows, and takedowns."},
    {level:"expert",section:"Striking",title:"Counter KOs",controls:["Slip + immediate power shot"],desc:"Slip a strike then immediately counter with a hook or uppercut.",why:"Counter shots do bonus damage. Most flash KOs come from perfectly timed counters."},
    {level:"expert",section:"Grappling",title:"Submission Chain",controls:["Transition → immediate submission attempt"],desc:"Advance position then immediately attempt a submission before they can react.",why:"Chaining transitions into subs gives almost no time to defend. Elite ground game."},
    {level:"expert",section:"Strategy",title:"Body Work → Head",controls:["Go body early → head late"],desc:"Invest in body shots in rounds 1-2, then go to the head in later rounds.",why:"A fighter with no stamina can't block. Body work early pays dividends in later rounds."}
  ]
},
{
  id:"wwe2k",name:`WWE 2K${NEXT_YEAR}`,yearlyUpdate:true,genre:"Sports / Wrestling",category:"sports",icon:"💪",color:"#d4af37",
  desc:"Enter the ring. Grapples, finishers, reversals, and every match type mastered.",
  tags:["Sports","Wrestling","Multiplayer","MyRise"],
  tips:[
    {level:"beginner",section:"Offense",title:"Light Attack / Strike",controls:["□"],desc:"Press Square for quick strikes.",why:"Strikes are fast and build damage for grapple moves."},
    {level:"beginner",section:"Offense",title:"Grapple",controls:["○"],desc:"Press Circle to initiate a grapple.",why:"Grapples lead to your most damaging moves. Mix between light and heavy."},
    {level:"beginner",section:"Offense",title:"Heavy Attack",controls:["X"],desc:"Press X for a heavy strike or grapple move.",why:"Slower but more damage. Use when the opponent is stunned."},
    {level:"beginner",section:"Offense",title:"Irish Whip",controls:["○ + direction"],desc:"Grapple then push toward the ropes to Irish Whip.",why:"Sets up running attacks, corner moves, and environmental hazards."},
    {level:"beginner",section:"Offense",title:"Pin",controls:["Right Stick down near downed opponent"],desc:"Push right stick down near a grounded opponent to attempt a pin.",why:"You can only win by pin (or submission). Attempt pins after big moves."},
    {level:"beginner",section:"Defense",title:"Reversal",controls:["△"],desc:"Press Triangle at the right moment to reverse an opponent's move.",why:"Reversals are the core of WWE 2K. Timing is everything — flash when available."},
    {level:"beginner",section:"Defense",title:"Kick Out of Pin",controls:["Timing mini-game"],desc:"Hit the button in the zone during the pin kick-out mini-game.",why:"Failing to kick out = you lose. Practice the timing — it gets harder as damage increases."},
    {level:"intermediate",section:"Offense",title:"Signature Move",controls:["△ + ○ when prompted"],desc:"When your signature is available, trigger it near your opponent.",why:"Signatures are powerful and build toward your Finisher."},
    {level:"intermediate",section:"Offense",title:"Finisher",controls:["R2 + X when meter full"],desc:"Activate your finisher when the meter is full for a devastating move.",why:"Finishers almost always lead to a successful pin. Save it for the right moment."},
    {level:"intermediate",section:"Offense",title:"Running Attack",controls:["R2 (sprint) + □"],desc:"Sprint with R2 then press Square for a running strike.",why:"Running attacks close distance fast and catch opponents off guard."},
    {level:"intermediate",section:"Offense",title:"Diving Attack",controls:["Climb turnbuckle + X or □"],desc:"Climb the turnbuckle and press an attack button to dive.",why:"High-flying moves deal huge damage but miss if they roll away."},
    {level:"intermediate",section:"Offense",title:"Weapon Attack",controls:["Pick up + □ or X"],desc:"Pick up a weapon (in no-DQ matches) and strike.",why:"Weapons multiply damage. Chairs, tables, ladders, kendo sticks — all devastating."},
    {level:"intermediate",section:"Grapple",title:"Submission",controls:["○ near downed opponent + mini-game"],desc:"Initiate a submission hold and win the mini-game to tap them out.",why:"Submissions are an alternative win condition. Work the body part first."},
    {level:"intermediate",section:"Grapple",title:"Corner Moves",controls:["Irish Whip to corner → attack"],desc:"Whip opponent to the corner then run in with an attack.",why:"Corner-trapped opponents can't reverse. Free damage opportunity."},
    {level:"advanced",section:"Offense",title:"Springboard Attack",controls:["Run to ropes + L1"],desc:"Run toward the ropes and press L1 for a springboard move.",why:"Springboard attacks are fast and hard to reverse. Great for cruiserweights."},
    {level:"advanced",section:"Offense",title:"OMG Moment",controls:["R2 + △ near environment trigger"],desc:"Trigger an OMG moment for a cinematic environmental attack.",why:"OMG moments deal massive damage and are crowd pleasers."},
    {level:"advanced",section:"Match Types",title:"Ladder Match",controls:["Set up ladder + climb + mini-game"],desc:"Position ladder under the title, climb, and win the grab mini-game.",why:"In ladder matches, damage your opponent enough that they can't interrupt your climb."},
    {level:"advanced",section:"Match Types",title:"Royal Rumble",controls:["Irish Whip to ropes → elimination mini-game"],desc:"Whip opponents to the ropes and trigger the elimination sequence.",why:"Manage your stamina. Let others fight and pick off weakened opponents."},
    {level:"expert",section:"Defense",title:"Reversal Management",controls:["Save reversals for big moves"],desc:"You have limited reversals. Don't waste them on light attacks — save for finishers.",why:"Reversing a finisher swings the entire match. That's worth 10 light attack reversals."},
    {level:"expert",section:"Strategy",title:"Limb Targeting",controls:["Focus attacks on one body part"],desc:"Target the same body part repeatedly to weaken it, then apply a submission to that limb.",why:"A damaged arm makes punches weaker. Damaged legs slow movement. Then submit the damaged part."},
    {level:"expert",section:"Strategy",title:"Payback Abilities",controls:["D-Pad when meter fills"],desc:"Use Payback abilities (poison mist, low blow, etc.) at critical moments.",why:"Paybacks can turn a losing match around. Save them for when you're in deep trouble."}
  ]
},
{
  id:"pga",name:`PGA Tour 2K${NEXT_YEAR}`,genre:"Sports / Golf",category:"sports",icon:"⛳",color:"#006747",
  desc:"Master the links. Swing mechanics, putting, and course management for every situation.",
  tags:["Sports","Golf","Simulation","Multiplayer"],
  tips:[
    {level:"beginner",section:"Swing",title:"Basic Swing",controls:["Right Stick back → forward"],desc:"Pull right stick back then push forward for your swing. Tempo matters.",why:"Smooth, even tempo produces straight shots. Jerky inputs cause hooks and slices."},
    {level:"beginner",section:"Swing",title:"Club Selection",controls:["L1 / R1"],desc:"Press L1/R1 to switch clubs.",why:"Use the right club for the distance. The game suggests one — trust it for now."},
    {level:"beginner",section:"Swing",title:"Aim",controls:["Left Stick"],desc:"Move left stick to adjust aim direction.",why:"Account for wind, elevation, and slopes when aiming."},
    {level:"beginner",section:"Putting",title:"Putt",controls:["Right Stick (gentle)"],desc:"Gentle right stick movement for putting. Distance = how far you pull back.",why:"Read the green grid lines. Putt uphill hard, downhill soft."},
    {level:"beginner",section:"Putting",title:"Read Green",controls:["Left Stick to view break"],desc:"Move the camera to read the green's slope before putting.",why:"The grid overlay shows you exactly which way the ball will break."},
    {level:"intermediate",section:"Swing",title:"Power Shot",controls:["R2 + swing"],desc:"Hold R2 before swinging for extra distance (limited uses per round).",why:"Use on long par 5s to reach in two. Don't waste them on holes you can reach normally."},
    {level:"intermediate",section:"Swing",title:"Backspin / Topspin",controls:["Left Stick down (back) / up (top) during swing"],desc:"Add spin by holding left stick during your swing.",why:"Backspin stops the ball on the green. Topspin adds roll for extra distance."},
    {level:"intermediate",section:"Swing",title:"Draw / Fade",controls:["Left Stick left (draw) / right (fade)"],desc:"Shape your shot to curve around obstacles.",why:"Draws and fades work with the wind or around trees and doglegs."},
    {level:"intermediate",section:"Strategy",title:"Punch Shot",controls:["D-Pad down for low trajectory"],desc:"Use a punch shot under trees or into wind.",why:"Low shots under tree branches save penalty strokes."},
    {level:"intermediate",section:"Strategy",title:"Flop Shot",controls:["D-Pad up for high trajectory"],desc:"High, soft shot that lands and stops quickly.",why:"Essential for getting over bunker lips onto tight pin positions."},
    {level:"advanced",section:"Swing",title:"Wind Compensation",controls:["Aim adjustment per mph"],desc:"Roughly 1 yard of aim adjustment per 1 mph of crosswind.",why:"Wind destroys scores if you ignore it. Read the wind arrow carefully."},
    {level:"advanced",section:"Swing",title:"Elevation Adjustment",controls:["Check elevation marker"],desc:"Add ~1% distance per foot of uphill, subtract for downhill.",why:"A 150-yard shot playing 10 feet uphill plays like 160 yards."},
    {level:"advanced",section:"Putting",title:"Speed Control",controls:["Practice pull-back distance"],desc:"Match your backstroke to the distance indicator line.",why:"Speed is more important than line on putts. Two-putt from anywhere with good speed control."},
    {level:"expert",section:"Strategy",title:"Course Management",controls:["Play to the fat of the green"],desc:"Don't always aim at the pin. Aim at the center of the green when pins are tucked.",why:"Avoiding bogeys is more important than making birdies. Smart targets = lower scores."},
    {level:"expert",section:"Strategy",title:"Risk-Reward Par 5s",controls:["Evaluate layup vs go-for-it"],desc:"Sometimes laying up to your favorite wedge distance beats going for the green.",why:"A confident wedge from 100y beats a prayer from 240y. Know your strengths."}
  ]
},
{
  id:"tonyhawk",name:"Tony Hawk's Pro Skater 1+2",genre:"Sports / Skateboarding",category:"sports",icon:"🛹",color:"#ff6600",
  desc:"Grind, flip, and combo your way to high scores. Every trick and combo mechanic mastered.",
  tags:["Sports","Skateboarding","Arcade","Classic"],
  tips:[
    {level:"beginner",section:"Basics",title:"Ollie / Jump",controls:["X"],desc:"Press X to ollie (jump). Hold longer for higher jumps.",why:"The foundation of every trick. You can't do anything without jumping first."},
    {level:"beginner",section:"Basics",title:"Push / Move",controls:["Left Stick"],desc:"Use left stick to move and steer.",why:"Steering while in the air adjusts your landing angle."},
    {level:"beginner",section:"Tricks",title:"Kickflip / Heelflip",controls:["□ + direction"],desc:"Press Square + a direction for flip tricks.",why:"Flip tricks are your bread and butter for combos. Each direction = different trick."},
    {level:"beginner",section:"Tricks",title:"Grab Trick",controls:["○ + direction"],desc:"Press Circle + direction while airborne for grab tricks.",why:"Hold grabs longer for more points. But release before landing or you bail."},
    {level:"beginner",section:"Tricks",title:"Grind",controls:["△ near a rail/edge"],desc:"Press Triangle near a grindable edge to start grinding.",why:"Grinds extend combos along rails and edges. The core of high-score runs."},
    {level:"beginner",section:"Tricks",title:"Lip Trick",controls:["△ at top of ramp"],desc:"Press Triangle at the top of a half-pipe or quarter pipe.",why:"Lip tricks give easy points at the top of ramps. Hold for bonus."},
    {level:"intermediate",section:"Combos",title:"Manual",controls:["Right Stick up then down (or reverse)"],desc:"After landing, flick right stick up then down to manual (wheelie).",why:"Manuals CONNECT tricks on the ground. Land trick → manual → next trick = one big combo."},
    {level:"intermediate",section:"Combos",title:"Revert",controls:["R2 when landing on ramp"],desc:"Press R2 when landing on a ramp to revert.",why:"Reverts connect air tricks to ground tricks. Air → revert → manual → grind = massive combo."},
    {level:"intermediate",section:"Tricks",title:"Spine Transfer",controls:["R2 at ramp top"],desc:"Press R2 at the top of a spine ramp to transfer over to the other side.",why:"Accesses new areas and extends combos seamlessly."},
    {level:"intermediate",section:"Tricks",title:"Wall Ride",controls:["Ollie at wall → triangle"],desc:"Jump at a wall and grind it.",why:"Wall rides add variety and maintain combos when there's no rail nearby."},
    {level:"intermediate",section:"Tricks",title:"Boneless",controls:["X + X (double tap up)"],desc:"Double tap X while pushing up for a Boneless with extra height.",why:"More air time = more complex tricks and more points."},
    {level:"advanced",section:"Combos",title:"Combo Multiplier",controls:["Never repeat tricks"],desc:"Using different tricks in the same combo increases the multiplier.",why:"Repeating the same trick kills your multiplier. Variety = exponentially higher scores."},
    {level:"advanced",section:"Tricks",title:"Special Tricks",controls:["Fill meter → specific input"],desc:"Fill your special meter (top left) then input the specific command for character specials.",why:"Special tricks score massively more points. Each character has unique specials."},
    {level:"advanced",section:"Tricks",title:"Acid Drop / Bank Drop",controls:["R2 when falling toward ramp"],desc:"Press R2 when falling toward a ramp to transition smoothly into it.",why:"Maintains speed and enables combos when dropping off ledges into ramps."},
    {level:"advanced",section:"Tricks",title:"No-Comply",controls:["X + Left Stick down then up"],desc:"Quick pop into a trick with a unique animation.",why:"Adds variety to your combo for higher multipliers."},
    {level:"expert",section:"Combos",title:"Million Point Combos",controls:["Revert → Manual → Grind → Manual → repeat"],desc:"Chain: air trick → revert → manual → grind → manual → air trick → repeat indefinitely.",why:"Top players never end their combo. One continuous combo through the entire 2-minute run."},
    {level:"expert",section:"Movement",title:"Speed Management",controls:["Pump on ramps + no braking"],desc:"Pump by pressing down on ramps to gain speed without pushing.",why:"Maintaining speed means bigger airs means more points. Never brake in a combo."},
    {level:"expert",section:"Tricks",title:"Trick String Memorization",controls:["Learn all directional variants"],desc:"Each trick button has 12+ tricks depending on direction + modifiers.",why:"Knowing every variant means never repeating a trick in a combo. Infinite variety = infinite multiplier."}
  ]
},
{
  id:"riders",name:"Riders Republic",genre:"Sports / Extreme",category:"sports",icon:"🚵",color:"#ff4500",
  desc:"Bike, ski, snowboard, and wingsuit across a massive open world. Tricks, races, and mass events.",
  tags:["Sports","Extreme","Open World","Multiplayer"],
  tips:[
    {level:"beginner",section:"Biking",title:"Pedal / Accelerate",controls:["R2"],desc:"Hold R2 to pedal and accelerate on bikes.",why:"Speed management is key — you can go too fast and wipe out on turns."},
    {level:"beginner",section:"Biking",title:"Brake",controls:["L2"],desc:"Hold L2 to brake.",why:"Braking before turns prevents crashes. Tap for speed control, hold for hard stops."},
    {level:"beginner",section:"All Sports",title:"Steer",controls:["Left Stick"],desc:"Left stick controls direction for all sports.",why:"Wide, smooth turns maintain speed. Jerky inputs cause wipeouts."},
    {level:"beginner",section:"All Sports",title:"Jump",controls:["X"],desc:"Press X to jump or launch off ramps.",why:"Jumping lets you do tricks and avoid obstacles."},
    {level:"beginner",section:"Tricks",title:"Do Tricks",controls:["Right Stick + ○"],desc:"In the air, use right stick for flips and Circle + direction for grabs.",why:"Tricks build your trick meter and earn points."},
    {level:"beginner",section:"All Sports",title:"Rewind",controls:["L1"],desc:"Press L1 to rewind time after a crash.",why:"Rewind saves your race. You go back a few seconds without losing your position."},
    {level:"intermediate",section:"Snow",title:"Carve Turns",controls:["Left Stick + lean"],desc:"On skis or snowboard, lean into turns for tighter carving.",why:"Carving maintains speed better than sliding turns."},
    {level:"intermediate",section:"Wingsuit",title:"Wingsuit Controls",controls:["Left Stick (pitch/roll)"],desc:"Left stick controls pitch (up/down) and roll (left/right).",why:"Stay close to terrain for proximity points but not so close you crash."},
    {level:"intermediate",section:"Wingsuit",title:"Rocket Wingsuit Boost",controls:["R2"],desc:"Hold R2 to boost in the rocket wingsuit.",why:"Boost through checkpoints and recover from bad lines."},
    {level:"intermediate",section:"Tricks",title:"Grind",controls:["△ near rail"],desc:"Press Triangle near rails to grind.",why:"Grinds maintain speed and add combo points during trick events."},
    {level:"advanced",section:"Racing",title:"Draft / Slipstream",controls:["Stay behind opponent"],desc:"Ride directly behind another racer to gain a speed boost.",why:"Slipstream then slingshot past them. Classic racing strategy."},
    {level:"advanced",section:"Tricks",title:"Combo Chains",controls:["Trick → grind → trick → land"],desc:"Chain tricks, grinds, and transitions without touching the ground to combo.",why:"Combos multiply your score. One big combo beats twenty individual tricks."},
    {level:"advanced",section:"Racing",title:"Line Choice",controls:["Preview course → pick racing line"],desc:"In races, preview the course and pick optimal racing lines through checkpoints.",why:"A good line saves seconds per checkpoint. That adds up to huge time savings."},
    {level:"expert",section:"Mass Race",title:"Mass Race Strategy",controls:["Avoid the pack → find clean lines"],desc:"In 64-player mass races, avoid the chaos of the pack. Find clean lines on the edges.",why:"The pack causes crashes. Riding slightly off the main line avoids pileups."},
    {level:"expert",section:"Tricks",title:"Perfect Landing",controls:["Level out before touchdown"],desc:"Straighten your vehicle before landing to avoid crash penalties.",why:"Stomped landings maintain full speed. Bad landings slow you down or crash."}
  ]
}
]);
